src/objects/Activitytype__c.object
<CustomObject>
    <fields>
        <fullName>Bar_color__c</fullName>
        <label>Bar color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <inlineHelpText>Give a url to a icon for the activity type this should be in size 24x24 px</inlineHelpText>
        <label>Url to icon</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity types</label>
    <nameField>
        <label>Activity type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CRM_settings__c.object
<CustomObject>
    <fields>
        <fullName>Bar_color__c</fullName>
        <defaultValue>&quot;#FF9933,#A700DF,#369E2B&quot;</defaultValue>
        <inlineHelpText>Give the web color for each type in the CRM chart 
separated with comma. 
eg. #1223344,#112244,#335566</inlineHelpText>
        <label>Bar color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_performance_type__c</fullName>
        <label>CRM performance type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance, general</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Performance, project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance, marketing activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milestone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance, costcenter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Chart__c</fullName>
        <label>Chart</label>
        <picklist>
            <picklistValues>
                <fullName>Area charts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar charts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Line charts</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Spline charts</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expression_business_area__c</fullName>
        <inlineHelpText>Here you can enter which campaign to be included for the selected milestone, one row for each campaign</inlineHelpText>
        <label>Campaign</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expression_business_region__c</fullName>
        <inlineHelpText>Here you can enter which lead source to be included for the selected milestone, one row for each source</inlineHelpText>
        <label>Lead Source</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selector__c</fullName>
        <label>Selector</label>
        <picklist>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Source</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRM settings</label>
    <nameField>
        <label>Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Activitytype__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity type</label>
        <referenceTo>Activitytype__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_type__c</fullName>
        <label>User type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal user</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communities user</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Workspace__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>This text will come at top left side.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Workspaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Workspaces_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>html_description__c</fullName>
        <label>Presentation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Presentation</label>
    <nameField>
        <label>Headline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Presentation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MarketingAcitivityControllerTest.cls
@isTest(seeAllData=true)
 public class MarketingAcitivityControllerTest{
     static testMethod void Marketingactivity(){
        Profile p = [select id from profile where name='System Administrator']; 
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id, 
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ;  
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c); 
         Project__c objproject = new Project__c ();
         objproject.Name='test';
         objproject.Starts_date__c= System.now().date();
         objproject.Ends_date__c= System.now().date();
         objproject.OwnerId=plm.userid__c;
         insert objproject;
         System.assertEquals('test', objproject.name);
         
        musqot__ERP_Settings__c  ObjERPEdit=new musqot__ERP_Settings__c ();
        ObjERPEdit.Name='testERPEdit';
        ObjERPEdit.musqot__Selector__c='Business area';
        ObjERPEdit.musqot__erp_Chart__c='Bar charts';
        ObjERPEdit.musqot__Bar_color__c='#123344,#224466';
        ObjERPEdit.ERP_Performance_type__c='Performance, marketing activity';
        System.assertEquals('Business area', ObjERPEdit.musqot__Selector__c);
        insert ObjERPEdit;
        
        CRM_settings__c mr=new CRM_settings__c();
        mr.Bar_color__c='#369E2B';
        mr.Chart__c='Line chart';
        mr.CRM_performance_type__c='Performance, marketing activity';
        mr.Expression_business_area__c='APAC';
        mr.Expression_business_region__c='Lead';
        mr.Selector__c='test';
        insert mr;
        System.assertEquals('#369E2B', mr.Bar_color__c);
         
         musqot__Socialmedia_settings__c OBJSocial = new musqot__Socialmedia_settings__c();
        OBJSocial.name='testmedia';
        OBJSocial.musqot__Import_rate__c='Hour';        
        OBJSocial.musqot__Socialmedia_type__c='Facebook';
        OBJSocial.musqot__Watch_type__c='Downloads';
        OBJSocial.musqot__Chart__c='Bar charts';
        OBJSocial.musqot__Auto_import__c= true ;   
        OBJSocial.type__c='Performance, marketing activity';
        //OBJSocial.Type__c ='Milestone';
        insert OBJSocial;
        
          Activitytype__c objActiv = new Activitytype__c();
          objActiv.Name='musqot';
          objActiv.Icon__c='testicon';
          objActiv.Bar_color__c='blue';
          
          insert objActiv;
          System.assertEquals('musqot', objActiv.name);
          
         Marketing_activity__c objMarketingact=new Marketing_activity__c();
         objMarketingact.Name='test';
         objMarketingact.Description__c='tdescriptionest';
         objMarketingact.Status__c='completed';
         objMarketingact.musqot__ERP__c='testERP';
         objMarketingact.musqot__Social_media__c='testSocial';
         objMarketingact.musqot__CRM__c='testCRM';
         objMarketingact.musqot__Activitytype__c=objActiv.id;
         insert objMarketingact;
         System.assertEquals('test', objMarketingact.name);
        
         Workspace__c objectwork1=new Workspace__c();
         objectwork1.Name='test';
         objectwork1.ProjectName__c=objproject.id;
         objectwork1.Description__c='test1';
         objectwork1.html_description__c='test123';
         insert objectwork1;
         
         Workspace__c objectwork=new Workspace__c();
         objectwork.Name='test';
         objectwork.ProjectName__c=objproject.id;
         objectwork.Description__c='test1';
         objectwork.html_description__c='test123';
         System.assertEquals('test', objectwork.name);
         insert objectwork;
         
         Task t=new Task();
         t.Task_name__c='test';
         t.Status='completed';
         t.Priority='high';
         t.Allocated_h__c=12;
         System.assertEquals('test', t.Task_name__c);
         
         ApexPages.currentPage().getParameters().put('marktid', objMarketingact.id);
         ApexPages.StandardController sc = new ApexPages.standardController(objMarketingact);
         //MarketingAcitivityController objMRKT1= new MarketingAcitivityController (); 
         MarketingAcitivityController objMRKT= new MarketingAcitivityController (sc);
         //Activitytype__c  actType = [SELECT Id,musqot__F__c FROM musqot__Activitytype__c  WHERE Id =:objMarketingact.musqot__Activitytype__c];
         List<selectoption>temp=objMRKT.ACTList;
         List<Schema.FieldSetMember>  temp1=objMRKT.getFields();
         List<SelectOption> acttemp=objMRKT.getActivityColors();
         List<SelectOption>  temp2=objMRKT.SocialFilter;
         List<SelectOption> temp23=objMRKT.ERPFilter;
         List<SelectOption> temp4=objMRKT.CRMFilter;
         String[] plan=objMRKT.ERPItems;
         String[] plan1=objMRKT.CRMItems; 
         String[] plan2=objMRKT.SocialItems;
         
         List<String> erpstringList = new List<String>{'string1','string2','string3'};
         //try{
             objMRKT.ERPItems= erpstringList;         
             objMRKT.CRMItems= erpstringList;
             objMRKT.SocialItems= erpstringList;
         //}catch(Exception e){}       
         objMRKT.save();
         try{
          objMRKT.getFieldsetList('string marketid');
         }catch(Exception e){} 
         objMRKT.cancel();
         objMRKT.gotoEditMode();
         objMRKT.gotoInfoMode();
         objMRKT.getCustomSettRec(); 
        }
    }