src/objects/Activity__c.object
<CustomObject>
    <description>use for Musqot application setting</description>
    <fields>
        <fullName>Use_Allocation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Allocation</label>
        <type>Checkbox</type>
    </fields>
    <label>Musqot setting</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Musqot setting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Allocation_amount__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Costcentre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost center</label>
        <referenceTo>Costcentre__c</referenceTo>
        <relationshipLabel>Allocation Amounts</relationshipLabel>
        <relationshipName>Allocation_amounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation amount</label>
    <nameField>
        <label>Allocation Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Costcentre__c.object
<CustomObject>
    <customHelpPage>Costcentershelppage</customHelpPage>
    <fields>
        <fullName>StatusImage__c</fullName>
        <formula>CASE(Status__c, &apos;Not started&apos;, IMAGE(&apos;/resource/1433929854000/musqot__Planned&apos;,TEXT(Status__c),16,16), &apos;Active&apos;, IMAGE(&apos;/resource/1433930034000/musqot__Active&apos;,TEXT(Status__c),16,16),&apos;Closed&apos;,IMAGE(&apos;/resource/1433930023000/musqot__Deferred&apos;,TEXT(Status__c),16,16),  IMAGE(&apos;/resource/1446332034000/musqot__StatusOther&apos;,TEXT(Status__c),16,16))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not started</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>cc_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DONT USE THIS</description>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Costcentres</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cost center</label>
    <nameField>
        <label>Cost centre name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Members__c.object
<CustomObject>
    <description>Member in a project/sub project</description>
    <fields>
        <fullName>Cost_center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost center</label>
        <referenceTo>Costcentre__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member set name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Costcenter_Ctrl.cls
/*******************************************************
Class Name: Costcenter_Ctrl
Author:Nagaraju G             Last modified by:Poornima
Date:23/7/2014                Date:28/10/2015
********©2013 Musqot marketing technology Pvt ltd *******/
public  with sharing class Costcenter_Ctrl{  
 public boolean ccRec{get;set;}
 public string cosid{get;set;}
 public List<Id>userRole;
 public string usrProfileName;
 public list<Activity__c> act{get;set;}
    public Costcenter_Ctrl() {
      userRole=new List<Id>();
      usrProfileName = [select u.Profile.Name 
                          from User u 
                          where u.id =:Userinfo.getUserId()].Profile.Name;
      act=[SELECT Id, Use_Allocation__c 
           FROM Activity__c limit 1];
      if(act[0].Use_Allocation__c ==true){
          ccRec=true; 
        }
      if(act[0].Use_Allocation__c ==false){
          ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Musqot is configurated to not use Cost Centers');
          ApexPages.addMessage(myMsg); 
      }
      List<Members__c>MemberList=[SELECT Id, Name, ProjUsers__c, Cost_center__c 
                                              FROM Members__c 
                                              WHERE ProjUsers__c =:UserInfo.getUserId()];
        for(Members__c m:MemberList){
            userRole.add(m.Cost_center__c);
        }
    }    
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                if(usrProfileName=='System Administrator'){
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                      [SELECT Id, Name,Status__c ,StatusImage__c,cc_Owner__c, Owner.name 
                       FROM  Costcentre__c ORDER BY CreatedDate ASC limit 500]));
                }
                
                else{
                 setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                      [SELECT Id, Name,Status__c ,StatusImage__c,cc_Owner__c, Owner.name 
                       FROM  Costcentre__c WHERE Id IN:userRole OR OwnerId=:UserInfo.getUserId() ORDER BY CreatedDate ASC limit 500]));                      
                }
             }
            return setCon;
        }
        set;
    }  
    public List<Costcentre__c> getCostcenters() {
         setCon.setpagesize(10);
         return (List<Costcentre__c>) setCon.getRecords();
    }
    Public PageReference newCostcenter(){
        PageReference NewCostcenter=new PageReference('/apex/NewCostcenter?pageType=new');
        NewCostcenter.setredirect(true);
        return NewCostcenter; 
    }
    public pageReference DeleteCostcen(){
        try{
        musqot__Costcentre__c cos = [Select id, name,StatusImage__c,Status__c ,ownerId from Costcentre__c where id=:cosid];       
        list<Allocation_amount__c> allocat=[Select Id, Costcentre__c 
                                            from  Allocation_amount__c 
                                            where Approved__c=true and Costcentre__c=:cos.id];          
           if(allocat.isEmpty()){ 
               delete cos;    
            }else{
               ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Musqot can´t delete the Cost center, ');
               ApexPages.addMessage(myMsg); 
         }
        }catch(Exception e){}
         Pagereference PR;  
         Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
         String objPrefix = globalDescribe.get('musqot__Costcentre__c').getDescribe().getkeyprefix();
         PageReference prRef = new PageReference('/' + objPrefix+'/o');
         prRef.setRedirect(true);
         return prRef;
         
    }
    public pageReference editCostcen(){
        PageReference prj=new PageReference ('/apex/NewCostcenter?id='+EncodingUtil.urlEncode(cosid,'UTF-8'));
        return prj;
    }
     //--Redirect to coscenterDetail---
    public PageReference gotoccDetail() {
        String cosId= ApexPages.currentPage().getParameters().get('cosId');
        PageReference pgr;   
        pgr =new PageReference ('/apex/Costcenterdetail?Id='+EncodingUtil.urlEncode(cosId,'UTF-8')+'&&sfdc.override=1');
        return pgr;
    }
}