src/objects/Activitytype__c.object
<CustomObject>
    <fields>
        <fullName>Bar_color__c</fullName>
        <label>Bar color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <inlineHelpText>Give a url to a icon for the activity type this should be in size 24x24 px</inlineHelpText>
        <label>Url to icon</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity types</label>
    <nameField>
        <label>Activity type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Activitytype__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity type</label>
        <referenceTo>Activitytype__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/marketingClassTest.cls
/*******************************************************
Class Name: marketingClassTest
Author:Nagaraju         Last modified by: Janardhan reddy
Date :21/7/2014         Date : 19/3/2105                    
********©2013 Musqot marketing technology Pvt ltd *******/
@isTest(seeAllData=true)
    public class marketingClassTest{
    static testMethod void  marketingClassMethod(){
        Project__c objproject = new Project__c ();
        objproject.Name='test';
        //objproject.Project_type__c='test';
        objproject.Starts_date__c= System.now().date();
        objproject.Ends_date__c= System.now().date();
        System.assertEquals('test', objproject.name);
        insert objproject;
        Subproject__c objsubpro=new Subproject__c();
        objsubpro.Name='testsub';
        objsubpro.Starts_date__c=System.now().date();
        objsubpro.musqot__Parent_project__c=objproject.id;
        objsubpro.Ends_date__c=System.now().date();
        System.assertEquals('testsub', objsubpro.name);
        insert objsubpro;
         
        Activitytype__c objActiv = new Activitytype__c();
         objActiv.Name='musqot';
         objActiv.Icon__c='testicon';
         objActiv.Bar_color__c='blue';
         insert objActiv;
         
        /* List<StaticResource> resourceList = [
         SELECT Name, NamespacePrefix, SystemModStamp 
         FROM StaticResource ];*/
        
        System.assertEquals('musqot', objActiv.name);
        
        Marketing_activity__c objMarketingactivity=new Marketing_activity__c();
        objMarketingactivity.Name='test';
        //objMarketingactivity.Project__c=objproject.id;
        objMarketingactivity.Description__c='tdescriptionest';
        objMarketingactivity.Status__c='completed';
        objMarketingactivity.musqot__Activitytype__c=objActiv.id;
        objMarketingactivity.musqot__Plan__c=objproject .id;
        objMarketingactivity.musqot__Project__c=objsubpro.id;
        System.assertEquals('test', objMarketingactivity.name);
        insert objMarketingactivity;
         String tabId = System.currentPageReference().getParameters().get('tabId');
        ApexPages.currentPage().getParameters().put('id', objMarketingactivity.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objMarketingactivity);
        test.startTest(); 
        marketingClass objMarket1= new marketingClass();
        marketingClass objMarket = new marketingClass(sc);
        List<selectoption>temp=objMarket.ACTList;
        List<SelectOption> tempact = objMarket.getActivityColors();
        objMarket.save();
        objMarket.cancel();
 
        }
         static testMethod void  marketingClassMethod2(){
        Project__c objproject = new Project__c ();
        objproject.Name='test';
        //objproject.Project_type__c='test';
        objproject.Starts_date__c= System.now().date();
        objproject.Ends_date__c= System.now().date();
        System.assertEquals('test', objproject.name);
        insert objproject;
        Subproject__c objsubpro=new Subproject__c();
        objsubpro.Name='testsub';
        objsubpro.Starts_date__c=System.now().date();
        objsubpro.musqot__Parent_project__c=objproject.id;
        objsubpro.Ends_date__c=System.now().date();
        System.assertEquals('testsub', objsubpro.name);
        insert objsubpro;
         
        Activitytype__c objActiv = new Activitytype__c();
         objActiv.Name='musqot';
         objActiv.Icon__c='testicon';
         objActiv.Bar_color__c='blue';
         insert objActiv;
         
        /* List<StaticResource> resourceList = [
         SELECT Name, NamespacePrefix, SystemModStamp 
         FROM StaticResource ];*/
        
        System.assertEquals('musqot', objActiv.name);
        
        Marketing_activity__c objMarketingactivity=new Marketing_activity__c();
        objMarketingactivity.Name='test';
        //objMarketingactivity.Project__c=objproject.id;
        objMarketingactivity.Description__c='tdescriptionest';
        objMarketingactivity.Status__c='completed';
        objMarketingactivity.musqot__Activitytype__c=objActiv.id;
        objMarketingactivity.musqot__Plan__c=objproject .id;
        objMarketingactivity.musqot__Project__c=objsubpro.id;
        System.assertEquals('test', objMarketingactivity.name);
        insert objMarketingactivity;
         String tabId = System.currentPageReference().getParameters().get('tabId');
        ApexPages.currentPage().getParameters().put('subid', objsubpro.id);
       
        
        ApexPages.StandardController sc = new ApexPages.standardController(objMarketingactivity);
        test.startTest(); 
        marketingClass objMarket1= new marketingClass();
        marketingClass objMarket = new marketingClass(sc);
        List<selectoption>temp=objMarket.ACTList; 
         List<Schema.FieldSetMember>  temp1=objMarket .getFields();
         try{
         objMarket.getFieldsetList('String marketid');
         }catch(exception e){}
        objMarket.save();
        objMarket.cancel();
        }

    }