src/objects/Activity__c.object
<CustomObject>
    <description>use for Musqot application setting</description>
    <fields>
        <fullName>Plan_access_controll__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is checked then you need to defined all user who should have access to each Plan</inlineHelpText>
        <label>Plan access controll</label>
        <type>Checkbox</type>
    </fields>
    <label>Musqot setting</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Musqot setting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/plantype__c.object
<CustomObject>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusImage__c</fullName>
        <description>old
IMAGE(&apos;/servlet/servlet.FileDownload?file=&apos;+musqot__Status_Image_Id__c,TEXT(musqot__Status__c),16,16)</description>
        <formula>CASE(Status__c, &apos;Not Started&apos;, IMAGE(&apos;/resource/1433929854000/musqot__Planned&apos;,TEXT(Status__c),16,16), &apos;In Progress&apos;, IMAGE(&apos;/resource/1433930034000/musqot__Active&apos;,TEXT(Status__c),16,16),&apos;Completed&apos;,IMAGE(&apos;/resource/1433930013000/musqot__Finnished&apos;,TEXT(Status__c),16,16),&apos;Deferred&apos;,IMAGE(&apos;/resource/1433930023000/musqot__Deferred&apos;,TEXT(Status__c),16,16), IMAGE(&apos;/resource/1443021886000/musqot__StatusOther&apos;,TEXT(Status__c),16,16))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlansListView_Ctrl.cls
/*******************************************************
Class Name: PlansListView_Ctrl
Author:Nagaraju G             Last modified by:Raju GN
Date:28/10/2015               Date:28/10/2015
Desc:Adding if block to show the plan records Line no:52-66
********©2013 Musqot marketing technology Pvt ltd *******/
public  with sharing class PlansListView_Ctrl{ 
    public List<Project__c>plansRecList{get;set;}
    public List<Id>userRoleSet;
    public Activity__c musqotSettingRec{get;set;}
    public string usrProfileName;
    public string NewPlanUrl {get;set;}
    public PlansListView_Ctrl(){
        plansRecList=new list<Project__c>();
        userRoleSet=new List<Id>();
        usrProfileName = [select u.Profile.Name 
                          from User u 
                          where u.id =:Userinfo.getUserId()].Profile.Name;
        musqotSettingRec=[SELECT Id, Name, Plan_access_controll__c 
                          FROM Activity__c limit 1];
        List<Musqot_member__c>planMemberList=[SELECT Id, Name, userid__c, Plan__c 
                                              FROM Musqot_member__c 
                                              WHERE userid__c =:UserInfo.getUserId()];
        for(Musqot_member__c m:planMemberList){
            userRoleSet.add(m.Plan__c);
        }   
        NewPlanUrl = '/apex/Planpage_Resp?pageType='+ EncodingUtil.urlEncode('new','UTF-8');
    }
    //--Redirect to Planpage new plan---
    public Pagereference redirectPlanpage(){
        PageReference newPlanPage=new PageReference('/apex/Planpage?pageType='+ EncodingUtil.urlEncode('new','UTF-8'));
        newPlanPage.setredirect(true);
        return newPlanPage; 
    }
    //--Redirect to PlanDetail---
    public PageReference gotoPlanDetail() {
        String plnId= ApexPages.currentPage().getParameters().get('plnId');
        PageReference pgr;   
        pgr =new PageReference ('/apex/ProjectDetails?id='+EncodingUtil.urlEncode(plnId,'UTF-8')+'&&sfdc.override=1');
        return pgr;
    }
    
    // added by Narendra
    public PageReference gotoPlanDetailResp() {
        String plnId= ApexPages.currentPage().getParameters().get('plnId');
        PageReference pgr;   
        pgr =new PageReference ('/apex/ProjectDetails_Resp?Id='+EncodingUtil.urlEncode(plnId,'UTF-8')+'&&sfdc.override=1');
        return pgr;
    }
    //--Pegenation Start here---
    public ApexPages.StandardSetController setCon{
        get {
            if(setCon == null){
                //to check Plan access controll here 
                if(musqotSettingRec.Plan_access_controll__c==true){
                    //If logdin user profile equels to systemadminstrator,he can see all plans all time.
                    if(usrProfileName=='System Administrator'){
                       setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                          [SELECT  Name,Plantype__r.Name, Starts_date__c, Ends_date__c, Owner.Name, 
                           Status__c, StatusImage__c 
                           FROM Project__c  ORDER BY Name limit 1000]));
                    }
                    //else only see ,if logdin user owner of the plan or member of the plan(Non systemadminstrator users)
                    else{
                        setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                            [SELECT  Name,Plantype__r.Name,Starts_date__c,Ends_date__c,Owner.Name, 
                             Status__c, StatusImage__c 
                             FROM Project__c 
                             WHERE Id IN:userRoleSet OR OwnerId=:UserInfo.getUserId() ORDER BY Name limit 1000]));
                    }
                    
                }
                //If Plan access controll is uncheck
                else{
                     setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                          [SELECT  Name,Plantype__r.Name, Starts_date__c, Ends_date__c, Owner.Name, Status__c, StatusImage__c 
                           FROM Project__c  ORDER BY Name limit 1000]));
                }
            }
            return setCon;
        }
        set;
    }  
    public List<Project__c> getPlanRecs() {
         setCon.setpagesize(10);
         return (List<Project__c >)setCon.getRecords();
    }
}