src/objects/Activitytype__c.object
<CustomObject>
    <fields>
        <fullName>Bar_color__c</fullName>
        <label>Bar color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <inlineHelpText>Give a url to a icon for the activity type this should be in size 24x24 px</inlineHelpText>
        <label>Url to icon</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity types</label>
    <nameField>
        <label>Activity type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActivityTypeClassTest.cls
/**************************************************************
Class Name: ActivityTypeClassTest
Author: Nagaraju G         Last modified by:G Janardhanreddy 
Date  :  18/7/2014            Date:18/03/2015
***********©2013 Musqot marketing technology Pvt ltd **********/
@isTest(seeAllData=true)
public class ActivityTypeClassTest{
    static testmethod void ActivityTypeClass() {
     Activitytype__c objActiv = new Activitytype__c();
     objActiv.Name='musqot';
     objActiv.Icon__c='testicon';
     objActiv.Bar_color__c='blue';
     System.assertEquals('musqot', objActiv.name);
     insert objActiv;
      Activitytype__c  ActivityType= [select Icon__c from Activitytype__c where id = :objActiv.id];
             
     ApexPages.currentPage().getParameters().put('id', objActiv.id);
     PageReference pageRef = Page.Purchaseorderpage;
     Test.setCurrentPage(pageRef);  
     ApexPages.StandardController sc = new ApexPages.standardController(objActiv);
     test.startTest();
     ActivityTypeClass acttype = new ActivityTypeClass(sc);
     List<SelectOption>  temp1=acttype.Fieldsetlist;
     acttype.ActivityType=objActiv;         
     acttype.Save();
     acttype.banner='test';
     acttype.Cancel();
     acttype.selectActivityImage();
    
     acttype.closePopUp();
     acttype.showUplodePopUp();
     acttype.showActivityImagPopUp();
     try{
     acttype.createStaticResource();
     acttype.getIcon();
     //acttype.handleSaveResults();
     }catch (Exception e){}
     ActivityTypeClass.GetResourceURL('Sponsor');
                      
     }
     static testmethod void ActivityTypeClass1() {
     Activitytype__c objActiv = new Activitytype__c();
     objActiv.Name='musqot';
     objActiv.Icon__c='testicon';
     objActiv.Bar_color__c='blue';
     System.assertEquals('musqot', objActiv.name);
     insert objActiv;
      Activitytype__c  ActivityType= [select Icon__c from Activitytype__c where id = :objActiv.id];
             
     ApexPages.currentPage().getParameters().put('id', objActiv.id);
     PageReference pageRef = Page.Purchaseorderpage;
     Test.setCurrentPage(pageRef);  
     ApexPages.StandardController sc = new ApexPages.standardController(objActiv);
     test.startTest();
     ActivityTypeClass acttype = new ActivityTypeClass(sc);
     List<SelectOption>  temp1=acttype.Fieldsetlist;
     acttype.ActivityType=objActiv;   
     acttype.fileName='test'; 
     acttype.fileImage=blob.valueof('sample');
     acttype.filesize=1048577;     
     acttype.Save();
     acttype.banner='test';
     acttype.Cancel();
     acttype.selectActivityImage();
    
     acttype.closePopUp();
     acttype.showUplodePopUp();
     acttype.showActivityImagPopUp();
     try{
     acttype.createStaticResource();
     acttype.getIcon();
     //acttype.handleSaveResults();
     }catch (Exception e){}
     ActivityTypeClass.GetResourceURL('Sponsor');
                      
     }
     static testmethod void ActivityTypeClass2(){
     Activitytype__c objActiv = new Activitytype__c();
     objActiv.Name='musqot';
     objActiv.Icon__c='testicon';
     objActiv.Bar_color__c='blue';
     System.assertEquals('musqot', objActiv.name);
     insert objActiv;
      Activitytype__c  ActivityType= [select Icon__c from Activitytype__c where id = :objActiv.id];
             
     ApexPages.currentPage().getParameters().put('id', objActiv.id);
     PageReference pageRef = Page.Purchaseorderpage;
     Test.setCurrentPage(pageRef);  
     ApexPages.StandardController sc = new ApexPages.standardController(objActiv);
     test.startTest();
     ActivityTypeClass acttype = new ActivityTypeClass(sc);
     List<SelectOption>  temp1=acttype.Fieldsetlist;
     acttype.ActivityType=objActiv;   
     acttype.fileName='test'; 
     acttype.fileImage=blob.valueof('sample');
     acttype.filesize=1048570;     
     acttype.Save();
     acttype.banner='test';
     acttype.Cancel();
     acttype.selectActivityImage();
    
     acttype.closePopUp();
     acttype.showUplodePopUp();
     acttype.showActivityImagPopUp();
     try{
     acttype.createStaticResource();
     acttype.getIcon();
     //acttype.handleSaveResults();
     }catch (Exception e){}
     ActivityTypeClass.GetResourceURL('Sponsor');
                      
     }
 }