src/objects/Activitytype__c.object
<CustomObject>
    <fields>
        <fullName>Bar_color__c</fullName>
        <label>Bar color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F__c</fullName>
        <description>This should be a choice from Marketing activities field set name</description>
        <label>Fieldset</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <inlineHelpText>Give a url to a icon for the activity type this should be in size 24x24 px</inlineHelpText>
        <label>Url to icon</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity types</label>
    <nameField>
        <label>Activity type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_type__c</fullName>
        <label>User type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal user</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communities user</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/plantype__c.object
<CustomObject>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActivityEditControllerTest.cls
/***********************************************************
Class Name: ActivityEditControllerTest
Author: Nagaraju G         Last modified by:G Janardhanreddy 
Date  :  18/7/2014            Date:18/03/2015
*************©2013 Musqot marketing technology Pvt ltd ******/
@isTest(seeAllData=true)
public class ActivityEditControllerTest{
     static testmethod void Activitytest() {
     Profile p = [select id from profile where name='System Administrator']; 
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id,
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ;
     
     Activitytype__c objActivitytype = new Activitytype__c();
     objActivitytype.Name='test';
     objActivitytype.Icon__c='testicon';
     objActivitytype.Bar_color__c ='red';
     System.assertEquals('test', objActivitytype.name);
     try{
     insert objActivitytype;
     }catch(exception e){}
	 
     Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        //plm.Plan__c=objproj.id;        
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('test', objActivitytype.name);
         
     Project__c objproj = new Project__c();
     objproj .Name = 'testrec';
     objproj .Plantype__c =  null;
     objproj .Starts_date__c = Date.Today();
     objproj .Ends_date__c= Date.Today();
     objproj .Status__c = 'testpick'; 
     objproj.Ownerid=plm.userid__c;
     System.assertEquals('testrec', objproj.name);
     insert objproj ;
     try{
     Activitytype__c act=new Activitytype__c ();
     act.Name='musqot';
     act.Bar_color__c  ='green';
     System.assertEquals ('green',act.Bar_color__c);
     act.Icon__c ='musqottech'; 
     act.F__c = null;          
     insert act;
           Activitytype__c act1=[select id,name,Bar_color__c,Icon__c,F__c  from Activitytype__c  Where Id =:objActivitytype.Id];
           update act1;
      
     }catch(exception e){}	 
     
     Activitytype__c OBJActivit= new Activitytype__c();
     OBJActivit.Name='test';
     OBJActivit.Icon__c='testicon';
     OBJActivit.Bar_color__c ='red';
     System.assertEquals('test', OBJActivit.name);
     try{
     insert OBJActivit;
     }catch(exception e){}
    //}
    test.startTest();
    PageReference pageRef = Page.ActivitytypesPage;
    Test.setCurrentPage(pageRef); 
     
    ApexPages.currentPage().getParameters().put('Plans.id',objActivitytype.id);
    ApexPages.StandardController sc = new ApexPages.standardController(objActivitytype);
     
     ActivityEditController objact1 = new ActivityEditController ();
     ActivityEditController objactt = new ActivityEditController (sc);
     //objactt.redirectPage1();
     objactt.LoadData();
     objactt.getPln(); 
     objactt.DeleteAccount(); 
     objactt.NewPrtype();
     objactt.Save();
     objactt.Cancel();
          try{
        objactt.redirectPage1();
    }catch(Exception e){
        system.debug('exception caught');
    }

     ActivityEditController.GetResourceURL('Sponsor');      
     
     test.stopTest();  
     
  }
}