src/objects/Activitytype__c.object
<CustomObject>
    <fields>
        <fullName>Bar_color__c</fullName>
        <label>Bar color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <inlineHelpText>Give a url to a icon for the activity type this should be in size 24x24 px</inlineHelpText>
        <label>Url to icon</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity types</label>
    <nameField>
        <label>Activity type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CRM_settings__c.object
<CustomObject>
    <fields>
        <fullName>Bar_color__c</fullName>
        <defaultValue>&quot;#FF9933,#A700DF,#369E2B&quot;</defaultValue>
        <inlineHelpText>Give the web color for each type in the CRM chart 
separated with comma. 
eg. #1223344,#112244,#335566</inlineHelpText>
        <label>Bar color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CRM settings</label>
    <nameField>
        <label>Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ERP_logfile__c.object
<CustomObject>
    <fields>
        <fullName>Imported__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Imported</label>
        <type>Checkbox</type>
    </fields>
    <label>ERP logfile</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP logfile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ERP_sales_obj__c.object
<CustomObject>
    <fields>
        <fullName>ERP_logfile__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ERP logfile</label>
        <referenceTo>ERP_logfile__c</referenceTo>
        <relationshipName>ERP_sales_obj</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>ERP Sales Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP_sales_obj</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ERP_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Bar_color__c</fullName>
        <defaultValue>&quot;#FF9933,#A700DF,#369E2B&quot;</defaultValue>
        <inlineHelpText>Give the web color for each type in the ERP chart 
Separated with comma. 
eg. #1223344,#112244,#335566</inlineHelpText>
        <label>Bar color</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ERP Settings</label>
    <nameField>
        <label>Settings name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Activitytype__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity type</label>
        <referenceTo>Activitytype__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRM__c</fullName>
        <label>Performance CRM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ERP__c</fullName>
        <label>Performance ERP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Social_media__c</fullName>
        <inlineHelpText>This field is a container for Socialmedia setting, on this marketing activity.
DONT DO CHANGE THIS!</inlineHelpText>
        <label>Performance Social media</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/plantype__c.object
<CustomObject>
    <fields>
        <fullName>Barcolor__c</fullName>
        <description>sample number after # hex color</description>
        <label>Barcolor</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>CRM__c</fullName>
        <label>Performance CRM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ERP__c</fullName>
        <label>Performance ERP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Social_media__c</fullName>
        <label>Performance Social media</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <inlineHelpText>Enter a hexadecimal color (excluding #)</inlineHelpText>
        <label>Color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <label>Plan type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Social_media_data__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Social media data</label>
    <nameField>
        <label>Social media name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social media data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/socialmedia_settings__c.object
<CustomObject>
    <description>The Name will show-up in the Performance Gantt view.</description>
    <fields>
        <fullName>Bar_color__c</fullName>
        <defaultValue>&quot;#222,#666,#ccc&quot;</defaultValue>
        <label>Bar color</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Socialmedia Settings</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Socialmedia Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>CRM__c</fullName>
        <label>Performance CRM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ERP__c</fullName>
        <label>Performance ERP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Social_media__c</fullName>
        <label>Performance Social media</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectPerformanceControllerTest.cls
/*******************************************************
Class Name: ProjectPerformanceControllerTest
Author:Hussain      Last modified by: Hussain
Date:  20/04/2015      Date:20/04/2015
********©2013 Musqot marketing technology Pvt ltd *******/
@isTest(seeAllData=true)
Public class ProjectPerformanceControllerTest{
    static testMethod void  TestProjectPerformanceController(){ 
        Plantype__c pt = new Plantype__c();
        pt.Barcolor__c = '6E766F';
        pt.Name = 'Zuri';
        System.assertEquals('Zuri', pt.name);
        insert pt;
        
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress'; 
        prj.musqot__ERP__c='test';
        prj.musqot__CRM__c='test';
        prj.musqot__Social_media__c='test';
        System.assertEquals('ITC', prj.name);        
        insert prj;
        
        Project_type__c prjType = new Project_type__c();
        prjType.Name = 'Business';
        prjType.Color__c = 'FFFF01';
        System.assertEquals('Business', prjType.name);
        insert prjType;
         
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress';
        subPrj.musqot__ERP__c= 'ERP';
        subPrj.musqot__CRM__c= 'CRM';
        subPrj.musqot__Social_media__c= 'Socialmedia'; 
        subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Subproject__c subsubPrj = new Subproject__c();         
        subsubPrj.Name='ITC Project';
        subsubPrj.Parent_project__c = prj.Id;
        subsubPrj.Ends_date__c = system.toDay().addDays(3);
        subsubPrj.Starts_date__c= system.toDay();
        subsubPrj.Status__c = 'In Progress';
        subsubPrj.Project_del__c = subPrj.Id;  
        subsubPrj.Project_type__c = prjType.Id;
        subsubPrj.musqot__ERP__c='test';
        subsubPrj.musqot__CRM__c='test';
        subsubPrj.musqot__Social_media__c='test';
        System.assertEquals('ITC Project', subsubPrj.name);
        insert subsubPrj;
        
        Activitytype__c objActivity = new Activitytype__c(); 
        objActivity.Name='test';
        objActivity.Icon__c='testicon';
        objActivity.Bar_color__c ='red';   
        insert objActivity;
        
         Marketing_activity__c objMarketingact=new Marketing_activity__c();
         objMarketingact.Name='test';
         objMarketingact.Description__c='tdescriptionest';
         objMarketingact.Status__c='completed'; 
         objMarketingact.Activitytype__c = objActivity.Id;
         objMarketingact.Starts_date__c = system.today();
         objMarketingact.Ends_date__c= system.today();
         objMarketingact.Project__c=subsubPrj.id;
         objMarketingact.ERP__c='testERP';
         objMarketingact.CRM__c='testCRM';
         objMarketingact.Social_media__c='facebook';
         insert objMarketingact;
         System.assertEquals('test', objMarketingact.Name);
        
        ERP_logfile__c err = new ERP_logfile__c();
        err.Imported__c = true;
        err.Import_message__c = 'Good';
        err.Number_of_records__c = 10;
        insert err;
        
        ERP_sales_obj__c ess = new ERP_sales_obj__c();
        ess.Name = 'test';
        ess.Business_region__c = 'APAC';
        ess.Business_area__c = 'Prodcut';
        ess.sales_import_id__c = 'uftyft';
        ess.Sales_date__c = system.today();
        ess.Sales__c = 1000.00;
        ess.Sales_import_date__c = system.today();
        ess.ERP_logfile__c = err.Id;
        
        insert ess;
        
        socialmedia_settings__c ss = new socialmedia_settings__c();
        ss.Socialmedia_type__c = 'Facebook';
        ss.Import_rate__c = 'Day';
        ss.Watch_type__c = 'Visitor';
        ss.Chart__c = 'bar';
        insert ss;
        
        Social_media_data__c smd = new Social_media_data__c();        
        smd.Date__c = system.today();
        smd.Number_of_likes__c = 4;
        smd.Socialmedia_Settings__c = ss.Id; 
        smd.Name = 'test';              
        insert smd;
        
        PageReference testPage = new pagereference('/apex/ProjectPerformance');
        testPage.getParameters().put('id', 'prj.id');
        Test.setCurrentPage(testPage);
        
        ApexPages.currentPage().getParameters().put('planid', prj.id);  
        ProjectPerformanceController GPC = new ProjectPerformanceController();
        ProjectPerformanceController.GanttRow wrp=new ProjectPerformanceController.GanttRow();
           List<ERP_Settings__c> temp1=GPC.erpChartList;  
            List<CRM_Settings__c> temp2=GPC.crmChartList; 
        List<socialmedia_settings__c> temp3=GPC.mediaSettigs;
        GPC.gotoPlanPage();
        GPC.getjsString();
        GPC.gettaskstyleString();         
        GPC.getdataString();
        GPC.getFbData();
        GPC.showSelectedPlanTypes();
        GPC.getData();
        List<SelectOption> opl = GPC.PlanList;
        //GPC.gotoGanttPage();
        GPC.IsDeleted=true;
        //GPC.selStr='test';             
        ProjectPerformanceController.GanttRow ganttwrap= new ProjectPerformanceController.GanttRow();
        ganttwrap.idPH='ph';
        ganttwrap.text='testPH';
        ganttwrap.typePH='testPH';
        ganttwrap.start_date='sdate';
        ganttwrap.description='desc';
        ganttwrap.duration=1;
        ganttwrap.progress=100;
        ganttwrap.open=false;
        ganttwrap.parent='testParent';
        ganttwrap.img='testimg';
        ganttwrap.objType='asia';
        ganttwrap.actImg='testact';              
        }
     static testMethod void  TestProjectPerformanceController1(){ 
        Plantype__c pt = new Plantype__c();
        pt.Barcolor__c = '6E766F';
        pt.Name = 'Zuri';
        System.assertEquals('Zuri', pt.name);
        insert pt;
        
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';        
        System.assertEquals('ITC', prj.name);        
        insert prj;
        
        Project_type__c prjType = new Project_type__c();
        prjType.Name = 'Business';
        prjType.Color__c = 'FFFF01';
        System.assertEquals('Business', prjType.name);
        insert prjType;
         
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress';
        subPrj.musqot__ERP__c= 'ERP';
        subPrj.musqot__CRM__c= 'CRM';
        subPrj.musqot__Social_media__c= 'Socialmedia'; 
        subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Subproject__c subsubPrj = new Subproject__c();         
        subsubPrj.Name='ITC Project';
        subsubPrj.Parent_project__c = prj.Id;
        subsubPrj.Ends_date__c = system.toDay().addDays(3);
        subsubPrj.Starts_date__c= system.toDay();
        subsubPrj.Status__c = 'In Progress';
        subsubPrj.Project_del__c = subPrj.Id;  
        subsubPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subsubPrj.name);
        insert subsubPrj;
        
        Activitytype__c objActivity = new Activitytype__c(); 
        objActivity.Name='test';
        objActivity.Icon__c='testicon';
        objActivity.Bar_color__c ='red';   
        insert objActivity;
        
         Marketing_activity__c objMarketingact=new Marketing_activity__c();
         objMarketingact.Name='test';
         objMarketingact.Description__c='tdescriptionest';
         objMarketingact.Status__c='completed'; 
         objMarketingact.Activitytype__c = objActivity.Id;
         objMarketingact.Starts_date__c = system.today();
         objMarketingact.Ends_date__c= system.today();
         insert objMarketingact;
        
        ERP_logfile__c err = new ERP_logfile__c();
        err.Imported__c = true;
        err.Import_message__c = 'Good';
        err.Number_of_records__c = 10;
        insert err;
        
        ERP_sales_obj__c ess = new ERP_sales_obj__c();
        ess.Name = 'test';
        ess.Business_region__c = 'APAC';
        ess.Business_area__c = 'Prodcut';
        ess.sales_import_id__c = 'uftyft';
        ess.Sales_date__c = system.today();
        ess.Sales__c = 1000.00;
        ess.Sales_import_date__c = system.today();
        ess.ERP_logfile__c = err.Id;
        
        insert ess;
        
        socialmedia_settings__c ss = new socialmedia_settings__c();
        ss.Socialmedia_type__c = 'Facebook';
        ss.Import_rate__c = 'Day';
        ss.Watch_type__c = 'Visitor';
        ss.Chart__c = 'bar';
        insert ss;
        
        Social_media_data__c smd = new Social_media_data__c();        
        smd.Date__c = system.today();
        smd.Number_of_likes__c = 4;
        smd.Socialmedia_Settings__c = ss.Id; 
        smd.Name = 'test';              
        insert smd;
        
        PageReference testPage = new pagereference('/apex/ProjectPerformance');
        testPage.getParameters().put('id', 'prj.id');
        Test.setCurrentPage(testPage);
        
        ApexPages.currentPage().getParameters().put('planid', prj.id);  
        ProjectPerformanceController GPC = new ProjectPerformanceController();
        ProjectPerformanceController.GanttRow wrp=new ProjectPerformanceController.GanttRow();
           List<ERP_Settings__c> temp1=GPC.erpChartList;  
            List<CRM_Settings__c> temp2=GPC.crmChartList; 
         List<socialmedia_settings__c> temp3=GPC.mediaSettigs;
        GPC.gotoPlanPage();
        GPC.getjsString();
        GPC.gettaskstyleString();         
        GPC.getdataString();
        GPC.getFbData();
        GPC.showSelectedPlanTypes();
        GPC.getData();
        List<SelectOption> opl = GPC.PlanList;
        //GPC.gotoGanttPage();
        GPC.IsDeleted=true;
        //GPC.selStr='test';
    }
}