src/objects/Activitytype__c.object
<CustomObject>
    <fields>
        <fullName>Bar_color__c</fullName>
        <label>Bar color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F__c</fullName>
        <description>This should be a choice from Marketing activities field set name</description>
        <label>Fieldset</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <inlineHelpText>Give a url to a icon for the activity type this should be in size 24x24 px</inlineHelpText>
        <label>Url to icon</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity types</label>
    <nameField>
        <label>Activity type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActivitycontrollerTest.cls
/************************************************************
Class Name: ActivitycontrollerTest
Author: Nagaraju G         Last modified by:G Janardhanreddy 
Date  :  18/7/2014            Date:18/03/2015
**********©2013 Musqot marketing technology Pvt ltd **********/
@isTest(seeAllData=true)
public class ActivitycontrollerTest{
    static testMethod void myActivityTest(){         
    Activitytype__c objActivity = new Activitytype__c(); 
    objActivity.Name='test';
    objActivity.Icon__c='testicon';
    objActivity.Bar_color__c ='red';
    objActivity.F__c =Null;    
    System.assertEquals('test', objActivity.name);
    insert objActivity;
    
    ApexPages.currentPage().getParameters().put('id', objActivity.id);
    ApexPages.StandardController sc = new ApexPages.standardController(objActivity); 
    System.Dmlexception ex;
    test.startTest();
    Activitycontroller objact = new Activitycontroller(sc);
    ApexPages.Pagereference result = objact .save();
    List<SelectOption>  temp1=objact.Fieldsetlist;
    objact.selectActivityImage();
    objact.closePopUp();
    objact.showUplodePopUp();
    objact.showActivityImagPopUp();
    objact.getActivityImages();
    try{
    objact.Save();
    objact.Cancel();
    objact.createStaticResource(); 
    }catch(DmlException e) {
            ex = e;}
     objact.createStaticResource(); 
    }
    static testMethod void myActivityTest1(){         
    Activitytype__c objActivity = new Activitytype__c(); 
    objActivity.Name='test';
    objActivity.Icon__c='testicon';
    objActivity.Bar_color__c ='red';
    objActivity.F__c =Null;    
    System.assertEquals('test', objActivity.name);
    insert objActivity;
    
    ApexPages.currentPage().getParameters().put('id', objActivity.id);
    ApexPages.StandardController sc = new ApexPages.standardController(objActivity); 
    System.Dmlexception ex;
    test.startTest();
    Activitycontroller objact = new Activitycontroller(sc);
    ApexPages.Pagereference result = objact .save();
    List<SelectOption>  temp1=objact.Fieldsetlist;
    objact.fileName=''; 
    objact.fileImage=blob.valueof('sample');
    objact.filesize=1048577;   
    objact.selectActivityImage();
    objact.closePopUp();
    objact.showUplodePopUp();
    objact.showActivityImagPopUp();   
    try{
    objact.Save();
    objact.Cancel();    
    }catch(DmlException e){}
    objact.createStaticResource(); 
   }
  static testMethod void activityfile(){
    Activitytype__c objActivity = new Activitytype__c(); 
    objActivity.Name='test';
    objActivity.Icon__c='testicon';
    objActivity.Bar_color__c ='red';
    objActivity.F__c =Null;    
    System.assertEquals('test', objActivity.name);
    insert objActivity;
    
    ApexPages.currentPage().getParameters().put('id', objActivity.id);
    ApexPages.StandardController sc = new ApexPages.standardController(objActivity);
	Activitycontroller actfile = new Activitycontroller(sc);
    actfile.filesize=1048555;
    actfile.fileName=null;
    actfile.fileName='test';
    actfile.poptext='pop';
    actfile.createStaticResource();
    }  
  }