src/objects/Allocation_amount__c.object
<CustomObject>
    <fields>
        <fullName>Allocated__c</fullName>
        <label>Requested amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved_Amount__c</fullName>
        <label>Approved amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Costcentre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost center</label>
        <referenceTo>Costcentre__c</referenceTo>
        <relationshipLabel>Allocation Amounts</relationshipLabel>
        <relationshipName>Allocation_amounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Musqot_fiscal_year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Musqot fiscal year</label>
        <referenceTo>Musqot_fiscal_year__c</referenceTo>
        <relationshipLabel>Allocation amounts</relationshipLabel>
        <relationshipName>Allocation_amounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation amount</label>
    <nameField>
        <label>Allocation Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Costcentre__c.object
<CustomObject>
    <customHelpPage>Costcentershelppage</customHelpPage>
    <fields>
        <fullName>Fiscal_year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DONT USE THIS</description>
        <label>Fiscal year</label>
        <referenceTo>Musqot_fiscal_year__c</referenceTo>
        <relationshipLabel>Cost centers</relationshipLabel>
        <relationshipName>Cost_centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Headline__c</fullName>
        <label>Headline</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overveiw__c</fullName>
        <label>Overveiw</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not started</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>cc_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DONT USE THIS</description>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Costcentres</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cost center</label>
    <nameField>
        <label>Cost centre name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Members__c.object
<CustomObject>
    <description>Member in a project/sub project</description>
    <fields>
        <fullName>Cost_center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost center</label>
        <referenceTo>Costcentre__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role in Project</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Email__c</fullName>
        <label>Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member set name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_fiscal_year__c.object
<CustomObject>
    <fields>
        <fullName>End_date__c</fullName>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Musqot fiscal year</label>
    <nameField>
        <label>Fiscal year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Musqot fiscal year</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/costcenterdetailclsTest.cls
/*****************************************************************
Class Name: costcenterdetailclsTest
Author:Chaithanya daggumati                   Last modified by:Chaithanya daggumati
Date :14/12/2015                   			  Date :14/12/2015                    
********©2013 Musqot marketing technology Pvt ltd *****************/
@isTest
public class costcenterdetailclsTest {
    static testMethod void CostcenterDetailTestMethod(){
        Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey    = 'America/Los_Angeles');
           insert u2;
        Musqot_fiscal_year__c objMusqotfiscalyea=new Musqot_fiscal_year__c();
        objMusqotfiscalyea.name ='musqot';
        objMusqotfiscalyea.Start_date__c= System.now().date();
        objMusqotfiscalyea.End_date__c =System.now().date();
        System.assertEquals('musqot', objMusqotfiscalyea.name);
        insert objMusqotfiscalyea;
        
        Costcentre__c objCC=new Costcentre__c(); 
        objCC.Name='CCRequest';
        objCC.OwnerId=u2.id;
        objCC.Headline__c='musqotCostcenter';
        objCC.Fiscal_year__c=objMusqotfiscalyea.id;
        objCC.Overveiw__c='presentation';
        objCC.Status__c='Active';
        objCC.cc_Owner__c=u2.id;
        insert objCC;
        System.assertEquals('CCRequest', objCC.name);
        
        Members__c objmember=new Members__c();
        objmember.ProjUsers__c=UserInfo.getUserId();
        objmember.Role__c='Member';
        objmember.Cost_center__c=objCC.id;
        objmember.User_Email__c ='standarduser1@test.com';
        System.assertEquals('Member', objmember.Role__c);
        insert objmember; 
        
        Allocation_amount__c objAllocate=new Allocation_amount__c();
        objAllocate.Name='finance';
        objAllocate.Approved_Amount__c=4444;
        objAllocate.Allocated__c=220;
        objAllocate.Costcentre__c=objCC.id;
        insert objAllocate;
        System.assertEquals('finance', objAllocate.Name);
        
        Task ObTask = new Task();
        ObTask .Task_name__c = 'testname';
        ObTask .ownerId = u2.Id; 
        ObTask .WhatId=objCC.id; 
        ObTask .Subject = 'Run Test Trigger';
        ObTask .Status = 'Not Started';
        ObTask .Priority = 'Normal';
        insert ObTask ;
        System.assertEquals('testname', ObTask.Task_name__c);
        
        Test.startTest();
        PageReference pageRef = Page.Costcenterdetail;
        Test.setCurrentPage(pageRef);  
        ApexPages.currentPage().getParameters().put('cosid',objCC.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objCC);
        costcenterdetailcls ccdetails = new costcenterdetailcls(sc);
        MusqotUtility.innerClass musIncls = MusqotUtility.securitySettingcoscenter(objCC.Id);
        ccdetails.costcenteredit();
        ccdetails.costcenteroverview();
        ccdetails.workRedirect();
        ccdetails.getGadgetHTMLContent();
        ccdetails.newtask();
        ccdetails.gettaskrecs();
        ccdetails.gotoTaskEdit();
        ccdetails.newmember();
        ccdetails.getmembers();
        ccdetails.gotoMemberEdit();
        ccdetails.getTabInFocus();
        ccdetails.setTabInFocus('String');
        Test.stopTest();
    }
}