src/objects/Allocation_amount__c.object
<CustomObject>
    <fields>
        <fullName>Approvedate__c</fullName>
        <label>Approve date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>FiscalYear</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Musqot_fiscal_year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Musqot fiscal year</label>
        <referenceTo>Musqot_fiscal_year__c</referenceTo>
        <relationshipLabel>Allocation amounts</relationshipLabel>
        <relationshipName>Allocation_amounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Allocation_amounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Allocation_amounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation amount</label>
    <nameField>
        <label>Allocation Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_fiscal_year__c.object
<CustomObject>
    <label>Musqot fiscal year</label>
    <nameField>
        <label>Fiscal year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Musqot fiscal year</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_type__c</fullName>
        <label>User type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal user</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communities user</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FRMarketingPopupCtrlTest.cls
/*****************************************************
Class Name: FRMarketingPopupCtrlTest
Author:Nagaraju G     Last modified by:G Janarhanreddy
Date: 24/7/2014        Date:19/03/2015
********©2013 Musqot marketing technology Pvt ltd ****/
@isTest(seeAllData=true)
public class FRMarketingPopupCtrlTest{
    static testMethod void FRPlanPopup(){
        Profile p = [select id from profile where name='System Administrator']; 
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id, 
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ;  
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c); 
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
        prj.ownerid =plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
                
         Marketing_activity__c objMarketingact=new Marketing_activity__c();
         objMarketingact.Name='test';
         objMarketingact.Description__c='tdescriptionest';
         objMarketingact.Ends_date__c=system.today();
         objMarketingact.Starts_date__c=system.today();
         objMarketingact.Status__c='completed';
         objMarketingact.musqot__ERP__c='testERP';
         objMarketingact.musqot__Social_media__c='testSocial';
         objMarketingact.musqot__CRM__c='testCRM';         
         insert objMarketingact;
         System.assertEquals('test', objMarketingact.name);
        
        Musqot_fiscal_year__c fiscalYearObj=new Musqot_fiscal_year__c();
        fiscalYearObj.name='2015';
        fiscalYearObj.musqot__Start_date__c=system.today();
        fiscalYearObj.musqot__End_date__c=system.today()+10;
        insert fiscalYearObj;
        
        Allocation_amount__c objallocamt = new Allocation_amount__c ();
        objallocamt .Approvedate__c= Date.Today(); 
        objallocamt .Name = 'Name';
        objallocamt .FiscalYear__c='november';       
        objallocamt.plan__c=prj.id;
        objallocamt.project__c=subPrj.id;
        objallocamt.Musqot_fiscal_year__c=fiscalYearObj.id;       
        System.assertEquals('Name', objallocamt .name);         
        insert objallocamt; 
        
        test.startTest();
        PageReference pageRef = Page.Fundrequestmarketing;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('mark', objMarketingact.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objMarketingact);        
        FRMarketingPopupCtrl objfrMarketing = new FRMarketingPopupCtrl(sc);
        FRMarketingPopupCtrl.Reciver OBre=new FRMarketingPopupCtrl.Reciver();    
        objfrMarketing .saveAmt();
        List<SelectOption>fiscalyeartemp =objfrMarketing.fisicalYearOptions;
        objfrMarketing.defaultFiscalYearId='jan';
        objfrMarketing.selfApp=true;
        objfrMarketing.ccApp=true;
        test.stopTest();        
    }
}