src/objects/Allocation_amount__c.object
<CustomObject>
    <fields>
        <fullName>Approvedate__c</fullName>
        <label>Approve date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Allocation_amounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation amount</label>
    <nameField>
        <label>Allocation Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FRmarketingTest.cls
/**************************************************************
Class Name: FRmarketingTest
Author:chaithanya daggumati     Last modified by:G Janarhanreddy
Date: 23/7/2014                  Date:19/03/2015
********©2013 Musqot marketing technology Pvt ltd *************/
@isTest
public class  FRmarketingTest{
    static testMethod void FRmarketing(){
        Subproject__c objsubproj = new Subproject__c ();
        objsubproj .Name = 'test';
        System.assertEquals('test', objsubproj .name);
        insert objsubproj;
        
        Allocation_amount__c objfrmarktng = new Allocation_amount__c ();
        objfrmarktng.Approvedate__c= Date.Today();
        System.assertEquals(Date.Today(), objfrmarktng.Approvedate__c);
        insert objfrmarktng;
        
        Marketing_activity__c ma = new Marketing_activity__c ();
        ma.Project__c = objsubproj.Id;
        ma.Name= 'Market';
        insert ma;
        
        ApexPages.currentPage().getParameters().put('mark', ma.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objfrmarktng);
        
        FRMarketingPopupCtrl FRM = new FRMarketingPopupCtrl(sc);    
        FRM.saveAmt();
        FRM.selfApp=true;
        FRM.ccApp=true;
    }
}