src/objects/Allocation_amount__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Amount__c</fullName>
        <label>Approved amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approvedate__c</fullName>
        <label>Approve date</label>
        <type>Date</type>
    </fields>
    <label>Allocation amount</label>
    <nameField>
        <label>Allocation Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Approval_ProcessTest.cls
/**********************************************************
Class Name: Approval_ProcessTest
Author: Nagaraju G        Last modified by:G Janardhanreddy 
Date  : 24/07/2014             Date:18/03/2015
***********©2013 Musqot marketing technology Pvt ltd ******/
@isTest(seeAllData=true)
public class Approval_ProcessTest{
    static testMethod void Approval_ProcessMethod(){
    Allocation_amount__c objAllocation=new Allocation_amount__c ();
    objAllocation.Name='testallocation';
    objAllocation.Approved_Amount__c=1000;
    objAllocation.Approvedate__c=System.today();
    System.assertEquals('testallocation', objAllocation.name);
    insert objAllocation;
   
}
}