src/objects/Allocation_amount__c.object
<CustomObject>
    <fields>
        <fullName>Allocated__c</fullName>
        <label>Requested amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Costcentre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost center</label>
        <referenceTo>Costcentre__c</referenceTo>
        <relationshipLabel>Allocation Amounts</relationshipLabel>
        <relationshipName>Allocation_amounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>To_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Allocation_amounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Allocation_amounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Allocation_amounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation amount</label>
    <nameField>
        <label>Allocation Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Costcentre__c.object
<CustomObject>
    <customHelpPage>Costcentershelppage</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not started</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cost center</label>
    <nameField>
        <label>Cost centre name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Members__c.object
<CustomObject>
    <description>Member in a project/sub project</description>
    <fields>
        <fullName>Marketingmebers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketingmebers</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role in Project</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member set name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MusqotUtilityTest.cls
/********************************************************
Class Name: MusqotUtiliyyTest
Author:Hussain           Last modified by:Raju GN
Date: 05/05/2015         Date:23/12/2015
********©2013 Musqot marketing technology Pvt ltd *******/
@isTest(seeAllData=true)
Public class MusqotUtilityTest{
    static testMethod void TestMusqotUtilityPlan(){
          Profile p=[SELECT Id ,Name From Profile WHERE name='System Administrator'];
          User u2 =new User( Alias = 'newUser1' ,
          Email ='newuser123@testorg.com',
          EmailEncodingKey = 'UTF-8',
          LastName = 'Testing',
          LanguageLocaleKey='en_US',
          LocaleSidKey='en_US', 
          UserName='newuser1234@testorg.com',
          ProfileId=p.Id,
          TimeZoneSidKey    = 'America/Los_Angeles');
          insert u2;  
          
          musqot__Costcentre__c objCC=new musqot__Costcentre__c(); 
          objCC.Name='test';
          objCC.musqot__cc_Owner__c=u2.id;
          objCC.musqot__Headline__c='musqotCostcenter';
          insert objCC;
          System.assertEquals('test', objCC.name);  
         
        Project__c project = new Project__c ();
        project.Name='ITC';             
        project.Starts_date__c= system.toDay();
        project.Ends_date__c = system.toDay().addDays(3);
        project.Status__c = 'In Progress'; 
        insert project;
        system.assertEquals('ITC',project.Name);        
        
        Members__c member = new Members__c();
        member.ProjMembers__c = project.Id;
        member.musqot__ProjUsers__c=u2.id;
        member.musqot__ProjMembers__c=project.id;
        member.Role__c = 'Owner';
        insert member;
        
        Allocation_amount__c allocAmount = new Allocation_amount__c();
        allocAmount.Allocated__c = 200.00;
        allocAmount.To_Plan__c = project.Id; 
        allocAmount.musqot__Costcentre__c= objCC.id;     
        insert allocAmount;
       
        musqot__Activity__c objAct=new musqot__Activity__c ();
        objAct.Name='test';
        objAct.musqot__Use_Allocation__c=true;
        objAct.musqot__Use_Forcasting__c=true;
        objAct.musqot__Use_milestones__c=true;
        insert objAct;
        
        musqot__Profilelist__c profileList=new musqot__Profilelist__c ();
        profileList.Name='System Administrator1';
        profileList.musqot__profilename__c='System Administrator';
        insert profileList;
        
        musqot__Permissionlist__c permisionCs=new musqot__Permissionlist__c();
        permisionCs.Name='Permissionlist1';
        permisionCs.musqot__Permissionlistname__c='Musqot admine';
        insert permisionCs;
        
        MusqotUtility.innerClass inr1 = new MusqotUtility.innerClass(true,true,true,true,true);
        MusqotUtility.securitySetting(project.Id);
        //MusqotUtility.getFieldMetaData();
        //MusqotUtility.unshift('test',10);
    }
     static testMethod void TestMusqotUtilityPlan1(){
         
          UserLicense UL=[SELECT Id, Name FROM UserLicense where Name='Salesforce'];
          Profile p=[SELECT Id ,Name From Profile WHERE UserLicenseId=:ul.id limit 1];
          User u2 =new User( Alias = 'newUser1' ,
          Email ='newuser123@testorg.com',
          EmailEncodingKey = 'UTF-8',
          LastName = 'Testing',
          LanguageLocaleKey='en_US',
          LocaleSidKey='en_US', 
          UserName='newuser1234@testorg.com',
          ProfileId=p.Id,
          TimeZoneSidKey = 'America/Los_Angeles');
          insert u2;  
           
         // PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Musqot_admin_sf' AND UserLicenseId=:UL.id];
        
          musqot__Costcentre__c objCC=new musqot__Costcentre__c(); 
          objCC.Name='test';
          objCC.musqot__cc_Owner__c=u2.id;
           objCC.musqot__Headline__c='musqotCostcenter';
          insert objCC;
          System.assertEquals('test', objCC.name);  
         
        Project__c project = new Project__c ();
        project.Name='ITC';             
        project.Starts_date__c= system.toDay();
        project.Ends_date__c = system.toDay().addDays(3);
        project.Status__c = 'In Progress'; 
        insert project;
        system.assertEquals('ITC',project.Name);        
        
        Subproject__c subProject = new Subproject__c();         
        subProject.Name='ITC Project';             
        subProject.Starts_date__c= system.toDay();
        subProject.Ends_date__c = system.toDay().addDays(3);
        subProject.Status__c = 'In Progress'; 
        subProject.Parent_project__c = project.Id; 
        insert subProject; 
        
        Allocation_amount__c allocAmount = new Allocation_amount__c();
        allocAmount.Allocated__c = 200.00;
        allocAmount.To_Plan__c = subProject.Parent_project__c ; 
        allocAmount.musqot__Costcentre__c= objCC.id;     
        insert allocAmount; 
         
        musqot__Permissionlist__c permisionCs=new musqot__Permissionlist__c();
        permisionCs.Name='Permissionlist1';
        permisionCs.musqot__Permissionlistname__c='Musqot admine';
        insert permisionCs;
        
        Members__c member = new Members__c();
        member.ProjMembers__c = project.Id;
        member.musqot__ProjUsers__c=u2.id;
        member.musqot__ProjMembers__c=project.id;
        member.Role__c = 'member';
        insert member;
        
        musqot__Activity__c m1 =new musqot__Activity__c();
        m1.musqot__keycode__c='212';
        m1.musqot__Use_Allocation__c=true;
        m1.musqot__Use_Budget__c=true;
        m1.musqot__Use_Finance1__c=true;
        m1.musqot__Use_Forcasting__c=true;
        m1.musqot__Use_milestones__c=true;
        m1.musqot__Use_Resource__c=true;
        insert m1;
        
        MusqotUtility.innerClass inr1 = new MusqotUtility.innerClass(true,true,true,true,true);
        MusqotUtility.securitySetting(project.Id); MusqotUtility.fileType('contentType');
        MusqotUtility.charOf(9);
        MusqotUtility.valueOf('ch');
        MusqotUtility.getEdition('edChar');
        MusqotUtility.unmask('c','c2');
        MusqotUtility.decryptKeycode('keycode');
        
        
    }
    static testMethod void TestMusqotUtilitySub(){
        
        Profile p=[SELECT Id From Profile WHERE Name='Musqot admin'];
          User u2 =new User( Alias = 'newUser1' ,
          Email ='newuser123@testorg.com',
          EmailEncodingKey = 'UTF-8',
          LastName = 'Testing',
          LanguageLocaleKey='en_US',
          LocaleSidKey='en_US', 
          UserName='newuser1234@testorg.com',
          ProfileId=p.Id,
          TimeZoneSidKey    = 'America/Los_Angeles');
          insert u2;  
          
        Project__c project = new Project__c ();
        project.Name='ITC';             
        project.Starts_date__c= system.toDay();
        project.Ends_date__c = system.toDay().addDays(3);
        project.Status__c = 'In Progress';         
        insert project;
        system.assertEquals('ITC',project.Name);        
        
        Subproject__c subProject = new Subproject__c();         
        subProject.Name='ITC Project';             
        subProject.Starts_date__c= system.toDay();
        subProject.Ends_date__c = system.toDay().addDays(3);
        subProject.Status__c = 'In Progress'; 
        subProject.Parent_project__c = project.Id; 
        insert subProject;   
        
        Members__c member = new Members__c();
        member.SubProjMembers__c = subProject.Id;
        member.ProjUsers__c = UserInfo.getUserId();
        member.Role__c = 'Member';
       // member.SubProjMembers__c = subproject.Id;
        insert member;
       
        musqot__Activity__c m1 =new musqot__Activity__c();
        m1.musqot__keycode__c='212';
        m1.musqot__Use_Allocation__c=true;
        m1.musqot__Use_Budget__c=true;
        m1.musqot__Use_Finance1__c=true;
        m1.musqot__Use_Forcasting__c=true;
        m1.musqot__Use_milestones__c=true;
        m1.musqot__Use_Resource__c=true;
        insert m1;
        
        musqot__Costcentre__c objCC=new musqot__Costcentre__c(); 
        objCC.Name='test';
        objCC.musqot__cc_Owner__c=u2.id;
        objCC.musqot__Headline__c='musqotCostcenter';
        insert objCC;
        System.assertEquals('test', objCC.name);  
        
        Allocation_amount__c allocAmount = new Allocation_amount__c();
        allocAmount.Allocated__c = 200.00;
        allocAmount.To_Plan__c = project.Id; 
        allocAmount.musqot__Costcentre__c= objCC.id;     
        insert allocAmount;      
        MusqotUtility.innerClass inr2 = new MusqotUtility.innerClass(true,true,true,true,true);
        MusqotUtility.securitySettingSub(subProject.Id);
        MusqotUtility.fileType('contentType');
        MusqotUtility.charOf(9);
        MusqotUtility.valueOf('ch');
        MusqotUtility.getEdition('edChar');
        MusqotUtility.unmask('c','c2');
        MusqotUtility.decryptKeycode('keycode');
      
    }
    static testMethod void TestMusqotUtilityMarketing(){
        Profile p=[SELECT Id From Profile WHERE Name='Musqot user'];
          User u2 =new User( Alias = 'newUser1' ,
          Email ='Musqotuser1@testorg.com',
          EmailEncodingKey = 'UTF-8',
          LastName = 'mus',
          LanguageLocaleKey='en_US',
          LocaleSidKey='en_US', 
          UserName='Musqotuser1@testorg.com',
          ProfileId=p.Id,
          TimeZoneSidKey    = 'America/Los_Angeles');
          insert u2; 
          
        Project__c project = new Project__c ();
        project.Name='ITC';             
        project.Starts_date__c= system.toDay();
        project.Ends_date__c = system.toDay().addDays(3);
        project.Status__c = 'In Progress';         
        insert project;
        system.assertEquals('ITC',project.Name);        
        
        Subproject__c subProject = new Subproject__c();         
        subProject.Name='ITC Project';             
        subProject.Starts_date__c= system.toDay();
        subProject.Ends_date__c = system.toDay().addDays(3);
        subProject.Status__c = 'In Progress'; 
        subProject.Parent_project__c = project.Id; 
        insert subProject;
        
        Marketing_activity__c marketingactivity =new Marketing_activity__c();
        marketingactivity.Name='hs mark';
        marketingactivity.Description__c='Nothing';
        marketingactivity.Status__c='completed';         
        marketingactivity.Starts_date__c = system.today();
        marketingactivity.Ends_date__c= system.today();
        marketingactivity.Plan__c= project.Id; 
        marketingactivity.Project__c = subproject.Id;  
        insert marketingactivity;       
        
        Members__c member = new Members__c();
        member.Marketingmebers__c = marketingactivity.Id;
        member.ProjUsers__c = UserInfo.getUserId();
        member.Role__c = 'Member';
       // member.SubProjMembers__c = subproject.Id;
        insert member;
        
        musqot__Costcentre__c objCC=new musqot__Costcentre__c(); 
        objCC.Name='ccbangalore';
        objCC.musqot__cc_Owner__c=u2.id;
        objCC.musqot__Headline__c='ccus';
        insert objCC;
        System.assertEquals('ccbangalore', objCC.name);
         
        Allocation_amount__c allocAmount = new Allocation_amount__c();
        allocAmount.Allocated__c = 200.00;
        allocAmount.To_Plan__c = project.Id;       
        insert allocAmount;
        
        musqot__Activity__c m1 =new musqot__Activity__c();
        m1.musqot__keycode__c='212';
        m1.musqot__Use_Allocation__c=true;
        m1.musqot__Use_Budget__c=true;
        m1.musqot__Use_Finance1__c=true;
        m1.musqot__Use_Forcasting__c=true;
        m1.musqot__Use_milestones__c=true;
        m1.musqot__Use_Resource__c=true;
        insert m1;
        MusqotUtility.innerClass inr3 = new MusqotUtility.innerClass(true,true,true,true,true);
        MusqotUtility.markertsecuritySetting(marketingactivity.Id);
        MusqotUtility.fileType('contentType');
        MusqotUtility.charOf(9);
        MusqotUtility.valueOf('ch');
        MusqotUtility.getEdition('edChar');
        MusqotUtility.unmask('c','c2');
        MusqotUtility.decryptKeycode('keycode');
        //MusqotUtility.unshift('c','k');
    } 
  static testMethod void TestMusqotUtilitycoscenter(){		
    	Profile p=[SELECT Id From Profile WHERE Name='Musqot user'];
          User u2 =new User( Alias = 'newUser1' ,Email ='Musqotuser1@testorg.com',EmailEncodingKey = 'UTF-8',
          LastName = 'mus',LanguageLocaleKey='en_US',LocaleSidKey='en_US', UserName='Musqotuser1@testorg.com',
          ProfileId=p.Id,TimeZoneSidKey= 'America/Los_Angeles');
          insert u2; 
      	musqot__Costcentre__c objCC=new musqot__Costcentre__c(); 
        objCC.Name='ccmusqot';
        objCC.musqot__cc_Owner__c=u2.id;
        objCC.musqot__Headline__c='ccus';
        insert objCC;
        System.assertEquals('ccmusqot', objCC.name);
         
        Allocation_amount__c allocAmount = new Allocation_amount__c();
        allocAmount.Allocated__c = 200.00;
        allocAmount.Costcentre__c = objCC.Id;       
        insert allocAmount;
        System.assertEquals(200.00, allocAmount.Allocated__c);
        MusqotUtility.innerClass inr4 = new MusqotUtility.innerClass(true,true,true,true,true);
        MusqotUtility.securitySettingcoscenter(objCC.Id);
  	}
}