src/objects/Allocation_resources__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Allocation resources</relationshipLabel>
        <relationshipName>Allocation_resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipLabel>Allocation resources</relationshipLabel>
        <relationshipName>Allocation_resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation resources</label>
    <nameField>
        <label>Allocation resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Hoursmarketingpopupcls.cls
/**************************************************************
Class Name: Hoursmarketingpopupcls 
Author:chaithanya daggumati    Last modified by:Raju GN
Date: 09/04/2015                Date:16/10/2015
Dec:Adding fiscal year functionality
********©2013 Musqot marketing technology Pvt ltd *************/

public with sharing class Hoursmarketingpopupcls {
    public Allocation_resources__c hrs{get;set;}
    private ApexPages.standardController controller;
    public Marketing_activity__c market{get;set;}
    private List<Reciver> rev;
    String mark;
    public integer markStartYear;
    public integer markEndDate;
    public list<integer>markSpanYears=new list<integer>();
    public string fisYearCompare;
    public string defaultFiscalYearId{get;set;} 
    public Hoursmarketingpopupcls(ApexPages.StandardController controller) { 
        hrs = new Allocation_resources__c ();     
        Mark = ApexPages.currentPage().getParameters().get('mark');
        try {        
            market= [select ID, Name, Project__c, Project__r.Name,Project__r.Starts_date__c,Project__r.Ends_date__c from musqot__Marketing_activity__c where Id =:Mark];
            //----Raju To get Parent Plan Span Years---
            markStartYear=market.Project__r.Starts_date__c.year();
            markEndDate=market.Project__r.Ends_date__c.year();
            for(integer i=markStartYear;i<=markEndDate;i++){
               integer currentYear=system.today().year();
               if(i>=currentYear){
                 markSpanYears.add(i);
               }
            }  
            //----------End----  
        }
        catch(exception e){}                         
    }
    public void saveHrs()
    {
        if (Allocation_resources__c.sObjectType.getDescribe().isCreateable())
        {
            hrs.project__c = market.Project__c ;
            hrs.To_Marketing_activity__c = Mark;
            hrs.name = market.name;
            insert hrs;
        }
    }
    public class Reciver {
        //public string Sendto{get;set;}
    }
    //---Raju prepared fisical year dropdowen --- 
    
    public List<SelectOption> fisicalYearOptions
    {
        get
        {
            list<FiscalYearSettings>queryResult= [SELECT Id, Name 
                                                  FROM FiscalYearSettings order by SystemModstamp limit 200];
            
            fisicalYearOptions= new List<SelectOption>(); 
            for(FiscalYearSettings obj:queryResult)
            {  
                fisYearCompare=obj.Name;
                fisYearCompare=fisYearCompare.substring(0,4);
                if(fisYearCompare==string.valueof(system.now().year())){
                    defaultFiscalYearId=obj.Name;
                }  
                for(integer i:markSpanYears){
                    if(fisYearCompare==string.valueof(i))
                        fisicalYearOptions.add(new SelectOption(obj.id,obj.Name));
                }
            }
            return fisicalYearOptions;
        }
        set;
    }
    //----End----
}