src/objects/Budget__c.object
<CustomObject>
    <description>Budget for fiscal year</description>
    <fields>
        <fullName>Approved_date__c</fullName>
        <label>Approved date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Project budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_h__c</fullName>
        <label>Budget (h)</label>
        <precision>11</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>subproject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>user__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved by</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budget</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_type__c</fullName>
        <label>User type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal user</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communities user</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BudgetLockclassTest.cls
/*************************************************************
Class Name: BudgetLockclassTest
Author:Nagaraju G            Last modified by:G Janardhanreddy
Date: 23/7/2014              Date:18/03/2015
************©2013 Musqot marketing technology Pvt ltd ********/
@isTest (SeeAllData = true)
private class BudgetLockclassTest{
    static testMethod void BudgetLockclassTestMethod(){
        test.startTest();
        Profile p = [select id from profile where name='System Administrator'];
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
        emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
        localesidkey='en_US', profileid = p.Id, 
        timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);        
        Project__c objproject = new Project__c ();
        objproject.Name='test';
        objproject.Starts_date__c= System.now().date();
        objproject.Ends_date__c= System.now().date();
        objproject.ownerid =plm.userid__c;
        insert objproject;
        System.assertEquals('test', objproject.name);
        
        Subproject__c objsp = new Subproject__c ();
        objsp.name = 'testname';
        objsp.Description__c = 'sampdesc';
        objsp.Starts_date__c = date.today();
        objsp.Ends_date__c = date.today();
        objsp.Status__c = 'Notstarted';
        insert objsp ; 
        System.assertEquals('testname', objsp.name);
        
        Budget__c  objbudget1=new Budget__c ();
        objbudget1.Name = 'test1';
        objbudget1.Approved_date__c = System.today()+2;
        objbudget1.user__c=UserInfo.getUserId();
        objbudget1.musqot__Approved__c=true;
        objbudget1.musqot__Project__c=objproject.id;
        objbudget1.musqot__subproject__c=objsp.id;
        objbudget1	.Budget_h__c=10;
        objbudget1.Description__c='test123';
        objbudget1.Budget__c=5;
        insert objbudget1;
        update objbudget1;
        System.assertEquals('test1', objbudget1.name);
        
        Budget__c  objbudget2=new Budget__c ();
        objbudget1.Name = 'test1';
        objbudget1.Approved_date__c = System.today();
        objbudget1.user__c=UserInfo.getUserId();
        objbudget1.musqot__Approved__c=false;
        objbudget1.musqot__Project__c=objproject.id;
        objbudget1.musqot__subproject__c=objsp.id;
        objbudget1.Budget_h__c=10;
        objbudget1.Description__c='test123';
        objbudget1.Budget__c=5;
        insert objbudget2;
        update objbudget2;
        System.assertEquals('test1', objbudget1.name);
                               
        ApexPages.currentPage().getParameters().put('planId', objproject.id);    
        ApexPages.StandardController sc = new ApexPages.standardController(objproject); 
        BudgetLockclass objbudg = new BudgetLockclass(sc);
        List<Budget__c> budgloop = new List<Budget__c>(); 
        List<SelectOption> fisctemp=objbudg.fisicalYearOptions;
        Project__c temp1=objbudg.plan;
        Budget__c temp2=objbudg.plansum2;
        Budget__c temp3=objbudg.plansum;
        objbudg.closeBudget();
        objbudg.totbudget_h=0.1;
        objbudg.totbudget=10;
        test.stopTest();       
                 }
    Static testMethod void BudgetLockclassTestMethod1(){
        Test.startTest();
        Profile p = [select id from profile where name='System Administrator'];
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
        emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
        localesidkey='en_US', profileid = p.Id, 
        timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c); 
                
        Project__c objproject = new Project__c ();
        objproject.Name='test';
        objproject.Starts_date__c= System.now().date();
        objproject.Ends_date__c= System.now().date();
        objproject.ownerid =plm.userid__c;
        insert objproject;
        System.assertEquals('test', objproject.name);
        
        Subproject__c objsp = new Subproject__c ();
        objsp.name = 'testname';
        objsp.Description__c = 'sampdesc';
        objsp.Starts_date__c = date.today();
        objsp.Ends_date__c = date.today();
        objsp.Status__c = 'Notstarted';
        insert objsp ; 
        System.assertEquals('testname', objsp.name);
        
        Budget__c  objbudget1=new Budget__c ();
        objbudget1.Name = 'test1';
        objbudget1.Approved_date__c = System.today();
        objbudget1.user__c=UserInfo.getUserId();
        objbudget1.musqot__Approved__c=false;
        objbudget1.musqot__Project__c=objproject.id;
        objbudget1.musqot__subproject__c=objsp.id;
        objbudget1.Budget_h__c=10;
        objbudget1.Description__c='test123';
        objbudget1.Budget__c=5;
        insert objbudget1;
        update objbudget1;
        System.assertEquals('test1', objbudget1.name);
        
        Budget__c  objbudget2=new Budget__c ();
        objbudget1.Name = 'test1';
        objbudget1.Approved_date__c = System.today()+2;
        objbudget1.user__c=UserInfo.getUserId();
        objbudget1.musqot__Approved__c=true;
        objbudget1.musqot__Project__c=objproject.id;
        objbudget1.musqot__subproject__c=objsp.id;
        objbudget1.Budget_h__c=10;
        objbudget1.Description__c='test123';
        objbudget1.Budget__c=5;
        insert objbudget2;
        try{
        
       Budget__c   planBudget=[SELECT Id, musqot__Approved__c, musqot__Approved_date__c, musqot__user__c, musqot__subproject__c, musqot__Project__c,musqot__Budget__c FROM musqot__Budget__c where musqot__Project__c =:objproject.id];
        
    planBudget.musqot__Approved__c=true;
                planBudget.musqot__Approved_date__c=system.toDay();
                planBudget.user__c  = UserInfo.getUserId();
        update planBudget;
        System.assertEquals('test1', objbudget1.name);
               }catch(exception e){}     
        ApexPages.currentPage().getParameters().put('planId', objproject.id);    
        ApexPages.StandardController sc = new ApexPages.standardController(objproject); 
        BudgetLockclass objbudg = new BudgetLockclass(sc);
        List<Budget__c> budgloop = new List<Budget__c>(); 
        ApexPages.currentPage().getParameters().put('id',objbudget1.id);
        for(Budget__c budg : budgloop){
            budg.musqot__Approved__c=true;
            budg.musqot__Approved_date__c=system.toDay();
            budg.user__c  = UserInfo.getUserId(); 
            upsert budg;     
        Project__c temp1=objbudg.plan;
        Budget__c temp2=objbudg.plansum2;
        Budget__c temp3=objbudg.plansum;
        objbudg.closeBudget();
        objbudg.totbudget_h=0.1;
        objbudg.totbudget=10;
        test.stopTest();       
                 }
            }
       }