src/objects/Budget__c.object
<CustomObject>
    <description>Budget for fiscal year</description>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Budget is approved and can be changed</description>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approved_date__c</fullName>
        <label>Approved date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Project budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>subproject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>user__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved by</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budget</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Budgetpageclass.cls
/***********************************************************
Class Name: Budgetpageclass
Author:G Janardhanreddy    Last modified by:G Janardhanreddy 
Date: 21/7/2014             Date:18/03/2015
********©2013 Musqot marketing technology Pvt ltd **********/
public with sharing class Budgetpageclass{
    Public Budget__c bud{get;set;}
    public String planId{get;set;}
    public Budgetpageclass(ApexPages.StandardController controller) {
        bud=[SELECT id,Name,Approved__c,user__c,Approved_date__c,Description__c,Project__c,Budget__c,subproject__c FROM Budget__c LIMIT 1];
    }
        Public PageReference Editpage()//redirect to Budgetpage  page
    {
        
        PageReference pg=new PageReference ('/apex/Budgetpage?id='+EncodingUtil.urlEncode(bud.id,'UTF-8'));
        return pg;
    }
    /**************************************
	Save():redirect to ProjectDetails  page
	***************************************/
    Public PageReference Save()
    {
        PageReference pg;
        String tabId = System.currentPageReference().getParameters().get('tabId');
        string pageRef='/apex/ProjectDetails?id='+EncodingUtil.urlEncode(bud.id,'UTF-8')+'&tab='+EncodingUtil.urlEncode('bud','UTF-8');
        pg=new Pagereference (pageRef);
        // PageReference pg=new PageReference ('/apex/Budgetpage?id='+EncodingUtil.urlEncode(bud.id,'UTF-8'));
        return pg;
    }
    /************************************
	Cancel():redirect to Budgetpage  page
	************************************/
    Public PageReference Cancel()
    {
        PageReference pg=new PageReference ('/apex/Budgetpage?id='+EncodingUtil.urlEncode(bud.id,'UTF-8'));
        return pg;
    }
}