src/objects/Costcentre__c.object
<CustomObject>
    <customHelpPage>Costcentershelppage</customHelpPage>
    <fields>
        <fullName>CRM__c</fullName>
        <label>Performance CRM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ERP__c</fullName>
        <label>Performance ERP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Social_media__c</fullName>
        <label>Performance Social media</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusImage__c</fullName>
        <formula>CASE(Status__c, &apos;Not started&apos;, IMAGE(&apos;/resource/1433929854000/musqot__Planned&apos;,TEXT(Status__c),16,16), &apos;Active&apos;, IMAGE(&apos;/resource/1433930034000/musqot__Active&apos;,TEXT(Status__c),16,16),&apos;Closed&apos;,IMAGE(&apos;/resource/1433930023000/musqot__Deferred&apos;,TEXT(Status__c),16,16),  IMAGE(&apos;/resource/1446332034000/musqot__StatusOther&apos;,TEXT(Status__c),16,16))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not started</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>cc_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DONT USE THIS</description>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Costcentres</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cost center</label>
    <nameField>
        <label>Cost centre name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CRM_settings__c.object
<CustomObject>
    <fields>
        <fullName>CRM_performance_type__c</fullName>
        <label>CRM performance type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance, general</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Performance, project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance, marketing activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milestone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance, costcenter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRM settings</label>
    <nameField>
        <label>Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ERP_Settings__c.object
<CustomObject>
    <fields>
        <fullName>ERP_performance_type__c</fullName>
        <label>ERP performance type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Performance, general</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Performance, project</fullName>
            </value>
            <value>
                <fullName>Performance, marketing activity</fullName>
            </value>
            <value>
                <fullName>Milestone</fullName>
            </value>
            <value>
                <fullName>Performance, costcenter</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>ERP Settings</label>
    <nameField>
        <label>Settings name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/socialmedia_settings__c.object
<CustomObject>
    <description>The Name will show-up in the Performance Gantt view.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Performance, general</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Performance, project</fullName>
            </value>
            <value>
                <fullName>Performance, marketing activity</fullName>
            </value>
            <value>
                <fullName>Milestone</fullName>
            </value>
            <value>
                <fullName>Performance, costcenter</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Socialmedia Settings</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Socialmedia Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/costcentereditcls.cls
/*****************************************************************
Class Name: costcentereditcls
Author:Chaithanya daggumati                   Last modified by:Chaithanya daggumati
Date :24/11/2015                           	  Date :24/11/2015                    
********©2013 Musqot marketing technology Pvt ltd *****************/
public with sharing class costcentereditcls {
    public List<Costcentre__c> costcent{get;set;}
    Public String costid;
	public List<socialmedia_settings__c> SocialFilter_Temp = new List<socialmedia_settings__c>();
    public List<ERP_Settings__c> ERPFilter_Temp = new List<ERP_Settings__c>();
    public List<CRM_Settings__c> CRMFilter_Temp = new List<CRM_Settings__c>();    
    public costcentereditcls(ApexPages.StandardController controller) {
        costcent = new  List<Costcentre__c>();
        costid=ApexPages.currentPage().getParameters().get('cosid');
        costcent=[SELECT Id, Name,Status__c,StatusImage__c,CRM__c,ERP__c,Social_media__c, 
                       cc_Owner__c,Description__c FROM Costcentre__c WHERE Id=:costid LIMIT 1];
            
    }    
    /******************************************************************
     SocialFilter(): insert the social performance 
    ********************************************************************/
    public List<SelectOption> SocialFilter{
        get
        {
            SocialFilter_Temp = [Select u.Name, u.Id From socialmedia_settings__c u where type__c='Performance, costcenter' limit 250];
            SocialFilter= new List<SelectOption>(); 
            for(Socialmedia_settings__c objSocialFilter: SocialFilter_Temp )
            {
                SocialFilter.add(new SelectOption(objSocialFilter.Id, objSocialFilter.Name));
            }  
              
            return SocialFilter;
        }
        set;
    }
     public String[] SocialItems { 
     get {
        String[] selected = new List<String>();
        List<SelectOption> sos = this.SocialFilter;
        for(SelectOption s : sos) {
        if (this.costcent[0].Social_media__c!=null && this.costcent[0].Social_media__c.contains(s.getValue()))
           selected.add(s.getValue());
        }
        return selected;
     }public set {
        String selectedConcat = '';
        for(String s : value) {
         if (selectedConcat == '') 
           selectedConcat += s;
         else selectedConcat += ';' + s;
        }
        costcent[0].Social_media__c= selectedConcat;
     }
   } 

    /******************************************************************
     ERPFilter(): insert the erp settings
    ********************************************************************/
    public List<SelectOption> ERPFilter{
        get
        {
            ERPFilter_Temp = [Select u.Name, u.Id From ERP_Settings__c u where ERP_Performance_type__c='Performance, costcenter' limit 250];
            ERPFilter= new List<SelectOption>(); 
            for(ERP_Settings__c objERPFilter: ERPFilter_Temp )
            {
                ERPFilter.add(new SelectOption(objERPFilter.Id, objERPFilter.Name));
            } 
           
            return ERPFilter;
        }
        set;
    }
     public String[] ERPItems { 
     get {
        String[] selected = new List<String>();
        List<SelectOption> sos = this.ERPFilter;
        for(SelectOption s : sos) {
        if (this.costcent[0].ERP__c!=null && this.costcent[0].ERP__c.contains(s.getValue()))
           selected.add(s.getValue());
        }
        return selected;
     }public set {
        String selectedConcat = '';
        for(String s : value) {
         if (selectedConcat == '') 
           selectedConcat += s;
         else selectedConcat += ';' + s;
        }
        costcent[0].ERP__c= selectedConcat;
     }
   } 

    /******************************************************************
     CRMFilter(): insert the crm settings 
    ********************************************************************/
    public List<SelectOption> CRMFilter{
        get
        {
            CRMFilter_Temp = [Select u.Name, u.Id From CRM_Settings__c u where CRM_Performance_type__c='Performance, costcenter' limit 250];
            CRMFilter= new List<SelectOption>(); 
            for(CRM_Settings__c objCRMFilter: CRMFilter_Temp )
            {
                CRMFilter.add(new SelectOption(objCRMFilter.Id, objCRMFilter.Name));
            }  
          
            return CRMFilter;
        }
        set;
    }
    public String[] CRMItems { 
     get {
        String[] selected = new List<String>();
        List<SelectOption> sos = this.CRMFilter;
        for(SelectOption s : sos) {
        if (this.costcent[0].CRM__c!=null && this.costcent[0].CRM__c.contains(s.getValue()))
           selected.add(s.getValue());
        }
        return selected;
     }public set {
        String selectedConcat = '';
        for(String s : value) {
         if (selectedConcat == '') 
           selectedConcat += s;
         else selectedConcat += ';' + s;
        }
        costcent[0].CRM__c= selectedConcat;
     }
   }
   /**************************************************************
    updcc(): update the paln and redirects to ProjectDetails page
    ***************************************************************/
    public PageReference updcc(){       
        if(Costcentre__c.sObjectType.getDescribe().isUpdateable()){
            update costcent;
        }        
        Pagereference PR;
        PR = new Pagereference('/apex/Costcenterdetail?id='+EncodingUtil.urlEncode(costid,'UTF-8'));                  
        return PR ;             
    }
    /*****************************************
    cancel(): redirects to ProjectDetails page  
    ******************************************/
    public PageReference cancel(){
        Pagereference PR;
        PR = new Pagereference('/apex/Costcenterdetail?id='+EncodingUtil.urlEncode(costid,'UTF-8'));                  
        return PR ;
    }
}