src/objects/Costcentre__c.object
<CustomObject>
    <customHelpPage>Costcentershelppage</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Headline__c</fullName>
        <label>Headline</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overveiw__c</fullName>
        <label>Overveiw</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not started</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cost center</label>
    <nameField>
        <label>Cost centre name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/costcenteroverviewclsTest.cls
/*****************************************************************
Class Name: costcenteroverviewclsTest
Author:Chaithanya daggumati                   Last modified by:Chaithanya daggumati
Date :15/12/2015                           	  Date :15/12/2015                    
********©2013 Musqot marketing technology Pvt ltd *****************/
@isTest
public class costcenteroverviewclsTest {
    static testMethod void CostcenteroverviewMethod(){
        Costcentre__c objCC=new Costcentre__c(); 
        objCC.Name='CCRequest';
        objCC.Headline__c='musqotCostcenter';
        objCC.Overveiw__c='presentation';
        objCC.Status__c='Active';
        objCC.Description__c='this is cc description';        
        insert objCC;
        System.assertEquals('CCRequest', objCC.name);
        
        Test.startTest();
        objCC.Name ='CCMusqot';  
        update objCC;
        PageReference pageRef = Page.costcenteredit;
        Test.setCurrentPage(pageRef);          
        ApexPages.StandardController sc = new ApexPages.standardController(objCC);
        ApexPages.currentPage().getParameters().put('cosid',objCC.id);
        costcenteroverviewcls ccoverview = new costcenteroverviewcls(sc);
        ccoverview.Save();
        ccoverview.cancel();
    }
}