src/objects/CRM_data__c.object
<CustomObject>
    <fields>
        <fullName>Business_area__c</fullName>
        <label>Campaign</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_region__c</fullName>
        <label>Lead source</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_Leads__c</fullName>
        <label>No Leads</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Opportunities__c</fullName>
        <label>No Opportunities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value_Deals__c</fullName>
        <label>Amount Wins</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_Opportunities__c</fullName>
        <label>Amount Opportunities</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_w_Opportunities__c</fullName>
        <label>Amount (weighted) Opportunities</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CRM data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CRM_settings__c.object
<CustomObject>
    <fields>
        <fullName>CRM_performance_type__c</fullName>
        <label>CRM performance type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance, general</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Performance, project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance, marketing activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milestone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance, costcenter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expression_business_area__c</fullName>
        <inlineHelpText>Here you can enter which campaign to be included for the selected milestone, one row for each campaign</inlineHelpText>
        <label>Campaign</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expression_business_region__c</fullName>
        <inlineHelpText>Here you can enter which lead source to be included for the selected milestone, one row for each source</inlineHelpText>
        <label>Lead Source</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Watch_type__c</fullName>
        <inlineHelpText>For milestone you can only choice one option</inlineHelpText>
        <label>Watch type</label>
        <picklist>
            <picklistValues>
                <fullName>No Leads</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Wins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount (weighted) Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount Wins</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>CRM settings</label>
    <nameField>
        <label>Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipLabel>Milestones (Marketing activity)</relationshipLabel>
        <relationshipName>Milestones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone_type__c</fullName>
        <label>Milestone type</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reach on time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reach delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not reach</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_CRM_settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target CRM settings</label>
        <referenceTo>CRM_settings__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_number__c</fullName>
        <label>Target_number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_number_outcome__c</fullName>
        <description>This feild will be update by trigger in ERP, CRM and Social media</description>
        <label>Target number outcome</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Targetdate__c</fullName>
        <label>Target date</label>
        <type>Date</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMMilestoneUpdateScheduler.cls
/*******************************************************
Class Name: CRMMilestoneUpdateScheduler
Author: Narendra K Jha        Last modified by: Narendra K Jha
Date: Oct 19, 2015            Date: Oct 21, 2015
********©2015 Musqot marketing technology Pvt ltd *******/
global class CRMMilestoneUpdateScheduler Implements Schedulable {
   	public List<Milestone__c > milestoneList;
   	public List<Milestone__c > updateMilestoneList=new List<Milestone__c>(); 
   	public String businessRegion;
   	public String businessArea;
   	public Date today=system.toDay();
   	public List<String> businessRegionList = new List<String> ();
   	public List<String> businessAreaList = new List<String> ();
    public List<String> ebusinessRegionList = new List<String> ();
    public List<String> ebusinessAreaList = new List<String> ();
   	public List<musqot__CRM_data__c> crmDataList = new List<musqot__CRM_data__c>();
    public date startDate = system.today();
    public date endDate;

    global void execute(SchedulableContext sc) {
        	updateMilestoneList=new List<Milestone__c >();
            milestoneList = [SELECT Id, Plan__c, Project__c, Marketing_activity__c,
                                   Plan__r.Starts_date__c, Project__r.Starts_date__c, Marketing_activity__r.Starts_date__c,
                                   Plan__r.Ends_date__c, Project__r.Ends_date__c, Marketing_activity__r.Ends_date__c,
                                   Status__c, Targetdate__c, Target_number__c, Target_number_outcome__c,
                                   Target_CRM_settings__c, Target_CRM_settings__r.Watch_type__c,                   
                                   Target_CRM_settings__r.musqot__Expression_business_region__c,
                             	   Target_CRM_settings__r.Expression_business_area__c
                             FROM  Milestone__c 
                             where Milestone_type__c=5 limit 1000];
        
        // to query out crm data
        for(Milestone__c ms : milestoneList) {
            If (ms.Marketing_activity__c <> null) {
                If (ms.Marketing_activity__r.Starts_date__c < startDate){
                    startDate = ms.Project__r.Starts_date__c;
                }
            }
            else If (ms.Project__c <> null) {
                If (ms.Project__r.Starts_date__c < startDate){
                    startDate = ms.Project__r.Starts_date__c;
                }
            }
            else If (ms.Plan__c <> null) {
                If (ms.Plan__r.Starts_date__c < startDate){
                    startDate = ms.Plan__r.Starts_date__c;
                }
            }
        }
        crmDataList = [SELECT Id, Date__c, Business_area__c, Business_region__c, 
                       		No_Leads__c, 
                       		No_Opportunities__c, Value_Opportunities__c, Value_w_Opportunities__c, 
                       		Value_Deals__c
                      FROM  CRM_data__c 
                      where Date__c>=:startDate AND Date__c<=:TODAY];	
        // end -- to query out crm data
        // 
        	
        	Decimal TargetNumber_Leads;
            Decimal TargetNumber_Opportunities;
            Decimal TargetNumber_Amount;
            Decimal TargetNumber_Win;
            Decimal TargetNumber_Loose;
            Decimal TargetNumber_Weighted;
        
        for(Milestone__c updatemilestone : milestoneList) {
                 TargetNumber_Leads = 0;
                 TargetNumber_Opportunities = 0;
                 TargetNumber_Amount = 0;
                 TargetNumber_Win = 0;
                 TargetNumber_Loose = 0;
                 TargetNumber_Weighted = 0;
                 if(updatemilestone.Target_CRM_settings__r.Expression_business_region__c !=null){
                     businessRegion= updatemilestone.Target_CRM_settings__r.Expression_business_region__c;
                     businessRegionList.addAll(businessRegion.split('\\s*(=>|,|\\s)\\s*')); 
                 }
                 if(updatemilestone.Target_CRM_settings__r.Expression_business_area__c !=null){
                     businessArea= updatemilestone.Target_CRM_settings__r.Expression_business_area__c;
                     businessAreaList.addAll(businessArea.split('\\s*(=>|,|\\s)\\s*')); 
                 }

                 for(musqot__CRM_data__c crmData : crmDataList) {
					       if(updatemilestone.Marketing_activity__c <> null) {
                            	if (crmData.Date__c >= updatemilestone.Marketing_activity__r.Starts_date__c 
                                    && crmData.Date__c >= updatemilestone.Marketing_activity__r.Ends_date__c) {
                                        If(businessAreaList <> null) {
                                            for(String bal : businessAreaList) {
                                                if(bal == crmData.Business_area__c) {
                                                    if(businessRegionList <> null) {
                                                        for(String brl : businessRegionList) {
                                                            if(brl == crmData.Business_region__c) {
                                                                 TargetNumber_Leads += crmData.No_Leads__c;
                                                                 TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                                 TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                                 TargetNumber_Win += crmData.Value_Deals__c;
                                                                 TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                                 if(crmData.Value_Deals__c == 0) {
                                                                     TargetNumber_Loose += 1;
                                                                 }   
                                                            }
                                                        }
                                                    } else {
                                                        TargetNumber_Leads += crmData.No_Leads__c;
                                                        TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                        TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                        TargetNumber_Win += crmData.Value_Deals__c;
                                                        TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                        if(crmData.Value_Deals__c == 0) {
                                                            TargetNumber_Loose += 1;
                                                        }   
                                                    }
                                                }
                                            }
                                        } else {
                                            if(businessRegionList <> null) {
                                                for(String brl : businessRegionList) {
                                                    if(brl == crmData.Business_region__c) {
                                                        TargetNumber_Leads += crmData.No_Leads__c;
                                                        TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                        TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                        TargetNumber_Win += crmData.Value_Deals__c;
                                                        TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                        if(crmData.Value_Deals__c == 0) {
                                                            TargetNumber_Loose += 1;
                                                        }   
                                                    }
                                                }
                                            } else {
                                                TargetNumber_Leads += crmData.No_Leads__c;
                                                TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                TargetNumber_Win += crmData.Value_Deals__c;
                                                TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                if(crmData.Value_Deals__c == 0) {
                                                    TargetNumber_Loose += 1;
                                                }   
                                            }
                                        }
                                    }
							} 
						   	else If (updatemilestone.Project__c <> null) {
								if (crmData.Date__c >= updatemilestone.Project__r.Starts_date__c 
                                    && crmData.Date__c >= updatemilestone.Project__r.Ends_date__c) {
                                        If(businessAreaList <> null) {
                                            for(String bal : businessAreaList) {
                                                if(bal == crmData.Business_area__c) {
                                                    if(businessRegionList <> null) {
                                                        for(String brl : businessRegionList) {
                                                            if(brl == crmData.Business_region__c) {
                                                                 TargetNumber_Leads += crmData.No_Leads__c;
                                                                 TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                                 TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                                 TargetNumber_Win += crmData.Value_Deals__c;
                                                                 TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                                 if(crmData.Value_Deals__c == 0) {
                                                                     TargetNumber_Loose += 1;
                                                                 }   
                                                            }
                                                        }
                                                    } else {
                                                        TargetNumber_Leads += crmData.No_Leads__c;
                                                        TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                        TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                        TargetNumber_Win += crmData.Value_Deals__c;
                                                        TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                        if(crmData.Value_Deals__c == 0) {
                                                            TargetNumber_Loose += 1;
                                                        }   
                                                    }
                                                }
                                            }
                                        } else {
                                            if(businessRegionList <> null) {
                                                for(String brl : businessRegionList) {
                                                    if(brl == crmData.Business_region__c) {
                                                        TargetNumber_Leads += crmData.No_Leads__c;
                                                        TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                        TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                        TargetNumber_Win += crmData.Value_Deals__c;
                                                        TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                        if(crmData.Value_Deals__c == 0) {
                                                            TargetNumber_Loose += 1;
                                                        }   
                                                    }
                                                }
                                            } else {
                                                TargetNumber_Leads += crmData.No_Leads__c;
                                                TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                TargetNumber_Win += crmData.Value_Deals__c;
                                                TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                if(crmData.Value_Deals__c == 0) {
                                                    TargetNumber_Loose += 1;
                                                }   
                                            }
                                        }
                                    }
							}
						
							else If (updatemilestone.Plan__c <> null) {
								if (crmData.Date__c >= updatemilestone.Plan__r.Starts_date__c 
                                    && crmData.Date__c >= updatemilestone.Plan__r.Ends_date__c) {
                                       If(businessAreaList <> null) {
                                            for(String bal : businessAreaList) {
                                                if(bal == crmData.Business_area__c) {
                                                    if(businessRegionList <> null) {
                                                        for(String brl : businessRegionList) {
                                                            if(brl == crmData.Business_region__c) {
                                                                 TargetNumber_Leads += crmData.No_Leads__c;
                                                                 TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                                 TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                                 TargetNumber_Win += crmData.Value_Deals__c;
                                                                 TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                                 if(crmData.Value_Deals__c == 0) {
                                                                     TargetNumber_Loose += 1;
                                                                 }   
                                                            }
                                                        }
                                                    } else {
                                                        TargetNumber_Leads += crmData.No_Leads__c;
                                                        TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                        TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                        TargetNumber_Win += crmData.Value_Deals__c;
                                                        TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                        if(crmData.Value_Deals__c == 0) {
                                                            TargetNumber_Loose += 1;
                                                        }   
                                                    }
                                                }
                                            }
                                        } else {
                                            if(businessRegionList <> null) {
                                                for(String brl : businessRegionList) {
                                                    if(brl == crmData.Business_region__c) {
                                                        TargetNumber_Leads += crmData.No_Leads__c;
                                                        TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                        TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                        TargetNumber_Win += crmData.Value_Deals__c;
                                                        TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                        if(crmData.Value_Deals__c == 0) {
                                                            TargetNumber_Loose += 1;
                                                        }   
                                                    }
                                                }
                                            } else {
                                                TargetNumber_Leads += crmData.No_Leads__c;
                                                TargetNumber_Opportunities += crmData.Value_Opportunities__c;
                                                TargetNumber_Amount += crmData.Value_Opportunities__c;
                                                TargetNumber_Win += crmData.Value_Deals__c;
                                                TargetNumber_Weighted += crmData.Value_w_Opportunities__c;
                                                if(crmData.Value_Deals__c == 0) {
                                                    TargetNumber_Loose += 1;
                                                }   
                                            }
                                        } 
                                    }
							}

                         
                                   
                 }
                 
                 if(updatemilestone.Target_CRM_settings__r.Watch_type__c=='No Leads'){
                         updatemilestone.Status__c = getStatus(updatemilestone,TargetNumber_Leads);
                     	 updatemilestone.Target_number_outcome__c = TargetNumber_Leads;
                 } 
                 if(updatemilestone.Target_CRM_settings__r.Watch_type__c=='No Opportunities'){   
                     	 updatemilestone.Status__c = getStatus(updatemilestone,TargetNumber_Opportunities);
                     	 updatemilestone.Target_number_outcome__c = TargetNumber_Opportunities;
                 }
                 if(updatemilestone.Target_CRM_settings__r.Watch_type__c=='Amount Opportunities'){
                         updatemilestone.Status__c = getStatus(updatemilestone,TargetNumber_Amount);
                     	 updatemilestone.Target_number_outcome__c = TargetNumber_Amount;
                 }
                 if(updatemilestone.Target_CRM_settings__r.Watch_type__c=='No Wins'){
                         updatemilestone.Status__c = getStatus(updatemilestone,TargetNumber_Loose);
                     	 updatemilestone.Target_number_outcome__c = TargetNumber_Loose;
                 }
                 if(updatemilestone.Target_CRM_settings__r.Watch_type__c=='Amount Wins'){
                         updatemilestone.Status__c = getStatus(updatemilestone,TargetNumber_Win);
                     	 updatemilestone.Target_number_outcome__c = TargetNumber_Win;
                     
                 }
                 if(updatemilestone.Target_CRM_settings__r.Watch_type__c=='Amount (weighted) Opportunities'){
                      	 updatemilestone.Status__c = getStatus(updatemilestone,TargetNumber_Weighted);
                     	 updatemilestone.Target_number_outcome__c = TargetNumber_Weighted;
                 }
                
                updateMilestoneList.add(updatemilestone);
            }
            update updateMilestoneList;
        
           // reschediuling the job
           try{
                List<CRM_settings__c> cmrs = [SELECT Id, name from CRM_settings__c where CRM_performance_type__c= 'Milestone'];
                if(cmrs.size() > 0) {
                    // if milestone present
                    Date tomorrowsDate = System.today().addDays(1);
                    Integer day = tomorrowsDate.day();
                    Integer month = tomorrowsDate.month();
                    Integer year = tomorrowsDate.year();
                    String SchTimer='0 10 1 '+day+' '+month+' ? '+year;   //  next day 1:10 AM
                    System.schedule('CRMMilestoneUpdateSchedulerJob', SchTimer, new CRMMilestoneUpdateScheduler());
                }
            }catch(Exception e){
                System.debug('Exception : ' + e.getMessage());
            }
    }
    
    public String getStatus(Milestone__c updatemilestone, Decimal TargetNumber_outcome) {
        // Update Status      
        If( updatemilestone.Target_number__c > 0||updatemilestone.Target_number__c <> null){
            if(updatemilestone.Targetdate__c > toDay && updatemilestone.Target_number__c < TargetNumber_outcome){
                updatemilestone.Status__c= 'Open';                
            }
            else if(updatemilestone.Targetdate__c >= toDay && updatemilestone.Target_number__c >= TargetNumber_outcome && updatemilestone.Status__c <> 'Reach Delayed' ){
                updatemilestone.Status__c= 'Reach on time';        
            }
            else if(updatemilestone.Targetdate__c <= toDay && updatemilestone.Target_number__c >= TargetNumber_outcome){
                updatemilestone.Status__c= 'Not Reach';          
            }
            else if(updatemilestone.Targetdate__c < toDay && updatemilestone.Target_number__c < TargetNumber_outcome){
                updatemilestone.Status__c= 'Reach Delayed'; 
            }          
        }
        else{
            updatemilestone.Status__c= '?';
        }  
        return updatemilestone.Status__c;
        // status end
    }
}