src/objects/CRM_settings__c.object
<CustomObject>
    <fields>
        <fullName>Expression_business_area__c</fullName>
        <inlineHelpText>Here you can enter which campaign to be included for the selected milestone, one row for each campaign</inlineHelpText>
        <label>Campaign</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expression_business_region__c</fullName>
        <inlineHelpText>Here you can enter which lead source to be included for the selected milestone, one row for each source</inlineHelpText>
        <label>Lead Source</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Watch_type__c</fullName>
        <inlineHelpText>For milestone you can only choice one option</inlineHelpText>
        <label>Watch type</label>
        <picklist>
            <picklistValues>
                <fullName>No Leads</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Wins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount (weighted) Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount Wins</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>CRM settings</label>
    <nameField>
        <label>Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ERP_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Expression_business_area__c</fullName>
        <inlineHelpText>Here you can enter which business areas to be included for the selected milestone, one row for each area</inlineHelpText>
        <label>Expression business area</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expression_business_region__c</fullName>
        <inlineHelpText>Here you can enter which business regions to be included for the selected milestone, one row for each region</inlineHelpText>
        <label>Expression business region</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ERP Settings</label>
    <nameField>
        <label>Settings name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_type__c</fullName>
        <label>Milestone type</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reach on time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reach delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not reach</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_CRM_settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target CRM settings</label>
        <referenceTo>CRM_settings__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_ERP_Sales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target ERP Sales</label>
        <referenceTo>ERP_Settings__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Taget marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Milestones (Target Project)</relationshipLabel>
        <relationshipName>Milestones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Socialmedia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Socialmedia</label>
        <referenceTo>socialmedia_settings__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_number__c</fullName>
        <label>Target_number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_number_outcome__c</fullName>
        <description>This feild will be update by trigger in ERP, CRM and Social media</description>
        <label>Target number outcome</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Targetdate__c</fullName>
        <label>Target date</label>
        <type>Date</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/socialmedia_settings__c.object
<CustomObject>
    <description>The Name will show-up in the Performance Gantt view.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Performance, general</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Performance, project</fullName>
            </value>
            <value>
                <fullName>Performance, marketing activity</fullName>
            </value>
            <value>
                <fullName>Milestone</fullName>
            </value>
            <value>
                <fullName>Performance, costcenter</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Watch_type__c</fullName>
        <label>Watch type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Unique visitors</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Likes / click</fullName>
            </value>
            <value>
                <fullName>Members</fullName>
            </value>
            <value>
                <fullName>Unique visitor &amp; click/likes</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Socialmedia Settings</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Socialmedia Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MilestoneEditController.cls
/********************************************************************
Class Name: MilestoneEditController
Author:G Janardhanreddy         Last modified by: Chaithanya Daggumati
Date: 25/8/2014                 Date: 19/3/2015 
********©2013 Musqot marketing technology Pvt ltd ********************/
public with sharing class MilestoneEditController{
        public String projectid{get;set;}
        public String mileId{get;set;}
        public String subprjid{get;set;}
        public String mrkId{get;set;}
        Public Milestone__c Miles{get;set;}
        public boolean showRec{get;set;}
        public boolean hiderec{get;set;}
        public boolean showEdt{get;set;}
        public boolean showEdtbtn{get;set;}
        public boolean hideTargetNo{get;set;}
    	public boolean hideOutTargetNo{get;set;}
    
        private date startDate;
        private date endDate;
        public musqot__Activity__c actRec{get;set;}
        public boolean erpSetting{get;set;}
        public List<Socialmedia_settings__c> PRO_Temp = new List<Socialmedia_settings__c>();
        public List<ERP_Settings__c> sale_Temp = new List<ERP_Settings__c>();
        public MilestoneEditController(ApexPages.StandardController controller) {
            projectid = ApexPages.currentPage().getParameters().get('planid');
            subprjid = ApexPages.currentPage().getParameters().get('subid');
            mrkId = ApexPages.currentPage().getParameters().get('mrk');
            mileId= ApexPages.currentPage().getParameters().get('mileId');
            String MyProflieName;
            List<Profile> userprofile =new List<Profile>();
            userprofile = [SELECT Id, Name 
                           FROM Profile 
                           WHERE Id=:userinfo.getProfileId() Limit 1];
            MyProflieName = userprofile[0].Name;
            Miles= [select Id,Name, ownerid, Plan__c, Targetdate__c, Target_number__c, Target_number_outcome__c, Project__c, Status__c, Description__c, 
                        Target_Marketing_activity__c, Target_Marketing_activity__r.Name, Target_Project__c, 
                        Target_Project__r.Name ,Target_Socialmedia__c,Target_Socialmedia__r.Name,
                        Target_ERP_Sales__r.Name,Target_ERP_Sales__r.Expression_business_region__c,Target_ERP_Sales__r.Expression_business_area__c ,Milestone_type__c,Target_CRM_settings__r.Watch_type__c,Target_CRM_settings__r.Expression_business_region__c,Target_CRM_settings__r.Expression_business_area__c 
                    from Milestone__c 
                    where id =:mileId];
            if(miles.Milestone_type__c==3||miles.Milestone_type__c==4||miles.Milestone_type__c==5||miles.Milestone_type__c==9)
                hideTargetNo=true; 
            if(miles.Milestone_type__c==9)
                hideOutTargetNo=true; 
            if(mileId<>null && subprjid <>null){
                    try{
                       Subproject__c subPrj = [select Id,Parent_project__c, Project_del__c, planid__c, Project_del__r.id,Ends_date__c,Starts_date__c 
                                               from Subproject__c 
                                               where Id =:subprjid limit 1]; 
                       startDate = subPrj.Starts_date__c;
                       endDate = subPrj.Ends_date__c;  
                    }catch(Exception e){}           
                }
                else{
                    try{
                         musqot__Project__c  proRec=[SELECT Id, Starts_date__c, Ends_date__c 
                                                     FROM Project__c 
                                                     WHERE Id=:projectid LIMIT 1];
                         startDate = proRec.Starts_date__c;
                         endDate = proRec.Ends_date__c;
                    }catch(Exception e){} 
               }           
            if(miles.ownerid==UserInfo.getUserId()|| MyProflieName =='System Administrator'){     
                showEdt=true;
                showEdtbtn=false;  
            }
                showRec=true;
                hiderec=false;
            actRec=[SELECT Id, Name, Use_Performance_CRM__c, Use_socialmedia__c, Use_Performance_ERP__c 
                    FROM Activity__c  LIMIT 1 ]; 
            if(miles.Milestone_type__c==4){         
                if(actRec.musqot__Use_Performance_ERP__c==true){
                    erpSetting=false;
                }else
                    erpSetting=true;
            }
            if(miles.Milestone_type__c==3){         
                if(actRec.musqot__Use_socialmedia__c==true){
                    erpSetting=false;
                }else
                    erpSetting=true;
            }
            if(miles.Milestone_type__c==5){         
                if(actRec.musqot__Use_Performance_CRM__c<>'Not used'){
                    erpSetting=false;
                }else
                    erpSetting=true;
            }
            
            
        }
        /****************************************************************
        Save(): update the milestone and redirects to related parent page
        *****************************************************************/
        public Pagereference Save(){ 
            Pagereference pr;
            if(Miles<>null){ 
                IF( Miles.Targetdate__c > system.today() && Miles.Target_number__c <= Miles.Target_number_outcome__c && Miles.Status__c <> 'Reach delayed'){
                    Miles.Status__c = 'Reach on time';
                }
                else if(Miles.Targetdate__c > system.today() ){
                    Miles.Status__c = 'Open';
                }                    
               if (Milestone__c.sObjectType.getDescribe().isUpdateable()){           
                    Update Miles;
                }
                if(projectid<>null){
                    String tabId = System.currentPageReference().getParameters().get('tabId');
                    string pageRef='/apex/ProjectDetails?id='+EncodingUtil.urlEncode(projectid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('tb5','UTF-8');
                    pr=new Pagereference (pageRef);
                }
                else if(subprjid<>null){
                    String tabId = System.currentPageReference().getParameters().get('tabId');
                    string pageRef='/apex/SubProject?id='+EncodingUtil.urlEncode(subprjid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('tb5','UTF-8');
                    pr=new Pagereference (pageRef);
                }           
            }
            return pr;
        }
        Public void gotoEditMode(){ //show record edit mode
            hideTargetNo=false;  
            hideOutTargetNo=false; 
            if(miles.Milestone_type__c==9){
                hideOutTargetNo=true; 
                hideTargetNo=true;
            }
            
            showRec=false;
            hiderec=true;
            showEdt=false;
            showEdtbtn=true; 
            
        }      
        Public void gotoInfoMode(){ // show record edit mode through homw page
            showRec=false;
            hiderec=true;
            showEdt=false;
            showEdtbtn=true; 
         
        } 
        /*************************************************************************************************
        deleteMilestone(): delete milestone from the MilestoneEditpage and redirects to related parent page
        **************************************************************************************************/
        public Pagereference deleteMilestone(){
            if (Milestone__c.sObjectType.getDescribe().isDeletable())
            {  
                delete miles;
            }
            Pagereference pr;
            if(projectid<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/ProjectDetails?id='+EncodingUtil.urlEncode(projectid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('tb5','UTF-8');
                pr=new Pagereference (pageRef);
            }
            else if(subprjid<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/SubProject?id='+EncodingUtil.urlEncode(subprjid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('tb5','UTF-8');
                pr=new Pagereference (pageRef);
            }
            return pr;
        } 
        /********************************************************
        SocialmediaList: Convert lookup to dropdown 
        *********************************************************/
        public List<SelectOption> SocialMedia  {
            get
            {
                PRO_Temp = [Select u.Name, u.Id From Socialmedia_settings__c u where type__c = 'Milestone'  limit 250 ];
                SocialMedia= new List<SelectOption>(); 
                for(Socialmedia_settings__c objPROT : PRO_Temp )
                {
                    SocialMedia.add(new SelectOption(objPROT.Id, objPROT.Name));
                }
                return SocialMedia;
            }
            set;
        }
      /********************************************************
        ERPList: Convert lookup to dropdown 
        *********************************************************/
        public List<SelectOption> ERPSales  {
            get
            {
                sale_Temp = [Select u.Name, u.Id 
                             From ERP_Settings__c u 
                             where ERP_performance_type__c = 'Milestone'  limit 250 ]; 
                ERPSales = new List<SelectOption>(); 
                for(ERP_Settings__c objPROT2 : sale_Temp )
                {
                    ERPSales.add(new SelectOption(objPROT2.Id, objPROT2.Name));
                }
                return ERPSales;
            }
            set;
        }    
        /****************************************
        Cancel():redirects to related parent page
        *****************************************/
        public Pagereference Cancel(){
            Pagereference pr;
            if(projectid<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/ProjectDetails?id='+EncodingUtil.urlEncode(projectid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('tb5','UTF-8');
                pr=new Pagereference (pageRef);
            }
            else if(subprjid<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/SubProject?id='+EncodingUtil.urlEncode(subprjid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('tb5','UTF-8');
                pr=new Pagereference (pageRef);
                }       
            return pr;
         }
          // This is for render target number field based on coditions(Milestontype)
        public void selctType(){
            IF(miles.Milestone_type__c==4 ||miles.Milestone_type__c==3||miles.Milestone_type__c==5||miles.Milestone_type__c==9)
                hideTargetNo=true; 
             else
                hideTargetNo=false;  
            
            IF(miles.Milestone_type__c==9)
                hideOutTargetNo=false; 
             else
                hideOutTargetNo=true; 
        }  
      
    }