src/objects/ERP_logfile__c.object
<CustomObject>
    <fields>
        <fullName>Import_message__c</fullName>
        <label>Import message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Imported__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Imported</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_records__c</fullName>
        <label>Number of records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ERP logfile</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP logfile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ERP_sales_obj__c.object
<CustomObject>
    <fields>
        <fullName>Business_area__c</fullName>
        <label>Business area</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_region__c</fullName>
        <label>Business region</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_logfile__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ERP logfile</label>
        <referenceTo>ERP_logfile__c</referenceTo>
        <relationshipName>ERP_sales_obj</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <label>Sales</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_date__c</fullName>
        <label>Sales date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_import_date__c</fullName>
        <description>Date the the import is dun</description>
        <label>Sales import date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sales_currency__c</fullName>
        <label>sales currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sales_import_id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Id of the imported record</description>
        <externalId>true</externalId>
        <label>Sales import id</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ERP Sales Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP_sales_obj</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipLabel>Milestones (Marketing activity)</relationshipLabel>
        <relationshipName>Milestones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone_type__c</fullName>
        <label>Milestone type</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reach on time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reach delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not reach</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Achieved__c</fullName>
        <label>Target Achieved</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_ERP_Sales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target ERP Sales</label>
        <referenceTo>ERP_Settings__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Milestones (Target Project)</relationshipLabel>
        <relationshipName>Milestones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_number__c</fullName>
        <label>Target_number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_number_outcome__c</fullName>
        <description>This feild will be update by trigger in ERP, CRM and Social media</description>
        <label>Target number outcome</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Targetdate__c</fullName>
        <label>Target date</label>
        <type>Date</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ERPMilestoneUpdateSchedulertest.cls
/****************************************************************
Class Name: ERPMilestoneUpdateSchedulertest
Author:chaithanya daggumati                  Last modified by:chaithanya daggumati
Date: 26/10/2015                             Date: 26/10/2015
Description: class to schedule the CRM data update.
********©2013 Musqot marketing technology Pvt ltd ****************/
@isTest(seeAllData=true)
public class ERPMilestoneUpdateSchedulertest{
    static testMethod void ERPmilestonesupdate(){ 
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
         objMarketingact.Name='test';
         objMarketingact.Description__c='tdescriptionest';
         objMarketingact.Status__c='completed';
         objMarketingact.musqot__ERP__c='testERP';
         objMarketingact.musqot__Social_media__c='testSocial';
         objMarketingact.musqot__CRM__c='testCRM';
         objMarketingact.Starts_date__c=Date.Today();
         objMarketingact.Ends_date__c=Date.Today();
         //objMarketingact.musqot__Activitytype__c=objActiv.id;
         insert objMarketingact;
         System.assertEquals('test', objMarketingact.name);

        musqot__ERP_Settings__c  ERPset=new musqot__ERP_Settings__c ();
        ERPset.Name='testERPEdit';
        ERPset.musqot__Selector__c='Business area';
        ERPset.musqot__erp_Chart__c='Bar charts';
        ERPset.musqot__Bar_color__c='#123344,#224466';
        ERPset.ERP_performance_type__c='Performance, project';
        ERPset.Expression_business_area__c='APAC';
        ERPset.Expression_business_region__c='Global';
        System.assertEquals('Business area', ERPset.musqot__Selector__c);
        insert ERPset;
        
        ERP_logfile__c mus=new ERP_logfile__c();
        mus.Imported__c=true;        
        mus.Import_message__c='helloworld';
        mus.Number_of_records__c=2;
        System.assertEquals('helloworld', mus.Import_message__c);
        insert mus;
        
        ERP_sales_obj__c erp=new ERP_sales_obj__c();
        erp.Business_area__c='APAC';
        erp.Business_region__c='Global';
        erp.ERP_logfile__c=mus.id;
        erp.Sales__c=200;
        erp.sales_currency__c='cur';
        erp.Sales_date__c=Date.Today();
        erp.Sales_import_date__c=Date.Today();
        erp.sales_import_id__c='saleid';
        System.assertEquals('APAC', erp.Business_area__c);
        insert erp;
        
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'mile';
        //objmilestone.Plan__c=objproj.id;
        //objmilestone.Project__c=objsubproj .id;
        //objmilestone.Target_Project__c=objMarketingact.id;
        objmilestone.Marketing_activity__c=objMarketingact.id;
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_ERP_Sales__c=ERPset.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        objmilestone.Target_Achieved__c=2;
        objmilestone.Target_number_outcome__c=10;        
        insert objmilestone;
        System.assertEquals('mile', objmilestone.Name);
        
        OAuthService__c  OAuth=new OAuthService__c ();
        OAuth.Name='ffbook';
        OAuth.musqot__Authorization_Type__c='Requestheader';
        OAuth.musqot__Authorization_URL__c='https://www.facebook.com/dialog/oauth';
        OAuth.musqot__Response_Type__c='token';
        OAuth.musqot__Signature_Method__c='PLAINTEXT'; 
        OAuth.musqot__Bar_color__c='#333';   
        System.assertEquals('PLAINTEXT', OAuth.musqot__Signature_Method__c);
        insert OAuth;
        
     ERPMilestoneUpdateScheduler ERPschedule = new ERPMilestoneUpdateScheduler();
        SchedulableContext sc;
        ERPschedule.execute(sc);
        ERPschedule.getStatus(objmilestone,10);   
    }
    static testMethod void ERPmilestonesupdate1() {
     Subproject__c objsubproj = new Subproject__c();
        objsubproj .Name = 'test';
        //objsubproj .musqot__Parent_project__c=objproj.id;
        objsubproj .Starts_date__c = Date.Today();
        objsubproj .Ends_date__c = Date.Today();
        objsubproj .Description__c = 'testdesc';
        System.assertEquals('test', objsubproj .Name);
        insert objsubproj ;
        
        musqot__ERP_Settings__c  ERPset=new musqot__ERP_Settings__c ();
        ERPset.Name='testERPEdit';
        ERPset.musqot__Selector__c='Business region';
        ERPset.musqot__erp_Chart__c='Line charts';
        ERPset.musqot__Bar_color__c='#FF9933,#A700DF,#369E2B';
        ERPset.ERP_performance_type__c='Milestone';
        ERPset.Expression_business_area__c='APAC';
       // ERPset.Expression_business_region__c='Global';
        System.assertEquals('Business region', ERPset.musqot__Selector__c);
        insert ERPset;
        
        ERP_logfile__c mus=new ERP_logfile__c();
        mus.Imported__c=true;        
        mus.Import_message__c='helloworld';
        mus.Number_of_records__c=5;
        System.assertEquals('helloworld', mus.Import_message__c);
        insert mus;
        
        ERP_sales_obj__c erp=new ERP_sales_obj__c();
        erp.Business_area__c='APAC';
        erp.Business_region__c='Global';
        erp.ERP_logfile__c=mus.id;
        erp.Sales__c=200;
        erp.sales_currency__c='cur';
        erp.Sales_date__c=Date.Today();
        erp.Sales_import_date__c=Date.Today();
        erp.sales_import_id__c='saleid';
        System.assertEquals('Global', erp.Business_region__c);
        insert erp;
        
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'mile'; 
        objmilestone.Project__c =objsubproj.id;       
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_ERP_Sales__c=ERPset.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        objmilestone.Target_Achieved__c=2;
        objmilestone.Target_number_outcome__c=10;        
        insert objmilestone;
        System.assertEquals('mile', objmilestone.Name);
        
     ERPMilestoneUpdateScheduler ERPschedule = new ERPMilestoneUpdateScheduler();
        SchedulableContext sc;
        ERPschedule.execute(sc);
        ERPschedule.getStatus(objmilestone,10);           
    }
     static testMethod void ERPmilestonesupdate2(){
     	Profile p = [select id from profile where name='System Administrator']; 
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id, 
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ;  
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c); 
     Project__c objproj = new Project__c();
        objproj.name = 'testname';
        objproj.Starts_date__c = Date.Today()-5;
        objproj.Ends_date__c =  Date.Today()-10; 
        objproj.Description__c = 'sampdesc';
        objproj.ownerid =plm.userid__c;
        System.assertEquals('testname', objproj .name);
        insert objproj;
        
        musqot__ERP_Settings__c  ERPset=new musqot__ERP_Settings__c ();
        ERPset.Name='testERPEdit';
        ERPset.musqot__Selector__c='Business region';
        ERPset.musqot__erp_Chart__c='Line charts';
        ERPset.musqot__Bar_color__c='#FF9933,#A700DF,#369E2B';
        ERPset.ERP_performance_type__c='Milestone';
        ERPset.Expression_business_area__c='APAC';
        //ERPset.Expression_business_region__c='Global';
        System.assertEquals('Business region', ERPset.musqot__Selector__c);
        insert ERPset;
        
        ERP_logfile__c mus=new ERP_logfile__c();
        mus.Imported__c=true;        
        mus.Import_message__c='helloworld';
        mus.Number_of_records__c=5;
        System.assertEquals('helloworld', mus.Import_message__c);
        insert mus;
        
        ERP_sales_obj__c erp=new ERP_sales_obj__c();
        erp.Business_area__c='APAC';
        erp.Business_region__c='Global';
        erp.ERP_logfile__c=mus.id;
        erp.Sales__c=200;
        erp.sales_currency__c='cur';
        erp.Sales_date__c=Date.Today();
        erp.Sales_import_date__c=Date.Today();
        erp.sales_import_id__c='saleid';
        System.assertEquals('Global', erp.Business_region__c);
        insert erp;
        
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'mile';  
        objmilestone.Plan__c=objproj.id;      
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_ERP_Sales__c=ERPset.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        objmilestone.Target_Achieved__c=2;
        objmilestone.Target_number_outcome__c=10;        
        insert objmilestone;
        System.assertEquals('mile', objmilestone.Name);
        
        ERPMilestoneUpdateScheduler ERPschedule = new ERPMilestoneUpdateScheduler();
        SchedulableContext sc;
        ERPschedule.execute(sc);
        ERPschedule.getStatus(objmilestone,10);           
    }
    static testMethod void ERPmilestonesupdate3(){
     Profile p = [select id from profile where name='System Administrator']; 
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id, 
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ;  
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
     	Project__c objproj = new Project__c();
        objproj.name = 'testname';
        objproj.Starts_date__c = Date.Today()-5;
        objproj.Ends_date__c =  Date.Today()-10; 
        objproj.Description__c = 'sampdesc';
        objproj.ownerid =plm.userid__c;
        System.assertEquals('testname', objproj .name);
        insert objproj;
        
        musqot__ERP_Settings__c  ERPset=new musqot__ERP_Settings__c ();
        ERPset.Name='testERPEdit';
        ERPset.musqot__Selector__c='Business region';
        ERPset.musqot__erp_Chart__c='Line charts';
        ERPset.musqot__Bar_color__c='#FF9933,#A700DF,#369E2B';
        ERPset.ERP_performance_type__c='Milestone';
        ERPset.Expression_business_area__c='';
        ERPset.Expression_business_region__c='Global';
        System.assertEquals('Business region', ERPset.musqot__Selector__c);
        insert ERPset;
        
        ERP_logfile__c mus=new ERP_logfile__c();
        mus.Imported__c=true;        
        mus.Import_message__c='helloworld';
        mus.Number_of_records__c=5;
        System.assertEquals('helloworld', mus.Import_message__c);
        insert mus;
        
        ERP_sales_obj__c erp=new ERP_sales_obj__c();
        //erp.Business_area__c='APAC';
        erp.Business_region__c='Global';
        erp.ERP_logfile__c=mus.id;
        erp.Sales__c=200;
        erp.sales_currency__c='cur';
        erp.Sales_date__c=Date.Today();
        erp.Sales_import_date__c=Date.Today();
        erp.sales_import_id__c='saleid';
        System.assertEquals('Global', erp.Business_region__c);
        insert erp;
        
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'mile';  
        objmilestone.Plan__c=objproj.id;      
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_ERP_Sales__c=ERPset.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        objmilestone.Target_Achieved__c=2;
        objmilestone.Target_number_outcome__c=10;        
        insert objmilestone;
        System.assertEquals('mile', objmilestone.Name);
        
        ERPMilestoneUpdateScheduler ERPschedule = new ERPMilestoneUpdateScheduler();
        SchedulableContext sc;
        ERPschedule.execute(sc);
        ERPschedule.getStatus(objmilestone,10);           
    }
     static testMethod void ERPmilestonesupdate4() {
     Subproject__c objsubproj = new Subproject__c();
        objsubproj .Name = 'test';
        //objsubproj .musqot__Parent_project__c=objproj.id;
        objsubproj .Starts_date__c = Date.Today();
        objsubproj .Ends_date__c = Date.Today();
        objsubproj .Description__c = 'testdesc';
        System.assertEquals('test', objsubproj .Name);
        insert objsubproj ;
        
        musqot__ERP_Settings__c  ERPset=new musqot__ERP_Settings__c ();
        ERPset.Name='testERPEdit';
        ERPset.musqot__Selector__c='Business region';
        ERPset.musqot__erp_Chart__c='Line charts';
        ERPset.musqot__Bar_color__c='#FF9933,#A700DF,#369E2B';
        ERPset.ERP_performance_type__c='Milestone';
        //ERPset.Expression_business_area__c='APAC';
        ERPset.Expression_business_region__c='Global';
        System.assertEquals('Business region', ERPset.musqot__Selector__c);
        insert ERPset;
        
        ERP_logfile__c mus=new ERP_logfile__c();
        mus.Imported__c=true;        
        mus.Import_message__c='helloworld';
        mus.Number_of_records__c=5;
        System.assertEquals('helloworld', mus.Import_message__c);
        insert mus;
        
        ERP_sales_obj__c erp=new ERP_sales_obj__c();
        //erp.Business_area__c='APAC';
        erp.Business_region__c='Global';
        erp.ERP_logfile__c=mus.id;
        erp.Sales__c=200;
        erp.sales_currency__c='cur';
        erp.Sales_date__c=Date.Today();
        erp.Sales_import_date__c=Date.Today();
        erp.sales_import_id__c='saleid';
        System.assertEquals('Global', erp.Business_region__c);
        insert erp;
        System.assertEquals(null, erp.Business_area__c);
        
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'mile'; 
        objmilestone.Project__c =objsubproj.id;       
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_ERP_Sales__c=ERPset.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        objmilestone.Target_Achieved__c=2;
        objmilestone.Target_number_outcome__c=10;        
        insert objmilestone;
        System.assertEquals('mile', objmilestone.Name);
        
     ERPMilestoneUpdateScheduler ERPschedule = new ERPMilestoneUpdateScheduler();
        SchedulableContext sc;
        ERPschedule.execute(sc);
        ERPschedule.getStatus(objmilestone,10);           
    }
     static testMethod void ERPmilestonesupdate6(){ 
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
         objMarketingact.Name='test';
         objMarketingact.Description__c='tdescriptionest';
         objMarketingact.Status__c='completed';
         objMarketingact.musqot__ERP__c='testERP';
         objMarketingact.musqot__Social_media__c='testSocial';
         objMarketingact.musqot__CRM__c='testCRM';
         objMarketingact.Starts_date__c=Date.Today();
         objMarketingact.Ends_date__c=Date.Today();
         //objMarketingact.musqot__Activitytype__c=objActiv.id;
         insert objMarketingact;
         System.assertEquals('test', objMarketingact.name);

        musqot__ERP_Settings__c  ERPset=new musqot__ERP_Settings__c ();
        ERPset.Name='testERPEdit';
        ERPset.musqot__Selector__c='Business area';
        ERPset.musqot__erp_Chart__c='Bar charts';
        ERPset.musqot__Bar_color__c='#123344,#224466';
        ERPset.ERP_performance_type__c='Performance, project';
        ERPset.Expression_business_area__c='APAC';
        //ERPset.Expression_business_region__c='Global';
        System.assertEquals('Business area', ERPset.musqot__Selector__c);
        insert ERPset;
        
        ERP_logfile__c mus=new ERP_logfile__c();
        mus.Imported__c=true;        
        mus.Import_message__c='helloworld';
        mus.Number_of_records__c=2;
        System.assertEquals('helloworld', mus.Import_message__c);
        insert mus;
        
        ERP_sales_obj__c erp=new ERP_sales_obj__c();
        erp.Business_area__c='APAC';
       // erp.Business_region__c='Global';
        erp.ERP_logfile__c=mus.id;
        erp.Sales__c=200;
        erp.sales_currency__c='cur';
        erp.Sales_date__c=Date.Today();
        erp.Sales_import_date__c=Date.Today();
        erp.sales_import_id__c='saleid';
        System.assertEquals('APAC', erp.Business_area__c);
        insert erp;
        
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'mile';
        //objmilestone.Plan__c=objproj.id;
        //objmilestone.Project__c=objsubproj .id;
        //objmilestone.Target_Project__c=objMarketingact.id;
        objmilestone.Marketing_activity__c=objMarketingact.id;
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_ERP_Sales__c=ERPset.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        objmilestone.Target_Achieved__c=2;
        objmilestone.Target_number_outcome__c=10;        
        insert objmilestone;
        System.assertEquals('mile', objmilestone.Name);
        
        OAuthService__c  OAuth=new OAuthService__c ();
        OAuth.Name='ffbook';
        OAuth.musqot__Authorization_Type__c='Requestheader';
        OAuth.musqot__Authorization_URL__c='https://www.facebook.com/dialog/oauth';
        OAuth.musqot__Response_Type__c='token';
        OAuth.musqot__Signature_Method__c='PLAINTEXT'; 
        OAuth.musqot__Bar_color__c='#333';   
        System.assertEquals('PLAINTEXT', OAuth.musqot__Signature_Method__c);
        insert OAuth;
        
     ERPMilestoneUpdateScheduler ERPschedule = new ERPMilestoneUpdateScheduler();
        SchedulableContext sc;
        ERPschedule.execute(sc);
        ERPschedule.getStatus(objmilestone,10);   
    }
    static testMethod void ERPmilestonesupdate5(){ 
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
         objMarketingact.Name='test';
         objMarketingact.Description__c='tdescriptionest';
         objMarketingact.Status__c='completed';
         objMarketingact.musqot__ERP__c='testERP';
         objMarketingact.musqot__Social_media__c='testSocial';
         objMarketingact.musqot__CRM__c='testCRM';
         objMarketingact.Starts_date__c=Date.Today();
         objMarketingact.Ends_date__c=Date.Today();
         //objMarketingact.musqot__Activitytype__c=objActiv.id;
         insert objMarketingact;
         System.assertEquals('test', objMarketingact.name);

        musqot__ERP_Settings__c  ERPset=new musqot__ERP_Settings__c ();
        ERPset.Name='testERPEdit';
        ERPset.musqot__Selector__c='Business area';
        ERPset.musqot__erp_Chart__c='Bar charts';
        ERPset.musqot__Bar_color__c='#123344,#224466';
        ERPset.ERP_performance_type__c='Performance, project';
        //ERPset.Expression_business_area__c='APAC';
        ERPset.Expression_business_region__c='Global';
        System.assertEquals('Business area', ERPset.musqot__Selector__c);
        insert ERPset;
        
        ERP_logfile__c mus=new ERP_logfile__c();
        mus.Imported__c=true;        
        mus.Import_message__c='helloworld';
        mus.Number_of_records__c=2;
        System.assertEquals('helloworld', mus.Import_message__c);
        insert mus;
        
        ERP_sales_obj__c erp=new ERP_sales_obj__c();
        //erp.Business_area__c='APAC';
        erp.Business_region__c='Global';
        erp.ERP_logfile__c=mus.id;
        erp.Sales__c=200;
        erp.sales_currency__c='cur';
        erp.Sales_date__c=Date.Today();
        erp.Sales_import_date__c=Date.Today();
        erp.sales_import_id__c='saleid';
        insert erp;
        System.assertEquals(null, erp.Business_area__c);
        System.assertEquals('Global', erp.Business_region__c);
         
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'mile';
        //objmilestone.Plan__c=objproj.id;
        //objmilestone.Project__c=objsubproj .id;
        //objmilestone.Target_Project__c=objMarketingact.id;
        objmilestone.Marketing_activity__c=objMarketingact.id;
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_ERP_Sales__c=ERPset.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        objmilestone.Target_Achieved__c=2;
        objmilestone.Target_number_outcome__c=10;        
        insert objmilestone;
        System.assertEquals('mile', objmilestone.Name);
        
        OAuthService__c  OAuth=new OAuthService__c ();
        OAuth.Name='ffbook';
        OAuth.musqot__Authorization_Type__c='Requestheader';
        OAuth.musqot__Authorization_URL__c='https://www.facebook.com/dialog/oauth';
        OAuth.musqot__Response_Type__c='token';
        OAuth.musqot__Signature_Method__c='PLAINTEXT'; 
        OAuth.musqot__Bar_color__c='#333';   
        System.assertEquals('PLAINTEXT', OAuth.musqot__Signature_Method__c);
        insert OAuth;
        
     ERPMilestoneUpdateScheduler ERPschedule = new ERPMilestoneUpdateScheduler();
        SchedulableContext sc;
        ERPschedule.execute(sc);
        ERPschedule.getStatus(objmilestone,10);   
    }
     static testMethod void ERPmilestonesupdatetestm(){ 
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
         objMarketingact.Name='test';
         objMarketingact.Description__c='tdescriptionest';
         objMarketingact.Status__c='completed';
         objMarketingact.musqot__ERP__c='testERP';
         objMarketingact.musqot__Social_media__c='testSocial';
         objMarketingact.musqot__CRM__c='testCRM';
         objMarketingact.Starts_date__c=Date.Today();
         objMarketingact.Ends_date__c=Date.Today();
         //objMarketingact.musqot__Activitytype__c=objActiv.id;
         insert objMarketingact;
         System.assertEquals('test', objMarketingact.name);

        musqot__ERP_Settings__c  ERPset=new musqot__ERP_Settings__c ();
        ERPset.Name='testERPEdit';
        ERPset.musqot__Selector__c='Business area';
        ERPset.musqot__erp_Chart__c='Bar charts';
        ERPset.musqot__Bar_color__c='#123344,#224466';
        ERPset.ERP_performance_type__c='Performance, project';
        ERPset.Expression_business_area__c='APAC';
        //ERPset.Expression_business_region__c='Global';
        System.assertEquals('Business area', ERPset.musqot__Selector__c);
        insert ERPset;
        
        ERP_logfile__c mus=new ERP_logfile__c();
        mus.Imported__c=true;        
        mus.Import_message__c='helloworld';
        mus.Number_of_records__c=2;
        System.assertEquals('helloworld', mus.Import_message__c);
        insert mus;
        
        ERP_sales_obj__c erp=new ERP_sales_obj__c();
        erp.Business_area__c='APAC';
        erp.Business_region__c='Global';
        erp.ERP_logfile__c=mus.id;
        erp.Sales__c=200;
        erp.sales_currency__c='cur';
        erp.Sales_date__c=Date.Today();
        erp.Sales_import_date__c=Date.Today();
        erp.sales_import_id__c='saleid';
        System.assertEquals('APAC', erp.Business_area__c);
        insert erp;
        
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'mile';
        //objmilestone.Plan__c=objproj.id;
        //objmilestone.Project__c=objsubproj .id;
        //objmilestone.Target_Project__c=objMarketingact.id;
        objmilestone.Marketing_activity__c=objMarketingact.id;
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_ERP_Sales__c=ERPset.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        objmilestone.Target_Achieved__c=2;
        objmilestone.Target_number_outcome__c=10;        
        insert objmilestone;
        System.assertEquals('mile', objmilestone.Name);
        
     ERPMilestoneUpdateScheduler ERPschedule = new ERPMilestoneUpdateScheduler();
        SchedulableContext sc;
        ERPschedule.execute(sc);
        ERPschedule.getStatus(objmilestone,10);   
    }
    static testMethod void ERPmilestonesupdatetestmxx(){ 
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
         objMarketingact.Name='test';
         objMarketingact.Description__c='tdescriptionest';
         objMarketingact.Status__c='completed';
         objMarketingact.musqot__ERP__c='testERP';
         objMarketingact.musqot__Social_media__c='testSocial';
         objMarketingact.musqot__CRM__c='testCRM';
         objMarketingact.Starts_date__c=Date.Today()-1;
         objMarketingact.Ends_date__c=Date.Today()-2;
         //objMarketingact.musqot__Activitytype__c=objActiv.id;
         insert objMarketingact;
         System.assertEquals('test', objMarketingact.name);

        musqot__ERP_Settings__c  ERPset=new musqot__ERP_Settings__c ();
        ERPset.Name='testERPEdit';
        ERPset.musqot__Selector__c='Business area';
        ERPset.musqot__erp_Chart__c='Bar charts';
        ERPset.musqot__Bar_color__c='#123344,#224466';
        ERPset.ERP_performance_type__c='Performance, project';
        //ERPset.Expression_business_area__c='APAC';
        ERPset.Expression_business_region__c='Global';
        System.assertEquals('Business area', ERPset.musqot__Selector__c);
        insert ERPset;
        
        ERP_logfile__c mus=new ERP_logfile__c();
        mus.Imported__c=true;        
        mus.Import_message__c='helloworld';
        mus.Number_of_records__c=2;
        System.assertEquals('helloworld', mus.Import_message__c);
        insert mus;
        
        ERP_sales_obj__c erp=new ERP_sales_obj__c();
        erp.Business_area__c='APAC';
        erp.Business_region__c='Global';
        erp.ERP_logfile__c=mus.id;
        erp.Sales__c=200;
        erp.sales_currency__c='cur';
        erp.Sales_date__c=Date.Today();
        erp.Sales_import_date__c=Date.Today();
        erp.sales_import_id__c='saleid';
        System.assertEquals('APAC', erp.Business_area__c);
        insert erp;
        
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'mile';
        //objmilestone.Plan__c=objproj.id;
        //objmilestone.Project__c=objsubproj .id;
        //objmilestone.Target_Project__c=objMarketingact.id;
        objmilestone.Marketing_activity__c=objMarketingact.id;
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_ERP_Sales__c=ERPset.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        objmilestone.Target_Achieved__c=2;
        objmilestone.Target_number_outcome__c=10;        
        insert objmilestone;
        System.assertEquals('mile', objmilestone.Name);
        
        ERPMilestoneUpdateScheduler ERPschedule = new ERPMilestoneUpdateScheduler();
        SchedulableContext sc;
        ERPschedule.execute(sc);
        //ERPschedule.TargetNumber_Sales=0;
        ERPschedule.getStatus(objmilestone,10);   
    }
}