src/objects/ERP_sales_obj__c.object
<CustomObject>
    <fields>
        <fullName>Business_area__c</fullName>
        <label>Business area</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_region__c</fullName>
        <label>Business region</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <label>Sales</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_date__c</fullName>
        <label>Sales date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>ERP Sales Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP_sales_obj</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ERP_Settings__c.object
<CustomObject>
    <fields>
        <fullName>ERP_performance_type__c</fullName>
        <label>ERP performance type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Performance, general</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Performance, project</fullName>
            </value>
            <value>
                <fullName>Performance, marketing activity</fullName>
            </value>
            <value>
                <fullName>Milestone</fullName>
            </value>
            <value>
                <fullName>Performance, costcenter</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expression_business_area__c</fullName>
        <inlineHelpText>Here you can enter which business areas to be included for the selected milestone, one row for each area</inlineHelpText>
        <label>Expression business area</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expression_business_region__c</fullName>
        <inlineHelpText>Here you can enter which business regions to be included for the selected milestone, one row for each region</inlineHelpText>
        <label>Expression business region</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ERP Settings</label>
    <nameField>
        <label>Settings name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipLabel>Milestones (Marketing activity)</relationshipLabel>
        <relationshipName>Milestones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone_type__c</fullName>
        <label>Milestone type</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reach on time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reach delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not reach</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_ERP_Sales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target ERP Sales</label>
        <referenceTo>ERP_Settings__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_number__c</fullName>
        <label>Target_number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_number_outcome__c</fullName>
        <description>This feild will be update by trigger in ERP, CRM and Social media</description>
        <label>Target number outcome</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Targetdate__c</fullName>
        <label>Target date</label>
        <type>Date</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ERPMilestoneUpdateScheduler.cls
/*******************************************************
Class Name: ERPMilestoneUpdateScheduler
Author: Narendra K Jha        Last modified by: Narendra K Jha
Date: Oct 19, 2015            Date: Oct 21, 2015
********©2015 Musqot marketing technology Pvt ltd *******/
global class ERPMilestoneUpdateScheduler Implements Schedulable {
    public List<Milestone__c > milestoneList;
    public List<Milestone__c > updateMilestoneList=new List<Milestone__c>(); 
    public String businessRegion;
    public String businessArea;
    public Date today=system.toDay();
    public List<String> businessRegionList = new List<String> ();
    public List<String> businessAreaList = new List<String> ();
    public List<String> ebusinessRegionList = new List<String> ();
    public List<String> ebusinessAreaList = new List<String> ();
    public List<ERP_sales_obj__c> erpDataList = new List<ERP_sales_obj__c>();
    public date startDate = system.today();
    public date endDate;

    global void execute(SchedulableContext sc) {
            updateMilestoneList=new List<Milestone__c >();
            milestoneList = [SELECT Id, Plan__c, Project__c, Marketing_activity__c,
                                   Plan__r.Starts_date__c, Project__r.Starts_date__c, Marketing_activity__r.Starts_date__c,
                                   Plan__r.Ends_date__c, Project__r.Ends_date__c, Marketing_activity__r.Ends_date__c,
                                   Status__c, Targetdate__c, Target_number__c, Target_number_outcome__c,
                                   Target_ERP_sales__c,                 
                                   Target_ERP_sales__r.Expression_business_region__c,
                                   Target_ERP_sales__r.Expression_business_area__c
                             FROM  Milestone__c 
                             where Milestone_type__c=4 limit 1000];
        
        // to query out erp data
        for(Milestone__c ms : milestoneList) {
            If (ms.Marketing_activity__c <> null) {
                If (ms.Marketing_activity__r.Starts_date__c < startDate ){
                    startDate = ms.Project__r.Starts_date__c;
                }
            }
            else If (ms.Project__c <> null) {
                If (ms.Project__r.Starts_date__c < startDate){
                    startDate = ms.Project__r.Starts_date__c;
                }
            }
            else If (ms.Plan__c <> null) {
                If (ms.Plan__r.Starts_date__c < startDate){
                    startDate = ms.Plan__r.Starts_date__c;
                }
            }
        }

        erpDataList = [SELECT Id, Sales__c, Business_area__c, Business_region__c,Sales_date__c
                      FROM  ERP_sales_obj__c 
                      where Sales_date__c>=:startDate AND Sales_date__c<=:TODAY];   
            
        Decimal TargetNumber_Sales;
        
        for(Milestone__c updatemilestone : milestoneList) {
                 TargetNumber_Sales = 0;
                 if(updatemilestone.Target_ERP_sales__r.Expression_business_region__c !=null){
                     businessRegion= updatemilestone.Target_ERP_sales__r.Expression_business_region__c;
                     businessRegionList.addAll(businessRegion.split('\\s*(=>|,|\\s)\\s*')); 
                 }
                 if(updatemilestone.Target_ERP_sales__r.Expression_business_area__c !=null){
                     businessArea= updatemilestone.Target_ERP_sales__r.Expression_business_area__c;
                     businessAreaList.addAll(businessArea.split('\\s*(=>|,|\\s)\\s*')); 
                 }

                 for(ERP_sales_obj__c erpData : erpDataList) {
                           if(updatemilestone.Marketing_activity__c <> null) {
                                if (erpData.Sales_date__c >= updatemilestone.Marketing_activity__r.Starts_date__c 
                                    && erpData.Sales_date__c >= updatemilestone.Marketing_activity__r.Ends_date__c) {
                                        If(businessAreaList <> null){
                                            for(String bal : businessAreaList) {
                                                if(bal == erpData.Business_area__c) {
                                                    if(businessRegionList <> null) {
                                                        for(String brl : businessRegionList) {
                                                            if(brl == erpData.Business_region__c) {
                                                                 TargetNumber_Sales += erpData.Sales__c;
                                                            }
                                                        }
                                                    } else {
                                                        TargetNumber_Sales += erpData.Sales__c; 
                                                    }
                                                }
                                            }
                                        } else {
                                            if(businessRegionList <> null) {
                                                for(String brl : businessRegionList) {
                                                    if(brl == erpData.Business_region__c) {
                                                        TargetNumber_Sales += erpData.Sales__c;  
                                                    }
                                                }
                                            } else {
                                                TargetNumber_Sales += erpData.Sales__c;
                                            }
                                        }
                                    }
                            } 
                            else If (updatemilestone.Project__c <> null) {
                                if (erpData.Sales_date__c >= updatemilestone.Project__r.Starts_date__c 
                                    && erpData.Sales_date__c >= updatemilestone.Project__r.Ends_date__c) {
                                        If(businessAreaList <> null) {
                                            for(String bal : businessAreaList) {
                                                if(bal == erpData.Business_area__c) {
                                                    if(businessRegionList <> null) {
                                                        for(String brl : businessRegionList) {
                                                            if(brl == erpData.Business_region__c) {
                                                                 TargetNumber_Sales += erpData.Sales__c;  
                                                            }
                                                        }
                                                    } else {
                                                        TargetNumber_Sales += erpData.Sales__c;   
                                                    }
                                                }
                                            }
                                        } else {
                                            if(businessRegionList <> null) {
                                                for(String brl : businessRegionList) {
                                                    if(brl == erpData.Business_region__c) {
                                                        TargetNumber_Sales += erpData.Sales__c;  
                                                    }
                                                }
                                            } else {
                                                TargetNumber_Sales += erpData.Sales__c; 
                                            }
                                        }
                                    }
                            }
                        
                            else If (updatemilestone.Plan__c <> null) {
                                if (erpData.Sales_date__c >= updatemilestone.Plan__r.Starts_date__c 
                                    && erpData.Sales_date__c >= updatemilestone.Plan__r.Ends_date__c) {
                                       If(businessAreaList <> null) {
                                            for(String bal : businessAreaList) {
                                                if(bal == erpData.Business_area__c) {
                                                    if(businessRegionList <> null) {
                                                        for(String brl : businessRegionList) {
                                                            if(brl == erpData.Business_region__c) {
                                                                 TargetNumber_Sales += erpData.Sales__c; 
                                                            }
                                                        }
                                                    } else {
                                                        TargetNumber_Sales += erpData.Sales__c;  
                                                    }
                                                }
                                            }
                                        } else {
                                            if(businessRegionList <> null) {
                                                for(String brl : businessRegionList) {
                                                    if(brl == erpData.Business_region__c) {
                                                        TargetNumber_Sales += erpData.Sales__c;  
                                                    }
                                                }
                                            } else {
                                                TargetNumber_Sales += erpData.Sales__c; 
                                            }
                                        } 
                                    }
                            }

                         
                                   
                 }
                 
                 updatemilestone.Status__c = getStatus(updatemilestone,TargetNumber_Sales);
                 updatemilestone.Target_number_outcome__c = TargetNumber_Sales;
                
                 updateMilestoneList.add(updatemilestone);
            }
            update updateMilestoneList;
        
        
           // reschediuling the job
           try{
                List<ERP_Settings__c> erps = [SELECT Name, Id FROM ERP_Settings__c where ERP_performance_type__c = 'Milestone'];
                if(erps.size() > 0) {
                    // if milestone present
                    Date tomorrowsDate = System.today().addDays(1);
                    Integer day = tomorrowsDate.day();
                    Integer month = tomorrowsDate.month();
                    Integer year = tomorrowsDate.year();
                    String SchTimer='0 5 1 '+day+' '+month+' ? '+year;   //  next day 1:05 AM
                    System.schedule('ERPMilestoneUpdateSchedulerJob', SchTimer, new ERPMilestoneUpdateScheduler());
                }
            }catch(Exception e){
                System.debug('Exception : ' + e.getMessage());
            }
    }
    
    public String getStatus(Milestone__c updatemilestone, Decimal TargetNumber_outcome) {
        // Update Status      
        If( updatemilestone.Target_number__c > 0||updatemilestone.Target_number__c <> null){
            if(updatemilestone.Targetdate__c > toDay && updatemilestone.Target_number__c < TargetNumber_outcome){
                updatemilestone.Status__c= 'Open';                
            }
            else if(updatemilestone.Targetdate__c >= toDay && updatemilestone.Target_number__c >= TargetNumber_outcome && updatemilestone.Status__c <> 'Reach Delayed' ){
                updatemilestone.Status__c= 'Reach on time';        
            }
            else if(updatemilestone.Targetdate__c <= toDay && updatemilestone.Target_number__c >= TargetNumber_outcome){
                updatemilestone.Status__c= 'Not Reach';          
            }
            else if(updatemilestone.Targetdate__c < toDay && updatemilestone.Target_number__c < TargetNumber_outcome){
                updatemilestone.Status__c= 'Reach Delayed'; 
            }          
        }
        else{
            updatemilestone.Status__c= '?';
        }  
        return updatemilestone.Status__c;
        // status end
    }
}