src/objects/ERP_sales_obj__c.object
<CustomObject>
    <fields>
        <fullName>Business_area__c</fullName>
        <label>Business area</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_region__c</fullName>
        <label>Business region</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <label>Sales</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_date__c</fullName>
        <label>Sales date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sales_import_id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Id of the imported record</description>
        <externalId>true</externalId>
        <label>Sales import id</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ERP Sales Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP_sales_obj</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ERPSalesCotroller.cls
public with sharing class ERPSalesCotroller{
    public String getData(){
        List<ERP_sales_obj__c> erpList =  [select Sales__c,Sales_date__c,sales_import_id__c,Business_area__c,Business_region__c from ERP_sales_obj__c order by Sales_date__c, Business_region__c limit 5000];      
        //preparing JSON raw data
        List<String> jsonList = new List<String>();
        JSONGenerator jsonGen = JSON.createGenerator(true);
        jsonGen.writeStartArray();
        for(ERP_sales_obj__c erp : erpList){
            jsonGen.writeStartObject();
            jsonGen.writeDateField('date',erp.Sales_date__c);
            jsonGen.writeStringField('region',erp.Business_region__c);
            jsonGen.writeNumberField('sale',erp.Sales__c);
            jsonGen.writeStringField('area',erp.Business_area__c);    
            jsonGen.writeEndObject();     
        }
        jsonGen.writeEndArray();        
        return jsonGen.getAsString();
    }
}