src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>subproject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subproject</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>supplier__c</fullName>
        <label>Supplier</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_type__c</fullName>
        <label>User type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal user</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communities user</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <fields>
        <fullName>Plantype__c</fullName>
        <label>Plan type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_order__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effective_date__c</fullName>
        <description>Type in date the date when the cost is expected to occur. Will be use for forecasting in coming versions of Musqot.</description>
        <inlineHelpText>Type in date the date when the cost is expected to occur.</inlineHelpText>
        <label>Effective date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_order__c</fullName>
        <label>Purchase order externalid</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Purchase_order_cloesed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is checked, then you can&apos;t registry more invoice on this PO number</inlineHelpText>
        <label>Purchase order closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Purchase_order_name__c</fullName>
        <label>Purchase order number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_date__c</fullName>
        <inlineHelpText>Purchase order will be sent to supplier this date. 
To email you have in field &quot;Supplier email&quot;.
Leave &quot;Send date&quot; empty if you NOT will send.</inlineHelpText>
        <label>Send date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <label>Supplier</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_email__c</fullName>
        <label>Supplier email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Total_cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>subproject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subproject</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase order</label>
    <nameField>
        <label>Purchase order name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceEditControllerTest.cls
/*******************************************************
Class Name: InvoiceEditControllerTest
Author:Nagaraju G              Last modified by: G Janardhanreddy
Date:28/8/2014                 Date:19/03/2015
********©2013 Musqot marketing technology Pvt ltd **********/
@isTest//(seeAllData=true)
public class InvoiceEditControllerTest{
    
    static testMethod void InvoiceeditControlleratplan(){
        Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
                          Email ='newuser123@testorg.com',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', 
                          UserName='newuser1234@testorg.com',
                          ProfileId=p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        //prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
        prj.OwnerId=plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        //subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
        
        Purchase_order__c objpo = new Purchase_order__c();
        objpo.Name = 'testname';
        objpo.Purchase_order_name__c = 'test';
        objpo.Total_cost__c  = 1000;
        objpo.Description__c = 'test';
        objpo.Effective_date__c = Date.Today();
        objpo.Send_date__c = Date.Today();
        objpo.Supplier__c = 'test';
        objpo.Project__c = prj.Id;
        objpo.Purchase_order_cloesed__c=false;
        objpo.musqot__subproject__c = subprj.Id;
        objpo.musqot__Marketing_activity__c = objMarketingact.Id;
        objpo.Supplier_email__c = 'standarduser@abc.com';
        System.assertEquals('testname', objpo .Name);
        insert objpo ; 
        
        Purchase_article__c objpog = new Purchase_article__c();
        objpog.name ='testrec';
        System.assertEquals('testrec', objpog.name);
        insert objpog;
        
        Invoice__c  objInvoice=new Invoice__c();
        objInvoice.Name='testinvoice';
        objInvoice.musqot__Total_spent__c = 4000;                
        objInvoice.musqot__supplier__c='testsupplier'; 
        objInvoice.OwnerId=u2.id;    
        objInvoice.musqot__Project__c=prj.Id;
        //objInvoice.musqot__subproject__c=subprj.Id;
        //objInvoice.musqot__Marketing_activity__c=objMarketingact.Id;
        objInvoice.musqot__Purchase_orders__c=objpo.Id;
        objInvoice.musqot__Description__c='This for testing';
        System.assertEquals('testinvoice', objInvoice.Name);
        insert objInvoice;
        
        Attachment attach=new Attachment();
        attach.OwnerId = u2.Id;       
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=objInvoice.id;
        attach.contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
        System.assertEquals(objInvoice.id,attach.parentId);
        insert attach;
        
        Purchase_order__c purOrdr = [SELECT Id,Purchase_order_cloesed__c FROM Purchase_order__c where id=:objInvoice.musqot__Purchase_orders__c limit 1];  
        if(purOrdr != null){
            purOrdr.Purchase_order_cloesed__c = true;
            update purOrdr;
        }
        Invoice__c  objINV=[SELECT Name,musqot__supplier__c from Invoice__c  where id=:objInvoice.Id limit 1]; 
        objINV.Name='musqot';
        objINV.musqot__supplier__c='amazon';
        Update objINV;  
        
        test.starttest();
        ApexPages.currentPage().getParameters().put('invid', objINV.id);
        ApexPages.currentPage().getParameters().put('planid', prj.id);
       // ApexPages.currentPage().getParameters().put('prjid', subPrj.id);
        //ApexPages.currentPage().getParameters().put('markID', objMarketingact.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objINV);
        InvoiceEditController objinvedit = new InvoiceEditController(sc);
        objinvedit.subprjid= subPrj.Id;
        objinvedit.projectid= prj.Id;
        objinvedit.mrkId= objMarketingact.Id;
        Attachment att= objinvedit.attachment;
        objinvedit.subprjid= subPrj.Id;
        List<SelectOption> temp=objinvedit.PAList;
        objinvedit.attch();
        objinvedit.gotoEdit();
        objinvedit.contentType='test';
        objinvedit.Save();
        objinvedit.deleteinvoice();
        objinvedit.Cancel();
        objinvedit.DeleteAttchment();
        test.stoptest();
    }
    static testMethod void InvoiceeditControlleratproject(){
        Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
                          Email ='newuser123@testorg.com',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', 
                          UserName='newuser1234@testorg.com',
                          ProfileId=p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        //prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
        prj.OwnerId=plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress';        
        //subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
        
        Purchase_order__c objpo = new Purchase_order__c();
        objpo.Name = 'testname';
        objpo.Purchase_order_name__c = 'test';
        objpo.Total_cost__c  = 1000;
        objpo.Description__c = 'test';
        objpo.Effective_date__c = Date.Today();
        objpo.Send_date__c = Date.Today();
        objpo.Supplier__c = 'test';
        objpo.Project__c = prj.Id;
        objpo.Purchase_order_cloesed__c=false;
        objpo.musqot__subproject__c = subprj.Id;
        objpo.musqot__Marketing_activity__c = objMarketingact.Id;
        objpo.Supplier_email__c = 'standarduser@abc.com';
        System.assertEquals('testname', objpo .Name);
        insert objpo ; 
        
        Purchase_article__c objpog = new Purchase_article__c();
        objpog.name ='testrec';
        System.assertEquals('testrec', objpog.name);
        insert objpog;
        
        Invoice__c  objInvoice=new Invoice__c();
        objInvoice.Name='testinvoice';
        objInvoice.musqot__Total_spent__c = 4000;                
        objInvoice.musqot__supplier__c='testsupplier'; 
        objInvoice.OwnerId=u2.id;    
        //objInvoice.musqot__Project__c=prj.Id;
        objInvoice.musqot__subproject__c=subprj.Id;
        //objInvoice.musqot__Marketing_activity__c=objMarketingact.Id;
        objInvoice.musqot__Purchase_orders__c=objpo.Id;
        objInvoice.musqot__Description__c='This for testing';
        System.assertEquals('testinvoice', objInvoice.Name);
        insert objInvoice;
        
        Attachment attach=new Attachment();
        attach.OwnerId = u2.Id;       
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=objInvoice.id;
        attach.contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
        System.assertEquals(objInvoice.id,attach.parentId);
        insert attach;
        
        Purchase_order__c purOrdr = [SELECT Id,Purchase_order_cloesed__c FROM Purchase_order__c where id=:objInvoice.musqot__Purchase_orders__c limit 1];  
        if(purOrdr != null){
            purOrdr.Purchase_order_cloesed__c = true;
            update purOrdr;
        }
        Invoice__c  objINV=[SELECT Name,musqot__supplier__c from Invoice__c  where id=:objInvoice.Id limit 1]; 
        objINV.Name='musqot';
        objINV.musqot__supplier__c='amazon';
        Update objINV;  
        
        test.starttest();
        ApexPages.currentPage().getParameters().put('invid', objINV.id);
        ApexPages.currentPage().getParameters().put('subprjid', subPrj.id);
       // ApexPages.currentPage().getParameters().put('planid', prj.id);
       // ApexPages.currentPage().getParameters().put('markID', objMarketingact.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objINV);
        InvoiceEditController objinvedit = new InvoiceEditController(sc);
        objinvedit.subprjid= subPrj.Id;
        objinvedit.projectid= prj.Id;
        objinvedit.mrkId= objMarketingact.Id;
        Attachment att= objinvedit.attachment;
        objinvedit.subprjid= subPrj.Id;
        List<SelectOption> temp=objinvedit.PAList;
        objinvedit.attch();
        objinvedit.gotoEdit();
        objinvedit.contentType='test';
        objinvedit.Save();
        objinvedit.deleteinvoice();
        objinvedit.Cancel();
        objinvedit.DeleteAttchment();
        test.stoptest();
    }
    static testMethod void InvoiceeditControlleratmark(){
        Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
                          Email ='newuser123@testorg.com',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', 
                          UserName='newuser1234@testorg.com',
                          ProfileId=p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        //prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
        prj.OwnerId=plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        //subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
        
        Purchase_order__c objpo = new Purchase_order__c();
        objpo.Name = 'testname';
        objpo.Purchase_order_name__c = 'test';
        objpo.Total_cost__c  = 1000;
        objpo.Description__c = 'test';
        objpo.Effective_date__c = Date.Today();
        objpo.Send_date__c = Date.Today();
        objpo.Supplier__c = 'test';
        objpo.Project__c = prj.Id;
        objpo.Purchase_order_cloesed__c=false;
        objpo.musqot__subproject__c = subprj.Id;
        objpo.musqot__Marketing_activity__c = objMarketingact.Id;
        objpo.Supplier_email__c = 'standarduser@abc.com';
        System.assertEquals('testname', objpo .Name);
        insert objpo ; 
        
        Purchase_article__c objpog = new Purchase_article__c();
        objpog.name ='testrec';
        System.assertEquals('testrec', objpog.name);
        insert objpog;
        
        Invoice__c  objInvoice=new Invoice__c();
        objInvoice.Name='testinvoice';
        objInvoice.musqot__Total_spent__c = 4000;                
        objInvoice.musqot__supplier__c='testsupplier'; 
        objInvoice.OwnerId=u2.id;    
        //objInvoice.musqot__Project__c=prj.Id;
        //objInvoice.musqot__subproject__c=subprj.Id;
        objInvoice.musqot__Marketing_activity__c=objMarketingact.Id;
        objInvoice.musqot__Purchase_orders__c=objpo.Id;
        objInvoice.musqot__Description__c='This for testing';
        System.assertEquals('testinvoice', objInvoice.Name);
        insert objInvoice;
        
        Attachment attach=new Attachment();
        attach.OwnerId = u2.Id;       
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=objInvoice.id;
        attach.contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
        System.assertEquals(objInvoice.id,attach.parentId);
        insert attach;
        
        Purchase_order__c purOrdr = [SELECT Id,Purchase_order_cloesed__c FROM Purchase_order__c where id=:objInvoice.musqot__Purchase_orders__c limit 1];  
        if(purOrdr != null){
            purOrdr.Purchase_order_cloesed__c = true;
            update purOrdr;
        }
        Invoice__c  objINV=[SELECT Name,musqot__supplier__c from Invoice__c  where id=:objInvoice.Id limit 1]; 
        objINV.Name='musqot';
        objINV.musqot__supplier__c='amazon';
        Update objINV;  
        
        test.starttest();
        ApexPages.currentPage().getParameters().put('invid', objINV.id);
        ApexPages.currentPage().getParameters().put('mrkId', objMarketingact.id);
        //ApexPages.currentPage().getParameters().put('planid', prj.id);
       // ApexPages.currentPage().getParameters().put('planid', prj.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objINV);
        InvoiceEditController objinvedit = new InvoiceEditController(sc);
        objinvedit.subprjid= subPrj.Id;
        Purchase_order__c temp2=objinvedit.objPO;
        objinvedit.projectid= prj.Id;
        objinvedit.mrkId= objMarketingact.Id;
        Attachment att= objinvedit.attachment;
        objinvedit.subprjid= subPrj.Id;
        List<SelectOption> temp=objinvedit.PAList;
        objinvedit.attch();
        objinvedit.gotoEdit();
        objinvedit.contentType='test';
        objinvedit.Save();
        objinvedit.deleteinvoice();
        objinvedit.Cancel();
        objinvedit.DeleteAttchment();
        test.stoptest();
    }
  static testMethod void InvoiceeditControllersubpro(){
      	Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
                          Email ='newuser123@testorg.com',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', 
                          UserName='newuser1234@testorg.com',
                          ProfileId=p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        //prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
      	prj.OwnerId=plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        //subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Invoice__c  objInvoice=new Invoice__c();
        objInvoice.Name='testinvoice';
        objInvoice.musqot__Total_spent__c = 4000;                
        objInvoice.musqot__supplier__c='testsupplier'; 
        objInvoice.musqot__Description__c='This for testing';
        System.assertEquals('testinvoice', objInvoice.Name);
        insert objInvoice;
        
        ApexPages.currentPage().getParameters().put('prjid', subPrj.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objInvoice);
        InvoiceEditController invedit = new InvoiceEditController(sc);
        invedit.Save();       
              }
 static testMethod void InvoiceeditControllermark(){
     	Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
                          Email ='newuser123@testorg.com',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', 
                          UserName='newuser1234@testorg.com',
                          ProfileId=p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        //prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
     	prj.OwnerId=plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        //subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
                
        Invoice__c  objInvoice=new Invoice__c();
        objInvoice.Name='testinvoice';
        objInvoice.musqot__Total_spent__c = 4000;                
        objInvoice.musqot__supplier__c='testsupplier'; 
        objInvoice.musqot__Description__c='This for testing';
        System.assertEquals('testinvoice', objInvoice.Name);
        insert objInvoice;
        
        ApexPages.currentPage().getParameters().put('mrkId', objMarketingact.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objInvoice);
        InvoiceEditController invedit1 = new InvoiceEditController(sc);
        invedit1.deleteinvoice();
            }
 static testMethod void InvoiceeditControllercancel(){
     	Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
                          Email ='newuser123@testorg.com',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', 
                          UserName='newuser1234@testorg.com',
                          ProfileId=p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        //prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
     	prj.OwnerId=plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        //subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Invoice__c  objInvoice=new Invoice__c();
        objInvoice.Name='testinvoice';
        objInvoice.musqot__Total_spent__c = 4000;                
        objInvoice.musqot__supplier__c='testsupplier'; 
        objInvoice.musqot__Description__c='This for testing';
        System.assertEquals('testinvoice', objInvoice.Name);
        insert objInvoice;
        
        ApexPages.currentPage().getParameters().put('prjid', subPrj.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objInvoice);
        InvoiceEditController invedit = new InvoiceEditController(sc);
        invedit.Cancel();       
              }
 static testMethod void InvoiceeditControllercancel1(){
     	Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
                          Email ='newuser123@testorg.com',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', 
                          UserName='newuser1234@testorg.com',
                          ProfileId=p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        //prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
     	prj.OwnerId=plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        //subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
        
        Invoice__c  objInvoice=new Invoice__c();
        objInvoice.Name='testinvoice';
        objInvoice.musqot__Total_spent__c = 4000;                
        objInvoice.musqot__supplier__c='testsupplier'; 
        objInvoice.musqot__Description__c='This for testing';
        System.assertEquals('testinvoice', objInvoice.Name);
        insert objInvoice;
        
        ApexPages.currentPage().getParameters().put('mrkId', objMarketingact.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objInvoice);
        InvoiceEditController invedit = new InvoiceEditController(sc);
        invedit.Cancel();       
              }
static testMethod void InvoiceeditControllerdeleteinv(){
    	Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
                          Email ='newuser123@testorg.com',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', 
                          UserName='newuser1234@testorg.com',
                          ProfileId=p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        //prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
    	prj.OwnerId=plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        //subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Invoice__c  objInvoice=new Invoice__c();
        objInvoice.Name='testinvoice';
        objInvoice.musqot__Total_spent__c = 4000;                
        objInvoice.musqot__supplier__c='testsupplier'; 
        objInvoice.musqot__Description__c='This for testing';    
        System.assertEquals('testinvoice', objInvoice.Name);
        insert objInvoice;
        
        ApexPages.currentPage().getParameters().put('prjid', subPrj.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objInvoice);
        InvoiceEditController invedit = new InvoiceEditController(sc);
        invedit.deleteinvoice();       
              }
 static testMethod void InvoiceeditControllerdeleteinv1(){
     	Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
                          Email ='newuser123@testorg.com',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', 
                          UserName='newuser1234@testorg.com',
                          ProfileId=p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        //prj.Plantype__c= pt.Id;
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
     	prj.OwnerId=plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        //subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
                
        Invoice__c  objInvoice=new Invoice__c();
        objInvoice.Name='testinvoice';
        objInvoice.musqot__Total_spent__c = 4000;                
        objInvoice.musqot__supplier__c='testsupplier'; 
        objInvoice.musqot__Description__c='This for testing';    
        System.assertEquals('testinvoice', objInvoice.Name);
        insert objInvoice;
        
        ApexPages.currentPage().getParameters().put('mrkId', objMarketingact.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objInvoice);
        InvoiceEditController invedit = new InvoiceEditController(sc);
        invedit.deleteinvoice();       
              }
  static testMethod void Invoicesave(){
      	Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
                          Email ='newuser123@testorg.com',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', 
                          UserName='newuser1234@testorg.com',
                          ProfileId=p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Project__c prj = new Project__c ();
        prj.Name='ITC';
        prj.Ends_date__c = system.toDay().addDays(3);
        prj.Starts_date__c= system.toDay();
        prj.Status__c = 'In Progress';
      	prj.OwnerId=plm.userid__c;
        System.assertEquals('ITC', prj.name);         
        insert prj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = prj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
        
        Invoice__c  objInvoice=new Invoice__c();       
        objInvoice.Name='testinvoice';             
        objInvoice.musqot__supplier__c='testsupplier';        
        objInvoice.musqot__Total_spent__c = 4000;
        System.assertEquals('testinvoice', objInvoice.Name);
        insert objInvoice;
        
        PageReference pageRef = Page.ProjectDetails;
        Test.setCurrentPage(pageRef);
        String tabId = System.currentPageReference().getParameters().get('tabId');
        ApexPages.currentPage().getParameters().put('projectid', prj.id);
        ApexPages.currentPage().getParameters().put('markID', objMarketingact.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objInvoice);
        InvoiceEditController objinvcont = new InvoiceEditController(sc);
        objinvcont.Save();
      }
}