src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/plantype__c.object
<CustomObject>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <fields>
        <fullName>Plantype__c</fullName>
        <label>Plan type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_article__c.object
<CustomObject>
    <description>Type of product the supplier selling</description>
    <label>Purchase article</label>
    <nameField>
        <label>Purchase article</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_order__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effective_date__c</fullName>
        <description>Type in date the date when the cost is expected to occur. Will be use for forecasting in coming versions of Musqot.</description>
        <inlineHelpText>Type in date the date when the cost is expected to occur.</inlineHelpText>
        <label>Effective date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_article__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase article</label>
        <referenceTo>Purchase_article__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_order__c</fullName>
        <label>Purchase order externalid</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Purchase_order_cloesed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is checked, then you can&apos;t registry more invoice on this PO number</inlineHelpText>
        <label>Purchase order closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Purchase_order_name__c</fullName>
        <label>Purchase order number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_order_send__c</fullName>
        <description>The date purchase send to supplier</description>
        <inlineHelpText>The date purchase send to supplier</inlineHelpText>
        <label>Purchase order send</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_date__c</fullName>
        <inlineHelpText>Purchase order will be sent to supplier this date. 
To email you have in field &quot;Supplier email&quot;.
Leave &quot;Send date&quot; empty if you NOT will send.</inlineHelpText>
        <label>Send date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <label>Supplier</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_email__c</fullName>
        <label>Supplier email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Total_cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>subproject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subproject</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>total_Invoice_cost__c</fullName>
        <label>Invoice cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase order</label>
    <nameField>
        <label>Purchase order name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PurchaseorderEditControllerTest.cls
/*******************************************************
Class Name: PurchaseorderEditControllerTest
Author:Nagaraju G        Last modified by:Raju
Date: 28/8/2014          Date: 18/2/2015 
********©2013 Musqot marketing technology Pvt ltd *******/

@isTest(seeAllData=true)
public class PurchaseorderEditControllerTest{
    static testMethod void PurchaseorderEdittest(){  
      Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User objUs =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert objUs ; 
    Project__c prj = new Project__c ();
         prj.Name='ITC';
         //prj.Plantype__c= pt.Id;
         prj.Ends_date__c = system.toDay().addDays(3);
         prj.Starts_date__c= system.toDay();
         prj.Status__c = 'In Progress';
         System.assertEquals('ITC', prj.name);         
         insert prj;
         
        
    Subproject__c subPrj = new Subproject__c();         
         subPrj.Name='ITC Project';
         subPrj.Parent_project__c = prj.Id;
         subPrj.Ends_date__c = system.toDay().addDays(3);
         subPrj.Starts_date__c= system.toDay();
         subPrj.Status__c = 'In Progress'; 
         //subPrj.Project_type__c = prjType.Id;
         System.assertEquals('ITC Project', subPrj.name);     
         insert subPrj;
                     
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
       
        
      Purchase_order__c objpurchase=new Purchase_order__c ();   
        objpurchase.Name='testpurchaces';
        objpurchase.Ownerid=objUs.id;
        objpurchase.musqot__Purchase_order_name__c='testperching';
        //objpurchase.musqot__Project__c=prj.Id;
        objpurchase.musqot__subproject__c=subPrj.Id;
        objpurchase.musqot__Supplier_email__c='test@gmail.com';
        objpurchase.musqot__Total_cost__c=3000;
        objpurchase.musqot__Supplier__c='testsuppilor';
        objpurchase.musqot__Send_date__c=system.today();
        objpurchase.musqot__Effective_date__c=system.today();
        objpurchase.musqot__Purchase_order_cloesed__c = true;
        objpurchase.musqot__total_Invoice_cost__c=10;
        
        //decimal poOld=1000;
        //decimal maxPO2=500;
         if(objpurchase.Send_date__c==system.today())
             {
                 objpurchase.Purchase_order_send__c =objpurchase.Send_date__c;
                
             }
       
        System.assertEquals('testpurchaces', objpurchase.name);
       
        insert objpurchase;
         
        Purchase_article__c objpoarticlce = new Purchase_article__c();
        objpoarticlce .Name = 'test';
        System.assertEquals('test', objpoarticlce .Name );
        insert objpoarticlce;
        
        Attachment attach=new Attachment();       
        attach.Name='Unit Test Attachment';
        attach.OwnerId=objpurchase.OwnerId;
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=objpurchase.id;
        attach.contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
        System.assertEquals(objpurchase.id,attach.parentId);
        insert attach;
       
        id purid = ApexPages.currentPage().getParameters().get('purid');
        String tabId = System.currentPageReference().getParameters().get('tabId');
        ApexPages.currentPage().getParameters().put('pursid', objpurchase.id);
        ApexPages.currentPage().getParameters().put('prjId',subPrj.id);
        ApexPages.currentPage().getParameters().put('maxpo','2000');
        PageReference pageRef = Page.Purchaseorderpage;
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.standardController(objpurchase); 
        Test.startTest();
        PurchaseorderEditController objpurEdit=new PurchaseorderEditController(sc);
        List<SelectOption> temp = objpurEdit.PAList;
        Attachment temp4=objpurEdit.attachment;
        //try{
        objpurEdit.maxPO='2000';
        objpurEdit.poOld=3000;
        objpurEdit.Save();
        try{
        objpurEdit.DeleteAttchment();
       
        }catch(Exception e){}
        objpurEdit.redirectToTemplate();
        
        objpurEdit.getRedirectToTemplate();
        
        objpurEdit.deleteorders();
        objpurEdit.Cancel();  
        objpurEdit.gotoInfoMode();
        objpurEdit.gotoEditMode();
        objpurEdit.contentType='test';
        //objpurEdit.fileType='test';
        objpurEdit.showbutton=true;
      }
            
    static testMethod void PurchaseorderEdittest1(){ 
     Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User objUs =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert objUs ;   
    Project__c prj = new Project__c ();
         prj.Name='ITC';
         //prj.Plantype__c= pt.Id;
         prj.Ends_date__c = system.toDay().addDays(3);
         prj.Starts_date__c= system.toDay();
         prj.Status__c = 'In Progress';
         System.assertEquals('ITC', prj.name);         
         insert prj;
        
    Subproject__c subPrj = new Subproject__c();         
         subPrj.Name='ITC Project';
         subPrj.Parent_project__c = prj.Id;
         subPrj.Ends_date__c = system.toDay().addDays(3);
         subPrj.Starts_date__c= system.toDay();
         subPrj.Status__c = 'In Progress'; 
         //subPrj.Project_type__c = prjType.Id;
         System.assertEquals('ITC Project', subPrj.name);     
         insert subPrj;
                     
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
      Purchase_order__c objpurchase=new Purchase_order__c ();   
        objpurchase.Name='testpurchaces';
        objpurchase.musqot__Purchase_order_name__c='testperching';
        objpurchase.musqot__Project__c=prj.Id;
        objpurchase.musqot__Supplier_email__c='test@gmail.com';
        //objpurchase.musqot__subproject__c=subPrj.Id;
        //objpurchase.musqot__Total_cost__c=1000;
        objpurchase.Ownerid=objUs.id;
        objpurchase.musqot__Send_date__c=system.today();
        objpurchase.musqot__Effective_date__c=system.today();
        objpurchase.musqot__Purchase_order_cloesed__c = true;
        objpurchase.musqot__total_Invoice_cost__c=10;
        decimal poOld=100;
        decimal maxPO2=500;
        objpurchase.musqot__Supplier__c='testsuppilor';
         if(objpurchase.Send_date__c==system.today())
             {
                 objpurchase.Purchase_order_send__c =objpurchase.Send_date__c;
                
             }
       
        System.assertEquals('testpurchaces', objpurchase.name);
        
        insert objpurchase;
        
        Purchase_article__c objpoarticlce = new Purchase_article__c();
        objpoarticlce .Name = 'test';
        System.assertEquals('test', objpoarticlce .Name );
        insert objpoarticlce ;
        
        Attachment attach=new Attachment();       
        attach.Name='Unit Test Attachment';
        attach.OwnerId=objpurchase.OwnerId;
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=objpurchase.id;
        attach.contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
        System.assertEquals(objpurchase.id,attach.parentId);
        insert attach;
         //objpurchase.musqot__Marketing_activity__c=objMarketingact.Id;
      id purid = ApexPages.currentPage().getParameters().get('purid');
      String tabId = System.currentPageReference().getParameters().get('tabId');
      ApexPages.currentPage().getParameters().put('planid', prj.id);
      ApexPages.currentPage().getParameters().put('maxPOID', prj.id);
      ApexPages.currentPage().getParameters().put('purid', objpurchase.id);
      ApexPages.StandardController sc = new ApexPages.standardController(objpurchase);
      test.startTest();
   
        PurchaseorderEditController objpurEdit=new PurchaseorderEditController(sc);
        List<SelectOption> temp = objpurEdit.PAList;
        objpurEdit.maxPO='2000';
        objpurEdit.poOld=3000;
        try{
           objpurEdit.Save();
           objpurEdit.DeleteAttchment();
        }catch(Exception e){}
        objpurEdit.redirectToTemplate();
        //objpurEdit.DeleteAttchment();
        objpurEdit.getRedirectToTemplate();
        objpurEdit.deleteorders();
        objpurEdit.Cancel();  
        objpurEdit.gotoInfoMode();
        objpurEdit.gotoEditMode();
        objpurEdit.contentType='test';
        //objpurEdit.fileType='test';
        objpurEdit.showbutton=true;
       
          }
        static testMethod void PurchaseorderEdittest2(){  
         Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User objUs =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert objUs ;  
         Project__c prj = new Project__c ();
         prj.Name='ITC';
         //prj.Plantype__c= pt.Id;
         prj.Ends_date__c = system.toDay().addDays(3);
         prj.Starts_date__c= system.toDay();
         prj.Status__c = 'In Progress';
         System.assertEquals('ITC', prj.name);         
         insert prj;
       Subproject__c subPrj = new Subproject__c();         
         subPrj.Name='ITC Project';
         subPrj.Parent_project__c = prj.Id;
         subPrj.Ends_date__c = system.toDay().addDays(3);
         subPrj.Starts_date__c= system.toDay();
         subPrj.Status__c = 'In Progress'; 
         //subPrj.Project_type__c = prjType.Id;
         System.assertEquals('ITC Project', subPrj.name);     
         insert subPrj;
                     
       Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
      Purchase_order__c objpurchase=new Purchase_order__c ();   
        objpurchase.Name='testpurchaces';
        objpurchase.Ownerid=objUs.id;
        objpurchase.musqot__Purchase_order_name__c='testperching';
       // objpurchase.musqot__Project__c=prj.Id;
        objpurchase.musqot__subproject__c=subPrj.Id;
       // objpurchase.musqot__Marketing_activity__c=objMarketingact.Id;
        objpurchase.musqot__Supplier_email__c='test@gmail.com';
        objpurchase.musqot__Total_cost__c=100;
        objpurchase.musqot__Send_date__c=system.today();
        objpurchase.musqot__Effective_date__c=system.today();
        objpurchase.musqot__Purchase_order_cloesed__c = true;
        objpurchase.musqot__total_Invoice_cost__c=10;
        decimal poOld=100;
        decimal maxPO2=500;
        objpurchase.musqot__Supplier__c='testsuppilor';
         if(objpurchase.Send_date__c==system.today())
             {
                 objpurchase.Purchase_order_send__c =objpurchase.Send_date__c;
                
             }
       
        System.assertEquals('testpurchaces', objpurchase.name);
       
        insert objpurchase;
       
       Purchase_article__c objpoarticlce = new Purchase_article__c();
        objpoarticlce .Name = 'test';
        System.assertEquals('test', objpoarticlce .Name );
        insert objpoarticlce ;
        
        Attachment attach=new Attachment();       
        attach.Name='Unit Test Attachment';
        attach.OwnerId=objpurchase.OwnerId;
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=objpurchase.id;
        attach.contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
        System.assertEquals(objpurchase.id,attach.parentId);
        insert attach;
        
        String tabId = System.currentPageReference().getParameters().get('tabId');
       ApexPages.currentPage().getParameters().put('prjId', subPrj.id);
       ApexPages.currentPage().getParameters().put('maxPOID', subPrj.id);
       ApexPages.currentPage().getParameters().put('purid', objpurchase.id);
       ApexPages.StandardController sc = new ApexPages.standardController(objpurchase);
       test.startTest();
   
        PurchaseorderEditController objpurEdit=new PurchaseorderEditController(sc);
        List<SelectOption> temp = objpurEdit.PAList;
        objpurEdit.maxPO='2000';
        objpurEdit.poOld=3000;
        objpurEdit.Save();
         try{
        objpurEdit.DeleteAttchment();
        }catch(Exception e){}
        objpurEdit.redirectToTemplate();
        //objpurEdit.DeleteAttchment();
        objpurEdit.getRedirectToTemplate();
        objpurEdit.deleteorders();
        objpurEdit.Cancel();  
        objpurEdit.gotoInfoMode();
        objpurEdit.gotoEditMode();
        objpurEdit.contentType='test';
        //objpurEdit.fileType='test';
        objpurEdit.showbutton=true;
       
         }
    static testMethod void PurchaseorderEdittest3(){ 
     Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User objUs =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert objUs ;   
    Project__c prj = new Project__c ();
         prj.Name='ITC';
         //prj.Plantype__c= pt.Id;
         prj.Ends_date__c = system.toDay().addDays(3);
         prj.Starts_date__c= system.toDay();
         prj.Status__c = 'In Progress';
         System.assertEquals('ITC', prj.name);         
         insert prj;
         
         
    Subproject__c subPrj = new Subproject__c();         
         subPrj.Name='ITC Project';
         subPrj.Parent_project__c = prj.Id;
         subPrj.Ends_date__c = system.toDay().addDays(3);
         subPrj.Starts_date__c= system.toDay();
         subPrj.Status__c = 'In Progress'; 
         System.assertEquals('ITC Project', subPrj.name);     
         insert subPrj;
                     
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
       
        
      Purchase_order__c objpurchase=new Purchase_order__c ();   
        objpurchase.Name='testpurchaces';
        objpurchase.Ownerid=objUs.id;
        objpurchase.musqot__Purchase_order_name__c='testperching';
        //objpurchase.musqot__Project__c=prj.Id;
        //objpurchase.musqot__subproject__c=subPrj.Id;
        objpurchase.musqot__Marketing_activity__c=objMarketingact.Id;
        objpurchase.musqot__Supplier_email__c='test@gmail.com';
        objpurchase.musqot__Total_cost__c=100;
        objpurchase.musqot__Supplier__c='testsuppilor';
        objpurchase.musqot__Send_date__c=system.today();
        objpurchase.musqot__Effective_date__c=system.today();
        objpurchase.musqot__Purchase_order_cloesed__c = true;
        objpurchase.musqot__total_Invoice_cost__c=10;
        decimal poOld=100;
        decimal maxPO2=500;
         if(objpurchase.Send_date__c==system.today())
             {
                 objpurchase.Purchase_order_send__c =objpurchase.Send_date__c;
                
             }
       
        System.assertEquals('testpurchaces', objpurchase.name);
           insert objpurchase;
       
       Purchase_article__c objpoarticlce = new Purchase_article__c();
        objpoarticlce .Name = 'test';
        System.assertEquals('test', objpoarticlce .Name );
        insert objpoarticlce ;
        
        Attachment attach=new Attachment();       
        attach.Name='Unit Test Attachment';
        attach.OwnerId=objpurchase.OwnerId;
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=objpurchase.id;
        attach.contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
        System.assertEquals(objpurchase.id,attach.parentId);
        insert attach;
      String tabId = System.currentPageReference().getParameters().get('tabId');                    
      ApexPages.currentPage().getParameters().put('markID', objMarketingact.id);
      ApexPages.currentPage().getParameters().put('maxPOID', objMarketingact.id);
    ApexPages.currentPage().getParameters().put('purid', objpurchase.id);
    ApexPages.StandardController sc = new ApexPages.standardController(objpurchase);
    test.startTest();
   
        PurchaseorderEditController objpurEdit=new PurchaseorderEditController(sc);
        List<SelectOption> temp = objpurEdit.PAList;
        try{
        objpurEdit.Save();
        objpurEdit.DeleteAttchment();
        }catch(Exception e){}
        objpurEdit.redirectToTemplate();
        objpurEdit.DeleteAttchment();
        objpurEdit.getRedirectToTemplate();
        objpurEdit.deleteorders();
        objpurEdit.Cancel();  
        objpurEdit.gotoInfoMode();
        objpurEdit.gotoEditMode();
        objpurEdit.contentType='test';
        //objpurEdit.fileType='test';
        objpurEdit.showbutton=true;                           
      }
 static testMethod void posave(){
    Project__c objproj = new Project__c();
    objproj .name = 'testname';
    objproj .Starts_date__c = System.now().date();
    objproj .Ends_date__c =  System.now().date(); 
    objproj .Description__c = 'sampdesc';
    System.assertEquals('testname', objproj .name);
    insert objproj ;
    
    Subproject__c objsp = new Subproject__c ();
    objsp .name = 'testname';            
    objsp .Description__c = 'sampdesc';
    objsp .Project_del__c = objsp.Id;
    objsp .Starts_date__c =  System.now().date();
    objsp .Ends_date__c =  System.now().date();   
    System.assertEquals('testname', objsp .name);
    insert objsp ;
    
      
      Purchase_order__c objpurchase=new Purchase_order__c ();   
        objpurchase.Name='testpurchaces';        
        objpurchase.musqot__Purchase_order_name__c='testperching';               
        objpurchase.musqot__Supplier_email__c='test@gmail.com';
        objpurchase.musqot__Total_cost__c=100;
        objpurchase.musqot__Supplier__c='testsuppilor';
        objpurchase.musqot__Send_date__c=system.today();
        objpurchase.musqot__Effective_date__c=system.today();
        objpurchase.musqot__Purchase_order_cloesed__c = true;
        objpurchase.musqot__total_Invoice_cost__c=10;
        decimal poOld=100;
        decimal maxPO2=500;                 
        insert objpurchase;
        System.assertEquals('testpurchaces', objpurchase.name);
    
        ApexPages.currentPage().getParameters().put('projectid', objproj .id);
        ApexPages.StandardController sc = new ApexPages.standardController(objpurchase);            
        PurchaseorderEditController poed=new PurchaseorderEditController(sc);
        musqot__Purchase_order__c purs = [Select Id,ownerid, Name, Description__c,Supplier__c,Supplier_email__c, Total_cost__c,Project__c,subproject__c,Marketing_activity__c, Send_date__c, Purchase_order_name__c, total_Invoice_cost__c,Effective_date__c, Purchase_article__c, Purchase_order_cloesed__c,Purchase_order_send__c 
        FROM Purchase_order__c LIMIT 1]; 
        objpurchase.Send_date__c=system.today();
        update objpurchase;
        try{   
        poed.save();
        }catch(exception e){}      
         }
    
 }