src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/plantype__c.object
<CustomObject>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_article__c.object
<CustomObject>
    <description>Type of product the supplier selling</description>
    <label>Purchase article</label>
    <nameField>
        <label>Purchase article</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_order__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_article__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase article</label>
        <referenceTo>Purchase_article__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_order__c</fullName>
        <label>Purchase order externalid</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Send_date__c</fullName>
        <inlineHelpText>Purchase order will be sent to supplier this date. 
To email you have in field &quot;Supplier email&quot;.
Leave &quot;Send date&quot; empty if you NOT will send.</inlineHelpText>
        <label>Send date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>subproject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subproject</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase order</label>
    <nameField>
        <label>Purchase order name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_order_setting__c.object
<CustomObject>
    <fields>
        <fullName>PO_Lastnumber__c</fullName>
        <label>Last used number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PO_Prefix__c</fullName>
        <inlineHelpText>Prefix for purchase order  when you create in Musqot</inlineHelpText>
        <label>PO Prefix</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Startnumber__c</fullName>
        <label>Start number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase order setting</label>
    <nameField>
        <label>Purchase order setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase order settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PurchaseorderContrllorTest.cls
/******************************************************************
Class Name: PurchaseorderContrllorTest
Author:Nagaraju G             Last modified by: chaithanya daggumati
Date: 28/8/2014               Date: 18/2/2015 
********©2013 Musqot marketing technology Pvt ltd ******************/

@isTest(seeAllData=true)
public class PurchaseorderContrllorTest{
   static testMethod void Purchaseordertest(){ 
        Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
        User u2 =new User( Alias = 'newUser1' ,
        Email ='newuser123@testorg.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'Testing',
        LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', 
        UserName='newuser1234@testorg.com',
        ProfileId=p.Id,
        TimeZoneSidKey = 'America/Los_Angeles');
        insert u2;
    Contact c = new Contact(firstname='test',lastname='test',email='no@email.com');
    insert c;  
   Project__c prj = new Project__c ();
         prj.Name='ITC';
         prj.Plantype__c=  prj.Id;
         prj.Ends_date__c = system.toDay().addDays(3);
         prj.Starts_date__c= system.toDay();
         prj.Status__c = 'In Progress';
         System.assertEquals('ITC', prj.name);         
         insert prj;
         
    Subproject__c subPrj = new Subproject__c();         
         subPrj.Name='ITC Project';
         subPrj.Parent_project__c = prj.Id;
         subPrj.Ends_date__c = system.toDay().addDays(3);
         subPrj.Starts_date__c= system.toDay();
         subPrj.Status__c = 'In Progress'; 
         subPrj.Parent_project__c = prj.Id;
         //subPrj.Project_del__c = prj.Id;         
         System.assertEquals('ITC Project', subPrj.name);     
         insert subPrj;
                     
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
        
      Purchase_order__c objpurchase=new Purchase_order__c ();   
        objpurchase.Name='testpurchaces';
        objpurchase.musqot__Purchase_order_name__c='testperchage';
        objpurchase.musqot__Project__c=prj.Id;
        objpurchase.musqot__subproject__c=subPrj.Id;
        objpurchase.musqot__Total_cost__c=100;
        objpurchase.musqot__Supplier__c='testsuppilor';
        System.assertEquals('testsuppilor', objpurchase.musqot__Supplier__c);
        insert objpurchase;
        
        Purchase_order_setting__c objpoorderset = new Purchase_order_setting__c();
        objpoorderset .musqot__PO_Startnumber__c = 10;
        objpoorderset.musqot__PO_Lastnumber__c =15;
        objpoorderset.musqot__PO_Prefix__c = 'test';
        objpoorderset.musqot__PO_Autoprefix__c = 'test';
        objpoorderset.musqot__PO_External__c = 'test';
        System.assertEquals(10, objpoorderset .musqot__PO_Startnumber__c);
        insert objpoorderset ;
        
        Attachment attachment=new Attachment();
        attachment.OwnerId = u2.Id;
        attachment.OwnerId = userinfo.getuserid();
        attachment.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attachment.body=bodyBlob;
        attachment.ParentId = objpurchase.Id ;
        insert attachment;
        if(objpurchase.Send_date__c ==System.today() && objpurchase.musqot__Supplier_email__c != null && objpurchase.musqot__Supplier_email__c != ''){ 
        Purchase_order__c  purchOrdr = [SELECT Id,musqot__Purchase_order_name__c,musqot__Supplier_email__c,Name,musqot__Total_cost__c,musqot__Description__c, OwnerId FROM Purchase_order__c WHERE Id = :objpurchase.Id];
          EmailTemplate template = [SELECT Id, name,Subject, HtmlValue, Body FROM EmailTemplate WHERE name= 'Purchaseorder'];  
           Contact cnt = new Contact();
            cnt.LastName = 'Supplier';
            cnt.Email = purchOrdr .musqot__Supplier_email__c;
            insert cnt;
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setWhatId(purchOrdr .Id);
            mail.setTargetObjectId(cnt.Id);
            mail.setTemplateId(template.Id);
            mail.saveAsActivity = false;
            
              if(attachment.body<>null){
                //Set email file attachments
                List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
                // Add to attachment file list
                Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
                efa.setFileName(attachment.Name);
                efa.setBody(attachment.Body);
                efa.setContentType(attachment.ContentType);
                fileAttachments.add(efa);
                mail.setFileAttachments(fileAttachments);
            }
            //Send email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
            delete cnt;           
        }       
          
           
        Purchase_article__c objpoarticlce = new Purchase_article__c();
        objpoarticlce .Name = 'test';
        System.assertEquals('test', objpoarticlce .Name );
        insert objpoarticlce ;
        
        ApexPages.currentPage().getParameters().put('id', objpurchase.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objpurchase); 
        test.startTest();
        PurchaseorderContrllor objpur=new PurchaseorderContrllor (sc);
        List<SelectOption> temp = objpur.PAList;
        try{
        objpur.insertOrders();
        objpur.cancel();   
         } catch(exception e){}         
        try{
        objpur.sendEmail(objpurchase, attachment);
        }catch(exception e){}
        objpur.contenttype='test';
        objpur.a1=0.1;
        objpur.a2='test';
        objpur.a3='test';
        test.stoptest();
               }
     static  testMethod void Purchaseordertest1(){   
   Project__c prj = new Project__c ();
         prj.Name='ITC';
         prj.Plantype__c=  prj.Id;
         prj.Ends_date__c = system.toDay().addDays(3);
         prj.Starts_date__c= system.toDay();
         prj.Status__c = 'In Progress';
         System.assertEquals('ITC', prj.name);         
         insert prj;
         
    Subproject__c subPrj = new Subproject__c();         
         subPrj.Name='ITC Project';
         subPrj.Parent_project__c = prj.Id;
         subPrj.Ends_date__c = system.toDay().addDays(3);
         subPrj.Starts_date__c= system.toDay();
         subPrj.Status__c = 'In Progress'; 
         subPrj.Parent_project__c = prj.Id;
         //subPrj.Project_del__c = prj.Id;         
         System.assertEquals('ITC Project', subPrj.name);     
         insert subPrj;
                     
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
        
      Purchase_order__c objpurchase=new Purchase_order__c ();   
        objpurchase.Name='testpurchaces';
        objpurchase.musqot__Purchase_order_name__c='testperchage';
        objpurchase.musqot__Project__c=prj.Id;
        objpurchase.musqot__subproject__c=subPrj.Id;
        objpurchase.musqot__Total_cost__c=100;
        objpurchase.musqot__Supplier__c='testsuppilor';
        System.assertEquals('testsuppilor', objpurchase.musqot__Supplier__c);
        insert objpurchase;
        
        Purchase_order_setting__c objpoorderset = new Purchase_order_setting__c();
        objpoorderset .musqot__PO_Startnumber__c = 10;
        objpoorderset.musqot__PO_Lastnumber__c =15;
        objpoorderset.musqot__PO_Prefix__c = 'test';
        objpoorderset.musqot__PO_Autoprefix__c = 'test';
        objpoorderset.musqot__PO_External__c = 'test';
        System.assertEquals(10, objpoorderset .musqot__PO_Startnumber__c);
        insert objpoorderset ;
        
        Attachment attachment=new Attachment();
        attachment.OwnerId = userinfo.getuserid();
        attachment.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attachment.body=bodyBlob;
        attachment.ParentId = objpurchase.Id ;
        insert attachment;
         if(objpurchase.Send_date__c ==System.today() && objpurchase.musqot__Supplier_email__c != null && objpurchase.musqot__Supplier_email__c != ''){ 
        Purchase_order__c  purchOrdr = [SELECT Id,musqot__Purchase_order_name__c,musqot__Supplier_email__c,Name,musqot__Total_cost__c,musqot__Description__c, OwnerId FROM Purchase_order__c WHERE Id = :objpurchase.Id];
          EmailTemplate template = [SELECT Id, name,Subject, HtmlValue, Body FROM EmailTemplate WHERE name= 'Purchaseorder'];  
           Contact cnt = new Contact();
            cnt.LastName = 'Supplier';
            cnt.Email = purchOrdr .musqot__Supplier_email__c;
            insert cnt;
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
           // String[] toAddresses = new String[]{orders.musqot__Supplier_email__c};
            //system.debug('toadresses--->'+toAddresses);
            //mail.setToAddresses(toAddresses);
            mail.setWhatId(purchOrdr .Id);
            mail.setTargetObjectId(cnt.Id);
            mail.setTemplateId(template.Id);
            mail.saveAsActivity = false;
            
              if(attachment.body<>null){
                //Set email file attachments
                List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
                // Add to attachment file list
                Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
                efa.setFileName(attachment.Name);
                efa.setBody(attachment.Body);
                efa.setContentType(attachment.ContentType);
                fileAttachments.add(efa);
                mail.setFileAttachments(fileAttachments);
            }
            //Send email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
            delete cnt;           
        }       
          
           
        Purchase_article__c objpoarticlce = new Purchase_article__c();
        objpoarticlce .Name = 'test';
        System.assertEquals('test', objpoarticlce .Name );
        insert objpoarticlce ;
        
        ApexPages.currentPage().getParameters().put('planid', prj.id);
         String tabId = System.currentPageReference().getParameters().get('tabId');
          
        ApexPages.StandardController sc = new ApexPages.standardController(objpurchase); 
        test.startTest();
        PurchaseorderContrllor objpur=new PurchaseorderContrllor (sc);
        List<SelectOption> temp = objpur.PAList;
        objpur.insertOrders();
        objpur.cancel();
        try{
        objpur.sendEmail(objpurchase, attachment);
        }catch(exception e){}
        objpur.contenttype='test';
        objpur.a1=0.1;
        objpur.a2='test';
        objpur.a3='test'; 
        //objpur.getRedirectToTemplate();
        //objpur.redirectToTemplate(); 
        test.stoptest();  
               }
     static testMethod void Purchaseordertest2(){   
   Project__c prj = new Project__c ();
         prj.Name='ITC';
         prj.Plantype__c=  prj.Id;
         prj.Ends_date__c = system.toDay().addDays(3);
         prj.Starts_date__c= system.toDay();
         prj.Status__c = 'In Progress';
         System.assertEquals('ITC', prj.name);         
         insert prj;
         
    Subproject__c subPrj = new Subproject__c();         
         subPrj.Name='ITC Project';
         subPrj.Parent_project__c = prj.Id;
         subPrj.Ends_date__c = system.toDay().addDays(3);
         subPrj.Starts_date__c= system.toDay();
         subPrj.Status__c = 'In Progress'; 
         subPrj.Parent_project__c = prj.Id;
         //subPrj.Project_del__c = prj.Id;         
         System.assertEquals('ITC Project', subPrj.name);     
         insert subPrj;
                     
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
        
      Purchase_order__c objpurchase=new Purchase_order__c ();   
        objpurchase.Name='testpurchaces';
        objpurchase.musqot__Purchase_order_name__c='testperchage';
        objpurchase.musqot__Project__c=prj.Id;
        objpurchase.musqot__subproject__c=subPrj.Id;
        objpurchase.musqot__Total_cost__c=100;
        objpurchase.musqot__Supplier__c='testsuppilor';
        System.assertEquals('testsuppilor', objpurchase.musqot__Supplier__c);
        insert objpurchase;
        
        Purchase_order_setting__c objpoorderset = new Purchase_order_setting__c();
        objpoorderset .musqot__PO_Startnumber__c = 10;
        objpoorderset.musqot__PO_Lastnumber__c =15;
        objpoorderset.musqot__PO_Prefix__c = 'test';
        objpoorderset.musqot__PO_Autoprefix__c = 'test';
        objpoorderset.musqot__PO_External__c = 'test';
        System.assertEquals(10, objpoorderset .musqot__PO_Startnumber__c);
        insert objpoorderset ;
        
        Attachment attachment=new Attachment();
        attachment.OwnerId = userinfo.getuserid();
        attachment.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attachment.body=bodyBlob;
        attachment.ParentId = objpurchase.Id ;
        insert attachment;
         if(objpurchase.Send_date__c ==System.today() && objpurchase.musqot__Supplier_email__c != null && objpurchase.musqot__Supplier_email__c != ''){ 
        Purchase_order__c  purchOrdr = [SELECT Id,musqot__Purchase_order_name__c,musqot__Supplier_email__c,Name,musqot__Total_cost__c,musqot__Description__c, OwnerId FROM Purchase_order__c WHERE Id = :objpurchase.Id];
          EmailTemplate template = [SELECT Id, name,Subject, HtmlValue, Body FROM EmailTemplate WHERE name= 'Purchaseorder'];  
           Contact cnt = new Contact();
            cnt.LastName = 'Supplier';
            cnt.Email = purchOrdr .musqot__Supplier_email__c;
            insert cnt;
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
           // String[] toAddresses = new String[]{orders.musqot__Supplier_email__c};
            //system.debug('toadresses--->'+toAddresses);
            //mail.setToAddresses(toAddresses);
            mail.setWhatId(purchOrdr .Id);
            mail.setTargetObjectId(cnt.Id);
            mail.setTemplateId(template.Id);
            mail.saveAsActivity = false;
            
              if(attachment.body<>null){
                //Set email file attachments
                List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
                // Add to attachment file list
                Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
                efa.setFileName(attachment.Name);
                efa.setBody(attachment.Body);
                efa.setContentType(attachment.ContentType);
                fileAttachments.add(efa);
                mail.setFileAttachments(fileAttachments);
            }
            //Send email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
            delete cnt;           
        }       
          
           
        Purchase_article__c objpoarticlce = new Purchase_article__c();
        objpoarticlce .Name = 'test';
        System.assertEquals('test', objpoarticlce .Name );
        insert objpoarticlce ;
        
        ApexPages.currentPage().getParameters().put('prjId', subPrj.id);
         String tabId = System.currentPageReference().getParameters().get('tabId');  
        ApexPages.StandardController sc = new ApexPages.standardController(objpurchase); 
        test.startTest();
        PurchaseorderContrllor objpur=new PurchaseorderContrllor (sc);
        List<SelectOption> temp = objpur.PAList;
        objpur.insertOrders();
        objpur.cancel();
         try{
        objpur.sendEmail(objpurchase, attachment);
        }catch(exception e){}
        //objpur.getRedirectToTemplate();
        //objpur.redirectToTemplate(); 
        test.stoptest();  
               }
    static testMethod void Purchaseordertest3(){   
   Project__c prj = new Project__c ();
         prj.Name='ITC';
         prj.Plantype__c=  prj.Id;
         prj.Ends_date__c = system.toDay().addDays(3);
         prj.Starts_date__c= system.toDay();
         prj.Status__c = 'In Progress';
         System.assertEquals('ITC', prj.name);         
         insert prj;
         
    Subproject__c subPrj = new Subproject__c();         
         subPrj.Name='ITC Project';
         subPrj.Parent_project__c = prj.Id;
         subPrj.Ends_date__c = system.toDay().addDays(3);
         subPrj.Starts_date__c= system.toDay();
         subPrj.Status__c = 'In Progress'; 
         subPrj.Parent_project__c = prj.Id;
         //subPrj.Project_del__c = prj.Id;         
         System.assertEquals('ITC Project', subPrj.name);     
         insert subPrj;
                     
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
        
      Purchase_order__c objpurchase=new Purchase_order__c ();   
        objpurchase.Name='testpurchaces';
        objpurchase.musqot__Purchase_order_name__c='testperchage';
        objpurchase.musqot__Project__c=prj.Id;
        objpurchase.musqot__subproject__c=subPrj.Id;
        objpurchase.musqot__Total_cost__c=100;
        objpurchase.musqot__Supplier__c='testsuppilor';
        System.assertEquals('testsuppilor', objpurchase.musqot__Supplier__c);
        insert objpurchase;
        Attachment attachment=new Attachment();
        attachment.OwnerId = userinfo.getuserid();
        attachment.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attachment.body=bodyBlob;
        attachment.ParentId = objpurchase.Id ;
        insert attachment;
         if(objpurchase.Send_date__c ==System.today() && objpurchase.musqot__Supplier_email__c != null && objpurchase.musqot__Supplier_email__c != ''){ 
        Purchase_order__c  purchOrdr = [SELECT Id,musqot__Purchase_order_name__c,musqot__Supplier_email__c,Name,musqot__Total_cost__c,musqot__Description__c, OwnerId FROM Purchase_order__c WHERE Id = :objpurchase.Id];
          EmailTemplate template = [SELECT Id, name,Subject, HtmlValue, Body FROM EmailTemplate WHERE name= 'Purchaseorder'];  
          Contact cnt = new Contact();
          cnt.LastName = 'Supplier';
          cnt.Email = purchOrdr .musqot__Supplier_email__c;
          insert cnt;
          Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setWhatId(purchOrdr .Id);
        mail.setTargetObjectId(cnt.Id);
        mail.setTemplateId(template.Id);
        mail.saveAsActivity = false;
        
          if(attachment.body<>null){
            //Set email file attachments
            List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
            // Add to attachment file list
            Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
            efa.setFileName(attachment.Name);
            efa.setBody(attachment.Body);
            efa.setContentType(attachment.ContentType);
            fileAttachments.add(efa);
            mail.setFileAttachments(fileAttachments);
         }
            //Send email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
            delete cnt;           
        }       
          
        
        Purchase_order_setting__c objpoorderset = new Purchase_order_setting__c();
        objpoorderset .musqot__PO_Startnumber__c = 10;
        System.assertEquals(10, objpoorderset .musqot__PO_Startnumber__c);
        insert objpoorderset ;
           
        Purchase_article__c objpoarticlce = new Purchase_article__c();
        objpoarticlce .Name = 'test';
        System.assertEquals('test', objpoarticlce .Name );
        insert objpoarticlce ;
        
        contact objcont = new contact();
        objcont .LastName = 'testname';
        objcont .Email = 'newuser123@testorg.com';
        System.assertEquals('testname', objcont .LastName);
        insert objcont ; 
        
        ApexPages.currentPage().getParameters().put('markID', objMarketingact.id);
         String tabId = System.currentPageReference().getParameters().get('tabId');  
        ApexPages.StandardController sc = new ApexPages.standardController(objpurchase); 
        test.startTest();
        PurchaseorderContrllor objpur=new PurchaseorderContrllor (sc);
        //objpur.SingleEmailMessage ;
        List<SelectOption> temp = objpur.PAList;
        objpur.insertOrders();
        objpur.cancel();
        try{
        objpur.sendEmail(objpurchase, attachment);
        }catch(exception e){}
        objpur.contenttype='test';
        objpur.a1=0.1;
        objpur.a2='test';
        objpur.a3='test';
        //objpur.getRedirectToTemplate();
         //objpur.redirectToTemplate(); 
        test.stoptest();  
      }
   static testMethod void Purchaseorderinsert(){
       Project__c prj = new Project__c ();
         prj.Name='ITC';
         prj.Plantype__c=  prj.Id;
         prj.Ends_date__c = system.toDay().addDays(3);
         prj.Starts_date__c= system.toDay();
         prj.Status__c = 'In Progress';
         System.assertEquals('ITC', prj.name);         
         insert prj;
         
    Subproject__c subPrj = new Subproject__c();         
         subPrj.Name='ITC Project';
         subPrj.Parent_project__c = prj.Id;
         subPrj.Ends_date__c = system.toDay().addDays(3);
         subPrj.Starts_date__c= system.toDay();
         subPrj.Status__c = 'In Progress'; 
         subPrj.Parent_project__c = prj.Id;
         //subPrj.Project_del__c = prj.Id;         
         System.assertEquals('ITC Project', subPrj.name);     
         insert subPrj;
                     
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;
        
      Purchase_order__c objpurchase=new Purchase_order__c ();   
        objpurchase.Name='testpurchaces';
        objpurchase.musqot__Purchase_order_name__c='testperchage';
        objpurchase.musqot__Project__c=prj.Id;
        objpurchase.musqot__subproject__c=subPrj.Id;
        objpurchase.musqot__Total_cost__c=100;
        objpurchase.musqot__Supplier__c='testsuppilor';
        System.assertEquals('testsuppilor', objpurchase.musqot__Supplier__c);
        insert objpurchase;
         EmailTemplate template = new EmailTemplate();
         template .name='test';
         template.subject='test';
       
            
           Contact cnt = new Contact();
            cnt.LastName = 'Supplier';
            cnt.Email = objpurchase.musqot__Supplier_email__c;
            insert cnt;
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setWhatId(objpurchase.Id);
            mail.setTargetObjectId(cnt.Id);
            mail.setTemplateId(template.Id);
            mail.saveAsActivity = false;
        ApexPages.currentPage().getParameters().put('markID', objMarketingact.id); 
        ApexPages.StandardController sc = new ApexPages.standardController(objpurchase);
        PurchaseorderContrllor purinsert=new PurchaseorderContrllor (sc);
        purinsert.insertOrders();
           }
    static testMethod void Purchaseorderinsert1(){
        Project__c prj = new Project__c ();
         prj.Name='ITC';
         prj.Ends_date__c = system.toDay().addDays(3);
         prj.Starts_date__c= system.toDay();
         prj.Status__c = 'In Progress';
         System.assertEquals('ITC', prj.name);         
         insert prj;
        
        Purchase_order_setting__c objpoorderset = new Purchase_order_setting__c();
        objpoorderset .PO_Startnumber__c = 10;
        objpoorderset .PO_Lastnumber__c = 5;
        //objpoorderset .PO_Prefix__c = null;
        System.assertEquals(10, objpoorderset .PO_Startnumber__c);
        insert objpoorderset ;
        PageReference pageRef = Page.ProjectDetails;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('projectid', prj.id);
        ApexPages.StandardController sc = new ApexPages.standardController(prj);
        PurchaseorderContrllor purinsert1=new PurchaseorderContrllor (sc);
        purinsert1.insertOrders();
    }    
 }