src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Members__c.object
<CustomObject>
    <description>Member in a project/sub project</description>
    <fields>
        <fullName>ProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role in Project</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Email__c</fullName>
        <label>Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member set name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_type__c</fullName>
        <label>User type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal user</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communities user</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Workspace__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>This text will come at top left side.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Workspaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Workspaces_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>html_description__c</fullName>
        <label>Presentation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Presentation</label>
    <nameField>
        <label>Headline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Presentation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MarketingactivityTest.cls
/*******************************************************
Class Name: MarketingactivityTest
Author:Nagaraju         Last modified by: Janardhan reddy
Date :21/7/2014         Date : 19/3/2105                    
********©2013 Musqot marketing technology Pvt ltd *******/

@isTest(Seealldata = True)
private class MarketingactivityTest{
    static testMethod void Marketingactivity(){
    Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
    User u2 =new User( Alias = 'newUser1' ,
    Email ='newuser123@testorg.com',
    EmailEncodingKey = 'UTF-8',
    LastName = 'Testing',
    LanguageLocaleKey='en_US',
    LocaleSidKey='en_US', 
    UserName='newuser1234@testorg.com',
    ProfileId=p.Id,
    TimeZoneSidKey = 'America/Los_Angeles');
    insert u2;            
    Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c); 
    Project__c objproject = new Project__c ();
    objproject.Name='test';
    //objproject.Project_type__c='test';
    objproject.Starts_date__c= System.now().date();
    objproject.Ends_date__c= System.now().date();
    objproject.OwnerId=plm.userid__c;
    System.assertEquals('test', objproject.name);
    insert objproject;
    
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
    objMarketingact.Name='test';
    objMarketingact.Description__c='tdescriptionest';
    objMarketingact.Status__c='completed';
    objMarketingact.Plan__c=objproject.id;
    System.assertEquals('test', objMarketingact.name);
    try{
    insert objMarketingact;
    }
    catch(Exception e){
    Boolean expectedExceptionThrown =  e.getMessage().contains('Here goes your custom message') ? true : false;
    system.assertEquals(expectedExceptionThrown,true);      
    }
    Workspace__c objectwork1=new Workspace__c();
    objectwork1.Name='test';
    objectwork1.ProjectName__c=objproject.id;
    objectwork1.Description__c='test1';
    objectwork1.html_description__c='test123';
    
    insert objectwork1;
    
    Workspace__c objectwork=new Workspace__c();
    objectwork.Name='test';
    objectwork.ProjectName__c=objproject.id;
    objectwork.Description__c='test1';
    objectwork.html_description__c='test123';
    
    System.assertEquals('test', objectwork.name);
    insert objectwork;
    
    Task Objtask=new Task();
    Objtask.Task_name__c='test';
    Objtask.Status='completed';
    Objtask.Priority='high';
    Objtask.Allocated_h__c=12;
    System.assertEquals('test',Objtask.Task_name__c);
    //insert Objtask;
    Members__c objmember=new Members__c ();
    //objmember.Name ='test';
    //objmember.ProjMembers__c='test';
    //objmember.ProjUsers__c=u2.Id;
    //objmember.SubProjMembers__c='test';
    objmember.Role__c='Member';
    objmember.User_Email__c ='standarduser1@test.com';
    System.assertEquals('Member', objmember.Role__c);
    insert objmember;
    Attachment attach=new Attachment();
    attach.OwnerId = objMarketingact.OwnerId;       
    attach.Name='Unit Test Attachment';
    Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    attach.body=bodyBlob;
    attach.parentId=objMarketingact.id;
    attach.contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    System.assertEquals(objMarketingact.id,attach.parentId);
    //insert attach;
    ApexPages.currentPage().getParameters().put('id', objMarketingact.id);
    ApexPages.currentPage().getParameters().get('taskid');
    ApexPages.currentPage().getParameters().get('atmid');
    ApexPages.currentPage().getParameters().get('mbrId'); 
    ApexPages.StandardController sc = new ApexPages.standardController(objMarketingact); 
    Marketingactivity  objMarketingactivity = new Marketingactivity(sc);
    //Marketingactivity.AttachWrapper mawrap = new Marketingactivity.AttachWrapper(sc);
    objMarketingactivity .workSpace();
    objMarketingactivity.getmyfile();
    objMarketingactivity.Savedoc();
    objMarketingactivity.newMember();
    objMarketingactivity.gotoMemberEdit();
    objMarketingactivity.getparentmembers();
    objMarketingactivity.newtask(); 
    objMarketingactivity.gotoattchmentpage();
    objMarketingactivity.getTabInFocus();
    try{
    
    objMarketingactivity.delMrkRe();
    objMarketingactivity.gotoTaskEdit();
     
    }catch(exception e){}
   
    objMarketingactivity.getmembers();
    objMarketingactivity.gotomarketingEdit();
    objMarketingactivity.gettaskrecs2();
    objMarketingactivity.getGadgetHTMLContent();
    objMarketingactivity.customset();
    objMarketingactivity.getpubdatelist();
    objMarketingactivity.redirectNewDatesPage();
    objMarketingactivity.getAttLinks();
    objMarketingactivity.newPubdate();
    objMarketingactivity.activityEndDate='dec31';
    try{
     objMarketingactivity.goToActivityDatEditMode();
    }catch(exception e){}
    }
  static testMethod void Marketingactivity2(){
    Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
    User u2 =new User( Alias = 'newUser1' ,
    Email ='newuser123@testorg.com',
    EmailEncodingKey = 'UTF-8',
    LastName = 'Testing',
    LanguageLocaleKey='en_US',
    LocaleSidKey='en_US', 
    UserName='newuser1234@testorg.com',
    ProfileId=p.Id,
    TimeZoneSidKey = 'America/Los_Angeles');
    insert u2;            
    Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c); 
    Project__c objproject = new Project__c ();
    objproject.Name='test';
    //objproject.Project_type__c='test';
    objproject.Starts_date__c= System.now().date();
    objproject.Ends_date__c= System.now().date();
    objproject.OwnerId=plm.userid__c;
    System.assertEquals('test', objproject.name);
    insert objproject;
    
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
    objMarketingact.Name='test';
    objMarketingact.Description__c='tdescriptionest';
    objMarketingact.Status__c='completed';
    objMarketingact.Plan__c=objproject.id;
    System.assertEquals('test', objMarketingact.name);
    try{
    insert objMarketingact;
    }
    catch(Exception e){
    Boolean expectedExceptionThrown =  e.getMessage().contains('Here goes your custom message') ? true : false;
    system.assertEquals(expectedExceptionThrown,true);      
    }
    
    
    Workspace__c objectwork1=new Workspace__c();
    objectwork1.Name='test';
    objectwork1.ProjectName__c=objproject.id;
    objectwork1.Description__c='test1';
    objectwork1.html_description__c='test123';
    
    insert objectwork1;
    
    Workspace__c objectwork=new Workspace__c();
    objectwork.Name='test';
    objectwork.ProjectName__c=objproject.id;
    objectwork.Description__c='test1';
    objectwork.html_description__c='test123';
    
    System.assertEquals('test', objectwork.name);
    insert objectwork;
    
    Task Objtask=new Task();
    Objtask.Task_name__c='test';
    Objtask.Status='completed';
    Objtask.Priority='high';
    Objtask.Allocated_h__c=12;
    System.assertEquals('test',Objtask.Task_name__c);
    //insert Objtask;
    Members__c objmember=new Members__c ();
    //objmember.Name ='test';
    //objmember.ProjMembers__c='test';
    //objmember.ProjUsers__c=u2.Id;
    //objmember.SubProjMembers__c='test';
    objmember.Role__c='Member';
    objmember.User_Email__c ='standarduser1@test.com';
    System.assertEquals('Member', objmember.Role__c);
    insert objmember;
    Attachment attach=new Attachment();
    attach.OwnerId = objMarketingact.OwnerId;       
    attach.Name='Unit Test Attachment';
    Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    attach.body=bodyBlob;
    attach.parentId=objMarketingact.id;
    attach.contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    System.assertEquals(objMarketingact.id,attach.parentId);
    //insert attach;
    ApexPages.currentPage().getParameters().put('id', objMarketingact.id);
    ApexPages.currentPage().getParameters().get('taskid');
    ApexPages.currentPage().getParameters().get('atmid');
    ApexPages.currentPage().getParameters().get('mbrId'); 
    ApexPages.StandardController sc = new ApexPages.standardController(objMarketingact); 
    Marketingactivity  objMarketingactivity = new Marketingactivity(sc);
    objMarketingactivity .workSpace();
    objMarketingactivity.setTabInFocus('String s' );
    objMarketingactivity.getmyfile();
    objMarketingactivity.Savedoc();
    objMarketingactivity.newMember();
    objMarketingactivity.gotoMemberEdit();
     objMarketingactivity.getparentmembers();
    objMarketingactivity.newtask(); 
    objMarketingactivity.gotoattchmentpage();
    objMarketingactivity.getTabInFocus();
    try{
    
    objMarketingactivity.delMrkRe();
    objMarketingactivity.gotoTaskEdit();
     
    }catch(exception e){}
   
    objMarketingactivity.getmembers();
    objMarketingactivity.name='test';
    objMarketingactivity.displayPopup=true;
    objMarketingactivity.gotomarketingEdit();
    objMarketingactivity.gettaskrecs2();
        objMarketingactivity.getGadgetHTMLContent();
    objMarketingactivity.customset();
 
    //objMarketingactivity.getTabInFocus();
    
    }}