src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_article__c.object
<CustomObject>
    <description>Type of product the supplier selling</description>
    <label>Purchase article</label>
    <nameField>
        <label>Purchase article</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_order__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effective_date__c</fullName>
        <description>Type in date the date when the cost is expected to occur. Will be use for forecasting in coming versions of Musqot.</description>
        <inlineHelpText>Type in date the date when the cost is expected to occur.</inlineHelpText>
        <label>Effective date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_article__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase article</label>
        <referenceTo>Purchase_article__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_order__c</fullName>
        <label>Purchase order externalid</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Purchase_order_cloesed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is checked, then you can&apos;t registry more invoice on this PO number</inlineHelpText>
        <label>Purchase order closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Purchase_order_name__c</fullName>
        <label>Purchase order number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_order_send__c</fullName>
        <description>The date purchase send to supplier</description>
        <inlineHelpText>The date purchase send to supplier</inlineHelpText>
        <label>Purchase order send</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_date__c</fullName>
        <inlineHelpText>Purchase order will be sent to supplier this date. 
To email you have in field &quot;Supplier email&quot;.
Leave &quot;Send date&quot; empty if you NOT will send.</inlineHelpText>
        <label>Send date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <label>Supplier</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_email__c</fullName>
        <label>Supplier email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Total_cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>subproject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subproject</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Purchase_orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>total_Invoice_cost__c</fullName>
        <label>Invoice cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase order</label>
    <nameField>
        <label>Purchase order name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PurchaseorderEditController.cls
/**********************************************************************
Class Name: PurchaseorderEditController
Author:G Janardhanreddy            Last modified by:Raju GN
Date:27/8/2014                     Date:18/2/2015
********©2013 Musqot marketing technology Pvt ltd **********************/
public with sharing class PurchaseorderEditController{
    private String projectid;
    private String purid;
    private String subprjid;
    private String mrkId;
    private String attsid;
    public String maxPO{get;set;}
    private  decimal maxPO2;
    public decimal poOld;
    public String contentType{get;set;}
    public Attachment atts{get;set;}
    Public Purchase_order__c purs{get;set;}
    //public profile usrProfileName{get;set;}
    public task templateInfo {get; set;}
    public boolean showRec{get;set;}
    public boolean showEdt{get;set;}
    public boolean showrec1{get;set;}
    public boolean showbutton{get;set;}
    public string Download{get;set;}
    private Purchase_order__c pursoldCost;
    public string attachmentName{get;set;}
    public List<Purchase_article__c> PA_Temp = new List<Purchase_article__c>();
    public PurchaseorderEditController(ApexPages.StandardController controller) {
        projectid = ApexPages.currentPage().getParameters().get('planid');
        subprjid = ApexPages.currentPage().getParameters().get('prjId');
        mrkId = ApexPages.currentPage().getParameters().get('markID');
        purid = ApexPages.currentPage().getParameters().get('purid');
        maxPO= ApexPages.currentPage().getParameters().get('maxPO'); 
        
        try {
            purs = [Select Id,ownerid, Name, Description__c,Supplier__c,Supplier_email__c,
                    Total_cost__c,Project__c,subproject__c,Marketing_activity__c, 
                    Send_date__c, Purchase_order_name__c, total_Invoice_cost__c,
                    Effective_date__c, Purchase_article__c, Purchase_order_cloesed__c,Purchase_order_send__c 
                    FROM Purchase_order__c  
                    where Id =:purid limit 1];        
        }
        catch (System.QueryException e) {}  
        if(purid<>null){
            try {
                pursoldCost = [Select  Total_cost__c, total_Invoice_cost__c 
                               FROM Purchase_order__c  where Id =:purid limit 1];  
            }
            catch (System.QueryException e) {}  
            if(pursoldCost.Total_cost__c<>null){
                poOld = pursoldCost.Total_cost__c;
            }
            else{
                poOld = 0;
            }
            if(pursoldCost.total_Invoice_cost__c<>null){
                showEdt=false;
            }
        }
        string mainStr = ApexPages.CurrentPage().getParameters().get('retURL');
        atts= attch();
        if(atts<>null){
            if(atts.Name.containsAny('.'))
                attachmentName=atts.Name.substring(0,atts.Name.indexOf('.'));
            else 
                attachmentName=atts.Name;
        }
        showRec=true;
        showEdt=false;
        showRec1=false;
        Download='';
    }
    /*****************************************************************************
attch():This returns the Attachment details belongs to the Purchase order
att:This return the attachment details(Namee,decription etc..)
*****************************************************************************/
    public Attachment attch(){
        Attachment att;
        try{
            att= [SELECT id,ownerid,Name,description,parent.id,
                  parent.name,parent.type,Body,BodyLength,contentType 
                  from Attachment where Parent.id =:purid  limit 1];
        }catch(exception e){}
        
        return att;
    }
    /*****************************************************************
PAList: convert the lookup to dropdown of Purchase articles records.
.******************************************************************/
    public List<SelectOption> PAList
    {
        get
        {
            PA_Temp = [Select u.Name, u.Id From Purchase_article__c u limit 250];
            PAList = new List<SelectOption>(); 
            for(Purchase_article__c temp : PA_Temp)
            {
                PAList.add(new SelectOption(temp.Id, temp.Name));
            }
            return PAList;
        }
        set;
    }
    /************************************************************************************************
Save():Update the purchaseorder record & Insert Attachment & Then redirect to ralated parent page
**************************************************************************************************/
    public Pagereference Save(){ 
        Pagereference pr;
        Decimal maxPO2  = Decimal.valueOf(maxPO);
        try{
            if((maxPO2 - poOld) < purs.Total_cost__c ){
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,' '+ Label.finov_nofounds));
                return null;
            }
        }catch(exception e){}
        if(purs<>null){
            if (Purchase_order__c.sObjectType.getDescribe().isUpdateable())
            {                
                if(purs.Send_date__c==system.today() ){
                    purs.Purchase_order_send__c =purs.Send_date__c;                   
                    Update purs;
                }
                else {
                    Update purs;
                }
            }
            
            Purchase_order__c pOrder = [Select Id,ownerid, Name, Description__c,
                                        Supplier__c,Supplier_email__c, Total_cost__c,Project__c,
                                        subproject__c,Marketing_activity__c, Send_date__c, Purchase_order_name__c,
                                        total_Invoice_cost__c,Effective_date__c, Purchase_article__c, Purchase_order_cloesed__c,Purchase_order_send__c 
                                        FROM Purchase_order__c 
                                        where Id =:purid limit 1];        
            if(pOrder.musqot__Purchase_order_cloesed__c == true && pOrder.musqot__total_Invoice_cost__c == null){
                pOrder.musqot__total_Invoice_cost__c = 0;
                update pOrder;
            }
            
            
            //Attachment Code
            attachment.OwnerId = purs.OwnerId;
            attachment.ParentId = purs.Id; // the record the file is attached to        
            attachment.ContentType=ContentType;
            string extension=MusqotUtility.fileType(contentType);//filetype fetching from utility class.
            if(attachment.body<>null){
                if (Schema.sObjectType.Attachment.fields.body.isCreateable()){
                    attachment.Name = purs.Purchase_order_name__c+extension;
                    if(atts<>null){
                        delete atts;
                    }
                    insert attachment;  
                    atts = attch();
                    
                }                
            }
            
            
            if(projectid<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/ProjectDetails?id='+EncodingUtil.urlEncode(projectid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('purchase','UTF-8');
                pr=new Pagereference (pageRef);
            }
            else if(subprjid<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/SubProject?id='+EncodingUtil.urlEncode(subprjid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('purchase','UTF-8');
                pr=new Pagereference (pageRef);
            }
            else if(mrkId<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/Marketingactivity?id='+EncodingUtil.urlEncode(mrkId,'UTF-8')+'&tab='+EncodingUtil.urlEncode('purchase','UTF-8');
                pr=new Pagereference (pageRef);
            }
            
        }
        return pr;
    }
    /******************************************************
gotoEditMode():show edit mode of Purchase order record
******************************************************/
    Public void gotoEditMode(){ 
        showRec=false;
        showEdt=true;
        
    }
    /******************************************************** 
gotoInfoMode():show detail mode of  Purchase order record
********************************************************/
    Public void gotoInfoMode(){
        showRec=true;
        showEdt=false;
        
    }
    // Create Attachment 
    public Attachment attachment {
        get {
            if (attachment == null)
                attachment = new Attachment();
            return attachment;
        }
        set;
    }
    /*********************************************************************************** 
deleteorders() : Delete the Purchase orders and Then redirect to related parent  page
***************************************************************************************/  
    public Pagereference deleteorders(){
        Pagereference pr;
        if(purs<>null){
            if (Purchase_order__c.sObjectType.getDescribe().isDeletable())
            {
                delete purs;
            }
            if(projectid<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/ProjectDetails?id='+EncodingUtil.urlEncode(projectid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('purchase','UTF-8');
                pr=new Pagereference (pageRef);
            }
            else if(subprjid<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/SubProject?id='+EncodingUtil.urlEncode(subprjid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('purchase','UTF-8');
                pr=new Pagereference (pageRef);
            }
            else if(mrkId<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/Marketingactivity?id='+EncodingUtil.urlEncode(mrkId,'UTF-8')+'&tab='+EncodingUtil.urlEncode('purchase','UTF-8');
                pr=new Pagereference (pageRef);
            }
            
        }
        return pr;
        
    }   
    /****************************************************************************
DeleteAttchment(): delete the Attachments 
/****************************************************************************/
    public void DeleteAttchment(){    
        if (Schema.sObjectType.Attachment.isDeletable())    
        {
            delete atts;
            atts = null;
        }       
    }    
    public String getRedirectToTemplate() {
        return null;
    }
    
    
    public Pagereference redirectToTemplate() {
        try{
            insert templateInfo;
        }catch(Exception e){
            ApexPages.addMessages(e);
        }
        return null;
    }
    /*********************************************
Cancel():redirect to related parent page page
**********************************************/
    public Pagereference Cancel(){
        Pagereference pr;
        if(projectid<>null){
            String tabId = System.currentPageReference().getParameters().get('tabId');
            string pageRef='/apex/ProjectDetails?id='+EncodingUtil.urlEncode(projectid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('purchase','UTF-8');
            pr=new Pagereference (pageRef);
        }
        else if(subprjid<>null){
            String tabId = System.currentPageReference().getParameters().get('tabId');
            string pageRef='/apex/SubProject?id='+EncodingUtil.urlEncode(subprjid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('purchase','UTF-8');
            pr=new Pagereference (pageRef);       
        }
        else if(mrkId<>null){
            String tabId = System.currentPageReference().getParameters().get('tabId');
            string pageRef='/apex/Marketingactivity?id='+EncodingUtil.urlEncode(mrkId,'UTF-8')+'&tab='+EncodingUtil.urlEncode('purchase','UTF-8');
            pr=new Pagereference (pageRef);
        }
        return pr;
    } 
}