src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StatusImage__c</fullName>
        <description>old code
IMAGE(&apos;/servlet/servlet.FileDownload?file=&apos;+musqot__Status_Image_Id__c,TEXT(musqot__Status__c),16,16)</description>
        <formula>CASE(Status__c, &apos;Not Started&apos;, IMAGE(&apos;/resource/1433929854000/musqot__Planned&apos;,TEXT(Status__c),16,16), &apos;In Progress&apos;, IMAGE(&apos;/resource/1433930034000/musqot__Active&apos;,TEXT(Status__c),16,16),&apos;Completed&apos;,IMAGE(&apos;/resource/1433930013000/musqot__Finnished&apos;,TEXT(Status__c),16,16),&apos;Deferred&apos;,IMAGE(&apos;/resource/1433930023000/musqot__Deferred&apos;,TEXT(Status__c),16,16), IMAGE(&apos;/resource/1443021886000/musqot__StatusOther&apos;,TEXT(Status__c),16,16))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Members__c.object
<CustomObject>
    <description>Member in a project/sub project</description>
    <fields>
        <fullName>ProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role in Project</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Email__c</fullName>
        <label>Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member set name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusImage__c</fullName>
        <description>old
IMAGE(&apos;/servlet/servlet.FileDownload?file=&apos;+musqot__Status_Image_Id__c,TEXT(musqot__Status__c),16,16)</description>
        <formula>CASE(Status__c, &apos;Not Started&apos;, IMAGE(&apos;/resource/1433929854000/musqot__Planned&apos;,TEXT(Status__c),16,16), &apos;In Progress&apos;, IMAGE(&apos;/resource/1433930034000/musqot__Active&apos;,TEXT(Status__c),16,16),&apos;Completed&apos;,IMAGE(&apos;/resource/1433930013000/musqot__Finnished&apos;,TEXT(Status__c),16,16),&apos;Deferred&apos;,IMAGE(&apos;/resource/1433930023000/musqot__Deferred&apos;,TEXT(Status__c),16,16), IMAGE(&apos;/resource/1443021886000/musqot__StatusOther&apos;,TEXT(Status__c),16,16))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusImage__c</fullName>
        <description>old 
IMAGE(&apos;/servlet/servlet.FileDownload?file=&apos;+musqot__Status_Image_Id__c,TEXT(musqot__Status__c),16,16)</description>
        <formula>CASE(Status__c, 
&apos;Not Started&apos;, IMAGE(&apos;/resource/1433929854000/musqot__Planned&apos;,TEXT(Status__c),16,16), 
&apos;In Progress&apos;, IMAGE(&apos;/resource/1433930034000/musqot__Active&apos;,TEXT(Status__c),16,16),
&apos;Completed&apos;,IMAGE(&apos;/resource/1433930013000/musqot__Finnished&apos;,TEXT(Status__c),16,16),
&apos;Deferred&apos;,IMAGE(&apos;/resource/1433930023000/musqot__Deferred&apos;,TEXT(Status__c),16,16),
IMAGE(&apos;/resource/1443021886000/musqot__StatusOther&apos;,TEXT(Status__c),16,16))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskControllerTest.cls
/*********************************************************************
Class Name: TaskControllerTest 
Author:Chaithanya daggumati         Last modified by:Raju GN
Date: 22/7/2014                     Date: 19/3/2015  
********©2013 Musqot marketing technology Pvt ltd ********************/
@isTest(seeAllData=true)
    public class TaskControllerTest{
        static testMethod void TaskController(){           
           Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert u2;
            
            Project__c objproject = new Project__c ();
            objproject.Name='test';
           //objproject.Project_type__c='test';
            objproject.Starts_date__c= System.now().date();
            objproject.Ends_date__c= System.now().date();
            System.assertEquals('test', objproject.name);
            insert objproject;
            
            Subproject__c objspr = new Subproject__c ();
            objspr.name = 'testname';
            objspr.Description__c = 'sampdesc';
            objspr.Starts_date__c = date.today();
            objspr.Ends_date__c = date.today();
            objspr.Status__c = 'Notstarted';    
            System.assertEquals('testname', objspr.name);
            insert objspr; 
            
            Subproject__c objsp = new Subproject__c ();
            objsp.name = 'testname';
            objsp.Description__c = 'sampdesc';
            objsp.Starts_date__c = date.today();
            objsp.Ends_date__c = date.today()+10;
            objsp.Project_del__c = objspr.id;
            objsp.Parent_project__c = objproject.id;
            //objsp.Project_type__c = 'prtyp';
            objsp.Status__c = 'Notstarted';
           //objsp.user__c = u2.id;        
            System.assertEquals('testname', objsp .name);
            insert objsp ; 

            Marketing_activity__c objMarketingact=new Marketing_activity__c();
            objMarketingact.Name='test';
            objMarketingact.Description__c='tdescriptionest';
            objMarketingact.Status__c='completed';
            System.assertEquals('test', objMarketingact.name);
            insert objMarketingact;
            
            Task objtask = new Task();      
            objtask.Task_name__c = 'testname'; 
            objtask.OwnerId=UserInfo.getUserId();
            objtask.WhatId=objproject.id;
            objtask.ActivityDate =system.toDay();
            objtask.Status='Deferred';
            objtask.Allocated_h__c=2;
            objtask.Outcome_h__c=2;
            objtask.Task_description__c='test record';
            objtask.Task_name__c='Testtask';                     
            insert objtask ;
            System.assertEquals('Testtask', objtask .Task_name__c); 
            Attachment attach=new Attachment();       
            attach.Name='Unit Test Attachment';
            Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
            attach.body=bodyBlob;
            attach.parentId=objtask .id;
            System.assertEquals(objtask .id,attach.parentId);
            insert attach;
            
             Members__c objmember=new Members__c ();
             objmember.ProjMembers__c= objproject.Id;
             objmember.ProjUsers__c= u2.Id;
             objmember.SubProjMembers__c= objsp.Id;
             objmember.Role__c='Member';
             objmember.User_Email__c ='standarduser1@test.com';
             System.assertEquals('Member', objmember.Role__c);
             insert objmember;
            
            test.starttest();  
            String tabId = System.currentPageReference().getParameters().get('tabId');           
            ApexPages.currentPage().getParameters().put('id', objtask.id);
            ApexPages.currentPage().getParameters().put('mrkId',objMarketingact.id);
            PageReference pageRef = Page.Task;
            Test.setCurrentPage(pageRef); 
            ApexPages.StandardController sc = new ApexPages.standardController(objtask);            
            TaskController tsk = new TaskController(sc);
            TaskController tsk1= new TaskController();
            Members__c mbrs = [select Id,ProjUsers__c from Members__c LIMIT 1];
            upsert objmember;
            list<SelectOption>  temp=tsk.getItems();
            tsk.selectedTime='test';
            try{
            DateTime temp1=tsk.getConvertDateTime('string strDT');
            }catch(exception e){}
            tsk.Task = objtask;
           tsk.dauDateMethod();
           // c
            tsk.Save();
           // }catch(exception e){}
            tsk.cancel();
            tsk.getRedirectToTemplate();
            tsk.redirectToTemplate();
            tsk.getSelectedItem();
            tsk.setSelectedItem('String s');
            //tsk.getConvertDateTime('String strDt');
            test.stopTest();
           }           
    static testMethod void Taskprojtest1(){
           Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert u2;
            
            Project__c objproject = new Project__c ();
            objproject.Name='test';
           //objproject.Project_type__c='test';
            objproject.Starts_date__c= System.now().date();
            objproject.Ends_date__c= System.now().date();
            System.assertEquals('test', objproject.name);
            insert objproject;
            
            Subproject__c objsp = new Subproject__c ();
            objsp.name = 'testname';
            objsp.Description__c = 'sampdesc';
            objsp.Starts_date__c = date.today();
            objsp.Ends_date__c = date.today();
            objsp.Status__c = 'Notstarted';
            //objsp.StatusImage__c = 'Inprograss';
            //objsp.user__c = u2.id;        
            System.assertEquals('testname', objsp .name);
            insert objsp ; 
                    
            
            Marketing_activity__c objMarketingact=new Marketing_activity__c();
            objMarketingact.Name='test';
            objMarketingact.Description__c='tdescriptionest';
            objMarketingact.Status__c='completed';
            System.assertEquals('test', objMarketingact.name);
            insert objMarketingact;
            
            Task objtask = new Task();      
            objtask.Task_name__c = 'testname';
            objtask.WhatId=objproject.id;                      
            System.assertEquals('testname', objtask .Task_name__c); 
            //insert objtask ;
            
             Members__c objmember=new Members__c ();
             //objmember.Name ='test';
             objmember.ProjMembers__c= objproject.Id;
             objmember.ProjUsers__c= u2.Id;
             objmember.SubProjMembers__c= objsp.Id;
            objmember.Role__c='Member';
            objmember.User_Email__c ='standarduser1@test.com';
            System.assertEquals('Member', objmember.Role__c);
            insert objmember;
            test.starttest();
            PageReference pageRef = Page.Task;
            Test.setCurrentPage(pageRef); 
            String tabId = System.currentPageReference().getParameters().get('tabId');
            //ApexPages.currentPage().getParameters().put('mrkId',null);            
            ApexPages.currentPage().getParameters().put('planid',objproject.id);
            system.debug('----->'+objproject.id);
            
            ApexPages.StandardController sc = new ApexPages.standardController(objtask);
            TaskController tsk = new TaskController(sc);
            tsk.Task = objtask;
            try{
            tsk.Save();
            }catch(exception e){}
            tsk.cancel();
            tsk.getRedirectToTemplate();
            tsk.redirectToTemplate();
            tsk.getSelectedItem();
            tsk.setSelectedItem('String s');
           // tsk.getConvertDateTime('String strDt');
           }
    static testMethod void Taskprojtest2(){
           Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert u2;
            
            Project__c objproject = new Project__c ();
            objproject.Name='test';
           //objproject.Project_type__c='test';
            objproject.Starts_date__c= System.now().date();
            objproject.Ends_date__c= System.now().date();
            System.assertEquals('test', objproject.name);
            insert objproject;
            
            Subproject__c objsp = new Subproject__c ();
            objsp.name = 'testname';
            objsp.Description__c = 'sampdesc';
            objsp.Starts_date__c = date.today();
            objsp.Ends_date__c = date.today();
            //objsp.Project_del__c = ;
            //objsp.Parent_project__c = 'pproj';
            //objsp.Project_type__c = 'prtyp';
            objsp.Status__c = 'Notstarted';
            //objsp.StatusImage__c = 'Inprograss';
            //objsp.user__c = u2.id;        
            System.assertEquals('testname', objsp .name);
            insert objsp ; 
                    
            
            Marketing_activity__c objMarketingact=new Marketing_activity__c();
            objMarketingact.Name='test';
            objMarketingact.Description__c='tdescriptionest';
            objMarketingact.Status__c='completed';
            System.assertEquals('test', objMarketingact.name);
            insert objMarketingact;
            
            Task objtask = new Task();      
            objtask.Task_name__c = 'testname';
            objtask.WhatId=objsp.id;                      
            System.assertEquals('testname', objtask .Task_name__c); 
            //insert objtask ;
            
             Members__c objmember=new Members__c ();
             objmember.ProjMembers__c= objproject.Id;
             objmember.ProjUsers__c= u2.Id;
             objmember.SubProjMembers__c= objsp.Id;
             objmember.Role__c='Member';
             objmember.User_Email__c ='standarduser1@test.com';
             System.assertEquals('Member', objmember.Role__c);
             insert objmember;
             test.starttest();
             PageReference pageRef = Page.Task;
             Test.setCurrentPage(pageRef); 
           
            String tabId = System.currentPageReference().getParameters().get('tabId');         
            ApexPages.currentPage().getParameters().put('subid',objsp .id);
            system.debug('----->'+objproject.id);
            ApexPages.StandardController sc = new ApexPages.standardController(objtask);
            TaskController tsk = new TaskController(sc);
            tsk.Task = objtask;
           try{
            tsk.Save();
            }catch(exception e){}
            tsk.cancel();
            tsk.getRedirectToTemplate();
            tsk.redirectToTemplate();
            tsk.getSelectedItem();
            tsk.setSelectedItem('String s');
            //tsk.getConvertDateTime('String strDt');
            test.stopTest();
           }
 static testMethod void Taskprojtest3(){           
           Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert u2;
            
            Project__c objproject = new Project__c ();
            objproject.Name='test';
           //objproject.Project_type__c='test';
            objproject.Starts_date__c= System.now().date();
            objproject.Ends_date__c= System.now().date();
            System.assertEquals('test', objproject.name);
            insert objproject;
            
            Subproject__c objsp = new Subproject__c ();
            objsp.name = 'testname';
            objsp.Description__c = 'sampdesc';
            objsp.Starts_date__c = date.today();
            objsp.Ends_date__c = date.today();
            //objsp.Project_del__c = ;
            //objsp.Parent_project__c = 'pproj';
            //objsp.Project_type__c = 'prtyp';
            objsp.Status__c = 'Notstarted';
            //objsp.StatusImage__c = 'Inprograss';
            //objsp.user__c = u2.id;        
            System.assertEquals('testname', objsp .name);
            insert objsp ; 
                    
            
            Marketing_activity__c objMarketingact=new Marketing_activity__c();
            objMarketingact.Name='test';
            objMarketingact.Description__c='tdescriptionest';
            objMarketingact.Status__c='completed';
            System.assertEquals('test', objMarketingact.name);
            insert objMarketingact;
            
            Task objtask = new Task();      
            objtask.Task_name__c = 'testname';
            objtask.WhatId=objproject.id;                      
            System.assertEquals('testname', objtask .Task_name__c); 
            //insert objtask ;
            
             Members__c objmember=new Members__c ();
             //objmember.Name ='test';
             objmember.ProjMembers__c= objproject.Id;
             objmember.ProjUsers__c= u2.Id;
             objmember.SubProjMembers__c= objsp.Id;
            objmember.Role__c='Member';
            objmember.User_Email__c ='standarduser1@test.com';
            System.assertEquals('Member', objmember.Role__c);
            insert objmember;
            test.starttest();
            PageReference pageRef = Page.Task;
            Test.setCurrentPage(pageRef); 
            //ApexPages.currentPage().getParameters().put('mrkId',null);    
            String tabId = System.currentPageReference().getParameters().get('tabId');        
            ApexPages.currentPage().getParameters().put('mrkid',objMarketingact.id);
            ApexPages.StandardController sc = new ApexPages.standardController(objtask);
            TaskController tsk = new TaskController(sc);
            tsk.Task = objtask;
            //try{
            tsk.Save();
            //}catch(exception e){}
            tsk.cancel();
            tsk.getRedirectToTemplate();
            tsk.redirectToTemplate();
            tsk.getSelectedItem();
            tsk.setSelectedItem('String s');
            //tsk.getConvertDateTime('String strDt');
             test.stopTest();
              }
     static testMethod void Taskprojtestsave(){ 
           Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert u2;
            
            Project__c objproject = new Project__c ();
            objproject.Name='test';
           //objproject.Project_type__c='test';
            objproject.Starts_date__c= System.now().date();
            objproject.Ends_date__c= System.now().date();
            System.assertEquals('test', objproject.name);
            insert objproject;
            
            Subproject__c objsp = new Subproject__c ();
            objsp.name = 'testname';
            objsp.Description__c = 'sampdesc';
            objsp.Starts_date__c = date.today();
            objsp.Ends_date__c = date.today();
            objsp.Project_del__c =objsp.id ;
            objsp.Parent_project__c =objproject.id;          
            objsp.Status__c = 'Notstarted';                  
            System.assertEquals('testname', objsp .name);
            insert objsp;
            
            Task objtask = new Task();      
            objtask.Task_name__c = 'testname';
            objtask.WhatId=objproject.id;                                 
            insert objtask ; 
            System.assertEquals('testname', objtask .Task_name__c);
            
            test.starttest();
            PageReference pageRef = Page.ProjectDetails;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('projectid',objproject.id);
            ApexPages.StandardController sc = new ApexPages.standardController(objproject);
            TaskController tsksave = new TaskController(sc);
            try{
            tsksave.Save();
            }catch(exception e){}
            test.stopTest();      
             }
   static testMethod void Taskprojtestsave1(){ 
            Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert u2;
            
            Project__c objproject = new Project__c ();
            objproject.Name='test';
           //objproject.Project_type__c='test';
            objproject.Starts_date__c= System.now().date();
            objproject.Ends_date__c= System.now().date();
            System.assertEquals('test', objproject.name);
            insert objproject;
            
            Subproject__c objsp = new Subproject__c ();
            objsp.name = 'testname';
            objsp.Description__c = 'sampdesc';
            objsp.Starts_date__c = date.today();
            objsp.Ends_date__c = date.today();
            objsp.Project_del__c =objsp.id ;
            objsp.Parent_project__c =objproject.id;          
            objsp.Status__c = 'Notstarted';                  
            System.assertEquals('testname', objsp .name);
            insert objsp;
            
            Task objtask = new Task();      
            objtask.Task_name__c = 'testname';
            objtask.WhatId=objproject.id;                                 
            insert objtask ; 
            System.assertEquals('testname', objtask .Task_name__c);
            
            test.starttest();
            PageReference pageRef = Page.ProjectDetails;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('subprjid',objsp.id);
            ApexPages.StandardController sc = new ApexPages.standardController(objsp);
            TaskController tsksave = new TaskController(sc);
            try{
            tsksave.Save();
            }catch(exception e){}
            test.stopTest();      
             }
     static testMethod void Taskcos(){
     		 Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
             User u2 =new User( Alias = 'newUser1',Email ='newuser123@testorg.com',EmailEncodingKey = 'UTF-8',LastName = 'Testing',
             LanguageLocaleKey='en_US',LocaleSidKey='en_US', UserName='newuser1234@testorg.com',ProfileId=p.Id,
             TimeZoneSidKey = 'America/Los_Angeles');
             insert u2;
         	musqot__Costcentre__c objCC=new musqot__Costcentre__c(); 
              objCC.Name='test';
              objCC.musqot__cc_Owner__c=u2.id;
              objCC.musqot__Headline__c ='present';
              insert objCC;
              System.assertEquals('test', objCC.name);
            ApexPages.currentPage().getParameters().put('cosid',objCC.id);
            ApexPages.StandardController sc = new ApexPages.standardController(objCC);
         	TaskController tskcs = new TaskController(sc);
            tskcs.Save();
         	tskcs.cancel();            
        }
    }