src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Workspace__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>This text will come at top left side.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Workspaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Workspaces_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>html_description__c</fullName>
        <label>Presentation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>subproject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subproject</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Workspaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Presentation</label>
    <nameField>
        <label>Headline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Presentation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WorkSpaceExtensionControllerTest.cls
/****************************************************************
Class Name: WorkSpaceExtensionControllerTest 
Author:Chaithanya daggumati     Last modified by: G Janardhanreddy
Date: 21/7/2014                 Date: 19/3/2015  
********©2013 Musqot marketing technology Pvt ltd ****************/
@isTest
public class WorkSpaceExtensionControllerTest{
    static testMethod void WorkSpaceExtension(){       
        Project__c objProj = new Project__c();
        objProj.Name='Plan';
        objProj.Starts_Date__c=Date.Today();
        objProj.Ends_Date__c=Date.Today();
        System.assertEquals('Plan',objProj.Name);
        insert objProj ;
        
        Subproject__c sb=new Subproject__c();
        sb.Name='sub';
        sb.musqot__Parent_project__c=objProj.id;
        System.assertEquals('sub',sb.Name);
        insert sb; 
        
        Marketing_activity__c objmarkact = new Marketing_activity__c();
        objmarkact .Name = 'test';
        objmarkact .Starts_date__c = Date.Today();
        objmarkact .Ends_date__c = Date.Today();
        objmarkact .Description__c = 'testarea';
        System.assertEquals('test',objmarkact .Name);
        insert objmarkact ;
        
        Workspace__c objwsp = new Workspace__c();
        objwsp.Name = 'test';
        objwsp.ProjectName__c =objProj.id;
        objwsp.subproject__c =sb.id;
        objwsp.musqot__Marketing_activity__c=objmarkact.id;
        objwsp.Description__c = 'desc';
        objwsp.musqot__Marketing_activity__c=objmarkact.id;
        objwsp.html_description__c = 'htdesc';
        System.assertEquals('test',objwsp.Name);
        insert objwsp;
        
        //PageReference pageRef = Page.SubProject;
        //Test.setCurrentPage(pageRef);  
        //ApexPages.currentPage().getParameters().put('projectid',sb.id);
        ApexPages.currentPage().getParameters().put('plnId', objProj.id);
       // ApexPages.currentPage().getParameters().put('markId', objmarkact.id);
        ApexPages.currentPage().getParameters().put('Id', objwsp.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objwsp);
        test.startTest();
        WorkSpaceExtensionController wspec = new WorkSpaceExtensionController(sc); 
        wspec.Save();
        wspec.cancel();
        wspec.getRedirectToTemplate();        
        wspec.redirectToTemplate();
        test.stopTest();
    }
    static testMethod void WorkSpaceExtension1(){       
        Project__c p = new Project__c();
        p.Name='Plan';
        p.Starts_Date__c=Date.Today();
        P.Ends_Date__c=Date.Today();
        System.assertEquals('Plan',p.Name);
        insert p;
        
        Subproject__c objsb=new Subproject__c();
        objsb.Name='sub';
        objsb.musqot__Parent_project__c=p.id;
        System.assertEquals('sub',objsb.Name);
        insert objsb;
        
        Marketing_activity__c objmarkact = new Marketing_activity__c();
        objmarkact .Name = 'test';
        objmarkact .Starts_date__c = Date.Today();
        objmarkact .Ends_date__c = Date.Today();
        objmarkact .Description__c = 'testarea';
        System.assertEquals('test',objmarkact .Name);
        insert objmarkact ;
        
        Workspace__c objwsp = new Workspace__c();
        objwsp.Name = 'test';
       // objwsp.ProjectName__c =p.id;
        objwsp.subproject__c =objsb.id;
        objwsp.musqot__Marketing_activity__c=objmarkact.id;
        objwsp.Description__c = 'desc';
        objwsp.html_description__c = 'htdesc';
        System.assertEquals('test',objwsp.Name);
        insert objwsp; 
     
        ApexPages.currentPage().getParameters().put('projectid',objsb.id);
        ApexPages.currentPage().getParameters().put('Id', objwsp.id);
        ApexPages.StandardController sc = new ApexPages.standardController(p);
        test.startTest();
        WorkSpaceExtensionController wspec1 = new WorkSpaceExtensionController();
        WorkSpaceExtensionController wspec = new WorkSpaceExtensionController(sc);
        PageReference pageRef = Page.ProjectDetails;
        Test.setCurrentPage(pageRef);  
        try{
            wspec.Save();
        }catch(Exception e){}
        wspec.cancel();
        wspec.getRedirectToTemplate();        
        wspec.redirectToTemplate();
        test.stopTest();
    }
    static testMethod void WorkSpaceExtension2(){       
        Project__c p = new Project__c();
        p.Name='Plan';
        p.Starts_Date__c=Date.Today();
        P.Ends_Date__c=Date.Today();
        System.assertEquals('Plan',p.Name);
        insert p;
        Subproject__c sb=new Subproject__c();
        sb.Name='sub';
        System.assertEquals('sub',sb.Name);
        insert sb;
         
        Marketing_activity__c objmarkact = new Marketing_activity__c();
        objmarkact .Name = 'test';
        objmarkact .Starts_date__c = Date.Today();
        objmarkact .Ends_date__c = Date.Today();
        objmarkact .Description__c = 'testarea';
        System.assertEquals('test',objmarkact .Name);
        insert objmarkact ;
        Workspace__c objwsp = new Workspace__c();
        objwsp.Name = 'test';
        objwsp.ProjectName__c =p.id;
        objwsp.subproject__c =sb.id;
        objwsp.Description__c = 'desc';
        objwsp.html_description__c = 'htdesc';
        System.assertEquals('test',objwsp.Name);
        insert objwsp;
        //ApexPages.currentPage().getParameters().put('plnId',p.id);
        ApexPages.currentPage().getParameters().put('markId', objmarkact.id);
        //ApexPages.currentPage().getParameters().put('SubProjectid', sb.id);
        ApexPages.currentPage().getParameters().put('Id', objwsp.id);
        ApexPages.StandardController sc = new ApexPages.standardController(sb);
        test.startTest();
        WorkSpaceExtensionController wspec1 = new WorkSpaceExtensionController();
        WorkSpaceExtensionController wspec = new WorkSpaceExtensionController(sc);
        PageReference pageRef = Page.Marketingactivity;
        Test.setCurrentPage(pageRef);  
        try{
            wspec.Save();
        }catch(Exception e){}
        wspec.cancel();
        wspec.getRedirectToTemplate();        
        wspec.redirectToTemplate();
        test.stopTest();
   
    } 
    static testMethod void WorkSpaceExtension3(){       
        Project__c p = new Project__c();
        p.Name='Plan';
        p.Starts_Date__c=Date.Today();
        P.Ends_Date__c=Date.Today();
        System.assertEquals('Plan',p.Name);
        insert p;
        Subproject__c sb=new Subproject__c();
        sb.Name='sub';
        System.assertEquals('sub',sb.Name);
        insert sb;
         
        Marketing_activity__c objmarkact = new Marketing_activity__c();
        objmarkact .Name = 'test';
        objmarkact .Starts_date__c = Date.Today();
        objmarkact .Ends_date__c = Date.Today();
        objmarkact .Description__c = 'testarea';
        System.assertEquals('test',objmarkact .Name);
        insert objmarkact ;
        Workspace__c objwsp = new Workspace__c();
        objwsp.Name = 'test';
        objwsp.ProjectName__c =p.id;
        objwsp.subproject__c =sb.id;
        objwsp.musqot__Marketing_activity__c=objmarkact.id;
        objwsp.Description__c = 'desc';
        objwsp.html_description__c = 'htdesc';
        System.assertEquals('test',objwsp.Name);
        insert objwsp;
        //ApexPages.currentPage().getParameters().put('plnId',p.id);
        ApexPages.currentPage().getParameters().put('marktingid', objmarkact.id);
        ApexPages.currentPage().getParameters().put('SubProjectid', sb.id);
        ApexPages.currentPage().getParameters().put('Id', objwsp.id);
        ApexPages.StandardController sc = new ApexPages.standardController(sb);
        test.startTest();
        WorkSpaceExtensionController wspec1 = new WorkSpaceExtensionController();
        WorkSpaceExtensionController wspec = new WorkSpaceExtensionController(sc);
        PageReference pageRef = Page.Marketingactivity;
        Test.setCurrentPage(pageRef);  
        try{
            wspec.Save();
        }catch(Exception e){}
        wspec.cancel();
        wspec.getRedirectToTemplate();        
        wspec.redirectToTemplate();
        wspec.Save2();
        wspec.cancel2();
        test.stopTest();
        
    } 
 }