src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Members__c.object
<CustomObject>
    <description>Member in a project/sub project</description>
    <fields>
        <fullName>Email_del__c</fullName>
        <formula>ProjUsers__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role in Project</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Email__c</fullName>
        <label>Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member set name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_type__c</fullName>
        <label>User type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal user</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communities user</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/plantype__c.object
<CustomObject>
    <fields>
        <fullName>Barcolor__c</fullName>
        <description>sample number after # hex color</description>
        <label>Barcolor</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <inlineHelpText>Enter a hexadecimal color (excluding #)</inlineHelpText>
        <label>Color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <label>Plan type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MemberEditControllerTest.cls
/*******************************************************
Class Name: MemberEditControllerTest
Author:Chaithanya daggumati        Last modified by: Chaithanya daggumati
Date :25/8/2014                   Date : 19/3/2105                    
********©2013 Musqot marketing technology Pvt ltd *******/

@isTest(seeAllData=true)
    public class MemberEditControllerTest{
    static testMethod void MemberEditController(){
    
    Members__c objmemberedit = new Members__c();
    objmemberedit .User_Email__c = 'test';
    //objmemberedit .Email_del__c = 'test';
    System.assertEquals('test', objmemberedit .User_Email__c);
    insert objmemberedit ; 
    
    ApexPages.currentPage().getParameters().put('id', objmemberedit.id);
    ApexPages.currentPage().getParameters().put('mbrId', objmemberedit.id);
    ApexPages.StandardController sc = new ApexPages.standardController(objmemberedit );
    
    MemberEditController memeditcont = new MemberEditController(sc);
    memeditcont.Save();
    memeditcont.deleteMember();
     memeditcont.mbrRole='test';
    memeditcont.Cancel();  
    }    
static testMethod void MemberEditController1(){
    Profile p = [select id from profile where name='System Administrator']; 
    User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id,
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
    insert objUser ;
    Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
    Plantype__c pt = new Plantype__c();
    pt.Barcolor__c = '6E766F';
    pt.Name = 'Zuri';
    System.assertEquals('Zuri', pt.name);
    insert pt;
    
    Project__c prj = new Project__c ();
    prj.Name='ITC';
    prj.Plantype__c= pt.Id;
    prj.Ends_date__c = system.toDay().addDays(3);
    prj.Starts_date__c= system.toDay();
    prj.Status__c = 'In Progress';
    prj.OwnerId=plm.musqot__userid__c;
    System.assertEquals('ITC', prj.name);         
    insert prj;
    
    Project_type__c prjType = new Project_type__c();
    prjType.Name = 'Business';
    prjType.Color__c = 'FFFF01';
    System.assertEquals('Business', prjType.name);
    insert prjType; 
    
    Subproject__c subPrj = new Subproject__c();         
    subPrj.Name='ITC Project';
    subPrj.Parent_project__c = prj.Id;
    subPrj.Ends_date__c = system.toDay().addDays(3);
    subPrj.Starts_date__c= system.toDay();
    subPrj.Status__c = 'In Progress'; 
    subPrj.Project_type__c = prjType.Id;
    System.assertEquals('ITC Project', subPrj.name);     
    insert subPrj;       
    
    Members__c objmemberedit = new Members__c();
    objmemberedit .User_Email__c = 'test';
    //objmemberedit .Email_del__c = 'test';
    objmemberedit.ProjMembers__c = prj.Id;
    System.assertEquals('test', objmemberedit.User_Email__c);
    insert objmemberedit ;     
    
    ApexPages.currentPage().getParameters().put('planid', prj.id);
    ApexPages.currentPage().getParameters().put('mbrId', objmemberedit.id);
    ApexPages.StandardController sc = new ApexPages.standardController(objmemberedit );
    test.startTest();
    MemberEditController memeditcont = new MemberEditController(sc);
    memeditcont.Save();
    memeditcont.deleteMember();
     memeditcont.mbrRole='test';
    memeditcont.Cancel();    
    }    
 static testMethod void MemberEditController2(){
    Profile p = [select id from profile where name='System Administrator']; 
    User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id,
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
    insert objUser ;
     Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
    Plantype__c pt = new Plantype__c();
    pt.Barcolor__c = '6E766F';
    pt.Name = 'Zuri';
    System.assertEquals('Zuri', pt.name);
    insert pt;
    
    Project__c prj = new Project__c ();
    prj.Name='ITC';
    prj.Plantype__c= pt.Id;
    prj.Ends_date__c = system.toDay().addDays(3);
    prj.Starts_date__c= system.toDay();
    prj.Status__c = 'In Progress';
    prj.OwnerId=plm.musqot__userid__c;
    System.assertEquals('ITC', prj.name);         
    insert prj;
    
    Project_type__c prjType = new Project_type__c();
    prjType.Name = 'Business';
    prjType.Color__c = 'FFFF01';
    System.assertEquals('Business', prjType.name);
    insert prjType; 
    
    Subproject__c subPrj = new Subproject__c();         
    subPrj.Name='ITC Project';
    subPrj.Parent_project__c = prj.Id;
    subPrj.Ends_date__c = system.toDay().addDays(3);
    subPrj.Starts_date__c= system.toDay();
    subPrj.Status__c = 'In Progress'; 
    subPrj.Project_type__c = prjType.Id;
    System.assertEquals('ITC Project', subPrj.name);     
    insert subPrj;       
    
    Members__c objmemberedit = new Members__c();
    objmemberedit .User_Email__c = 'test';
    //objmemberedit .Email_del__c = 'test';
    objmemberedit.SubProjMembers__c = subprj.Id;
    System.assertEquals('test', objmemberedit .User_Email__c);
    insert objmemberedit ;    
    
    ApexPages.currentPage().getParameters().put('subid', subPrj.id);
    ApexPages.currentPage().getParameters().put('mbrId', objmemberedit.id);
    ApexPages.StandardController sc = new ApexPages.standardController(objmemberedit );
    test.startTest();
    MemberEditController memeditcont = new MemberEditController(sc);
    memeditcont.Save();
    memeditcont.deleteMember();
     memeditcont.mbrRole='test';
    memeditcont.Cancel();  
 	}  
  static testMethod void MemberEditController3(){
  	Profile p = [select id from profile where name='System Administrator']; 
    User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id,
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
    insert objUser ;
     Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);  
    Plantype__c pt = new Plantype__c();
    pt.Barcolor__c = '6E766F';
    pt.Name = 'Zuri';
    System.assertEquals('Zuri', pt.name);
    insert pt;
    
    Project__c prj = new Project__c ();
    prj.Name='ITC';
    prj.Plantype__c= pt.Id;
    prj.Ends_date__c = system.toDay().addDays(3);
    prj.Starts_date__c= system.toDay();
    prj.Status__c = 'In Progress';
    prj.OwnerId=plm.musqot__userid__c;
    System.assertEquals('ITC', prj.name);         
    insert prj;
    
    Project_type__c prjType = new Project_type__c();
    prjType.Name = 'Business';
    prjType.Color__c = 'FFFF01';
    System.assertEquals('Business', prjType.name);
    insert prjType; 
    
    Subproject__c subPrj = new Subproject__c();         
    subPrj.Name='ITC Project';
    subPrj.Parent_project__c = prj.Id;
    subPrj.Ends_date__c = system.toDay().addDays(3);
    subPrj.Starts_date__c= system.toDay();
    subPrj.Status__c = 'In Progress'; 
    subPrj.Project_type__c = prjType.Id;
    System.assertEquals('ITC Project', subPrj.name);     
    insert subPrj;    
    
    Marketing_activity__c objMarketingact=new Marketing_activity__c();
    objMarketingact.Name='test';
    objMarketingact.Description__c='tdescriptionest';
    objMarketingact.Status__c='completed';
    System.assertEquals('test', objMarketingact.name);
    insert objMarketingact;
    
    
    Members__c objmemberedit = new Members__c();
    objmemberedit .User_Email__c = 'test';
    //objmemberedit .Email_del__c = 'test';
    objmemberedit.SubProjMembers__c = subprj.Id;
    System.assertEquals('test', objmemberedit .User_Email__c);
    insert objmemberedit ;    
    
    ApexPages.currentPage().getParameters().put('mrk', objMarketingact.id);
    ApexPages.currentPage().getParameters().put('mbrId', objmemberedit.id);
    ApexPages.StandardController sc = new ApexPages.standardController(objMarketingact );
    
    MemberEditController memeditcont = new MemberEditController(sc);
    memeditcont.Save();
    memeditcont.deleteMember();
   memeditcont.mbrRole='test';
    
    memeditcont.Cancel();  
    }    
}