src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Members__c.object
<CustomObject>
    <description>Member in a project/sub project</description>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member set name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Post_Install__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Is_Approval_Crated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Approval Crated</label>
        <type>Checkbox</type>
    </fields>
    <label>Post Install</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Workspace__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Workspaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>subproject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subproject</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Workspaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Presentation</label>
    <nameField>
        <label>Headline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Presentation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MusqotAdminPageController.cls
/************************************************************
Class Name: MusqotAdminPageController 
Author: Nagaraju         Last modified by: Chaithanya daggumati
Date: 23/7/2014          Date: 19/3/2015  
********©2013 Musqot marketing technology Pvt ltd ************/
public with sharing class MusqotAdminPageController {
    public String getObj() {
        return null;
    }
    public Map<String,String> objInfo{get;set;}
    public String objName{get;set;}
    public boolean shwSec{get;set;}
    String tabInFocus;
    String tabId;
    public Boolean showInstallProcess{get;set;}
    public list<FiscalYearSettings> orgFiscaltYearRec;
    public boolean defaultTabShow{get;set;}
    public string fiscalYearURL{get;set;}
    public MusqotAdminPageController (){
        shwSec = false;        
        tabInFocus = System.currentPageReference().getParameters().get('tab');
        Post_Install__c pi = Post_Install__c.getInstance('Amount Approval');
        showInstallProcess = pi.Is_Approval_Crated__c; 
        defaultTabShow=true;
        orgFiscaltYearRec=[SELECT Id, Name, YearType FROM FiscalYearSettings LIMIT 1];
        if(orgFiscaltYearRec.size()==0){
              defaultTabShow=false;
              ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please defined Fiscal Year according to your organization');
              ApexPages.addMessage(myMsg); 
              
        }
        string s=URL.getSalesforceBaseUrl().toExternalForm();
        fiscalYearURL=s+'/_ui/core/fiscalyear/FiscalYearSetup/d?setupid=ForecastFiscalYear';
     }
    /******************************************
     getTabInFocus(): redirect to paricular tab
    *******************************************/
    public String getTabInFocus() {
        return tabInFocus;
    }
   
    public void setTabInFocus(String s ) {
        this.tabInFocus = s;
    }
    /*************************************
     getObjNames():  getting  object names 
    **************************************/
    public Map<String,String> getObjNames(){
        objInfo =  new Map<String,String>();        
        objInfo.put('Project__c','Plan');
        objInfo.put('Subproject__c','Project');    
        objInfo.put('Workspace__c','Workspaces');
        objInfo.put('Marketing_activity__c','Marketing activity');
        objInfo.put('Members__c','Members');
        objInfo.put('Task','Tasks');
        objInfo.put('createApprovalProcess','createApprovalProcess');
        return objInfo;
    }
    /***************************************
     showRecords():  show the object records  
    ****************************************/
    public pageReference showRecords(){
        if(objName==null){
            objName = 'Project_type__c';    
        }
        else{
            objName = ApexPages.currentPage().getParameters().get('oName');
        }
        shwSec = true;
        return null;    
        }
    Public PageReference redirectToMusqotFiscalYearPage(){
        string s=URL.getSalesforceBaseUrl().toExternalForm();
        PageReference pageRef= new PageReference(s+'/_ui/core/fiscalyear/FiscalYearSetup/d?setupid=ForecastFiscalYear');
        pageRef.setredirect(true);
        return pageRef;
    }    
    }