src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing activity</label>
        <referenceTo>Marketing_activity__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_type__c</fullName>
        <label>User type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal user</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communities user</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/plantype__c.object
<CustomObject>
    <fields>
        <fullName>Barcolor__c</fullName>
        <description>sample number after # hex color</description>
        <label>Barcolor</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <inlineHelpText>Enter a hexadecimal color (excluding #)</inlineHelpText>
        <label>Color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <label>Plan type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AttachmentUploadControllerTest.cls
/*********************************************************
Class Name: AttachmentUploadControllerTest
Author:Nagaraju G         Last modified by:G Janardhanreddy
Date: Nagaraju G             Date:18/03/2015
********©2013 Musqot marketing technology Pvt ltd ********/
@isTest(seeAllData=true)
public class AttachmentUploadControllerTest{
    static testMethod void AttachmentUploadControllerMethod4(){
        Profile p = [select id from profile where name='System Administrator']; 
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id, 
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ; 
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Plantype__c objpt = new Plantype__c();
        objpt.Barcolor__c = '6E766F';
        objpt.Name = 'Zuri';
        System.assertEquals('Zuri', objpt.name);
        insert objpt;
        Project__c objprj = new Project__c ();
        objprj.Name='ITC';
        objprj.Plantype__c= objpt.Id;
        objprj.Ends_date__c = system.toDay().addDays(3);
        objprj.Starts_date__c= system.toDay();
        objprj.Status__c = 'In Progress';
        objPrj.ownerid =plm.userid__c;
        System.assertEquals('ITC', objprj.name);         
        insert objprj;
        Project_type__c objprjType = new Project_type__c();
        objprjType.Name = 'Business';
        objprjType.Color__c = 'FFFF01';
        System.assertEquals('Business', objprjType.name);
        insert objprjType; 
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = objprj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        subPrj.Project_type__c = objprjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        Attachment objatt=new Attachment();
        objatt.name='test';
        objatt.ParentId=objprj.id;
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        objatt.body = bodyBlob;
        objatt.ContentType='text';
        objatt.Description='test';
        System.assertEquals(objatt.ParentId, objprj.id); 
        insert objatt;
        PageReference pageRef = new PageReference('/apex/projectdetails?id=' + objprj .Id);  
        test.setCurrentPage(pageRef);  
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact;    
        ApexPages.currentPage().getParameters().put('plnId', objprj.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objatt);
        test.startTest();
        AttachmentUploadController objAttachment = new AttachmentUploadController ();           
        try{           
            objAttachment.upload();    
        }catch(exception e){}   
        objAttachment.cancel();                  
    }    
    static testMethod void AttachmentUploadControllerMethod1(){
        Profile p = [select id from profile where name='System Administrator']; 
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id, 
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ; 
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Plantype__c objpt = new Plantype__c();
        objpt.Barcolor__c = '6E766F';
        objpt.Name = 'Zuri';
        System.assertEquals('Zuri', objpt.name);
        insert objpt;
        Project__c objprj = new Project__c ();
        objprj.Name='ITC';
        objprj.Plantype__c= objpt.Id;
        objprj.Ends_date__c = system.toDay().addDays(3);
        objprj.Starts_date__c= system.toDay();
        objprj.Status__c = 'In Progress';
        objPrj.ownerid =plm.userid__c;
        System.assertEquals('ITC', objprj.name);         
        insert objprj;
        Project_type__c objprjType = new Project_type__c();
        objprjType.Name = 'Business';
        objprjType.Color__c = 'FFFF01';
        System.assertEquals('Business', objprjType.name);
        insert objprjType; 
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = objprj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        subPrj.Project_type__c = objprjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
         Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact; 
        Attachment objatt=new Attachment();
        objatt.name='test';
        objatt.ParentId=subPrj.id;
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        objatt.body = bodyBlob;
        objatt.ContentType='text';
        objatt.Description='test';
        System.assertEquals(objatt.ParentId, subPrj.id); 
        insert objatt;
          
        ApexPages.currentPage().getParameters().put('subprojectid', subPrj.id);
        ApexPages.StandardController sc = new ApexPages.standardController(subPrj);
        test.startTest();
        AttachmentUploadController objAttachment = new AttachmentUploadController ();           
        try{           
            objAttachment.upload();    
        }catch(exception e){}    
        objAttachment.cancel();                 
    }
    static testMethod void AttachmentUploadControllerMethod2(){
        Profile p = [select id from profile where name='System Administrator']; 
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id, 
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ; 
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Plantype__c objpt = new Plantype__c();
        objpt.Barcolor__c = '6E766F';
        objpt.Name = 'Zuri';
        System.assertEquals('Zuri', objpt.name);
        insert objpt;
        Project__c objprj = new Project__c ();
        objprj.Name='ITC';
        objprj.Plantype__c= objpt.Id;
        objprj.Ends_date__c = system.toDay().addDays(3);
        objprj.Starts_date__c= system.toDay();
        objprj.Status__c = 'In Progress';
        objPrj.ownerid =plm.userid__c;
        System.assertEquals('ITC', objprj.name);         
        insert objprj;
        Project_type__c objprjType = new Project_type__c();
        objprjType.Name = 'Business';
        objprjType.Color__c = 'FFFF01';
        System.assertEquals('Business', objprjType.name);
        insert objprjType; 
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = objprj.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        subPrj.Project_type__c = objprjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
        Marketing_activity__c objMarketingact=new Marketing_activity__c();
        objMarketingact.Name='test';
        objMarketingact.Description__c='tdescriptionest';
        objMarketingact.Status__c='completed';
        System.assertEquals('test', objMarketingact.name);
        insert objMarketingact; 
        Attachment objatt=new Attachment();
        objatt.name='test';
        objatt.ParentId=objMarketingact.id;
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        objatt.body = bodyBlob;
        objatt.ContentType='text';
        objatt.Description='test';
        System.assertEquals(objatt.ParentId, objMarketingact.id); 
        insert objatt;
           
        ApexPages.currentPage().getParameters().put('mrkId', objMarketingact.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objMarketingact);
        test.startTest();
        AttachmentUploadController objAttachment = new AttachmentUploadController ();           
        try{           
            objAttachment.upload();    
        }catch(exception e){}   
        objAttachment.cancel();                 
    }
 static testMethod void Attachmentupload(){
        Profile p = [select id from profile where name='System Administrator']; 
        User objUser = new User(alias = 'stan', email='standarduser@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id, 
                                timezonesidkey='America/Los_Angeles', username='standarduser06@test.com');
        insert objUser ; 
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=objUser.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        Project__c objprj = new Project__c ();
        objprj.Name='ITC';        
        objprj.Ends_date__c = system.toDay().addDays(3);
        objprj.Starts_date__c= system.toDay();
        objprj.Status__c = 'In Progress';
        objPrj.ownerid =plm.userid__c;
        System.assertEquals('ITC', objprj.name);         
        insert objprj;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';        
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress';         
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;
     
        Attachment objatt=new Attachment();
        objatt.name='test'; 
        objatt.ParentId=subPrj.id;       
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        objatt.body = bodyBlob;
        objatt.ContentType='application/pdf';
        objatt.Description='test';
        System.assertEquals('test', objatt.name); 
        insert objatt;
           
        ApexPages.currentPage().getParameters().put('plnId', objprj.id);
        ApexPages.currentPage().getParameters().put('subprojectid', subPrj.id);
        ApexPages.StandardController sc = new ApexPages.standardController(objprj);      
        AttachmentUploadController Atta = new AttachmentUploadController();
        Atta.contentType='application/pdf';
        try{ 
        Atta.fileNmaeWithExtension='.txt';          
        Atta.upload();    
        }catch(exception e){}                      
    }
}