src/objects/Marketing_activity__c.object
<CustomObject>
    <customHelpPage>Marketinghelppage</customHelpPage>
    <description>Event object to hold timeframe and event-cat</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <label>End date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Marketing_activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <label>Start date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing activity</label>
    <nameField>
        <label>Marketingactivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Trigger_Task_Emailtests.cls
@isTest(seeAllData=true)
    public class Trigger_Task_Emailtests{
           static testMethod void TaskController(){ 
           Profile p=[SELECT Id From Profile WHERE Name='System Administrator'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert u2;
            
            Project__c objproject = new Project__c ();
            objproject.Name='test';
           //objproject.Project_type__c='test';
            objproject.Starts_date__c= System.now().date();
            objproject.Ends_date__c= System.now().date();
            System.assertEquals('test', objproject.name);
            insert objproject;
            
            Task objtask = new Task();      
            objtask.Task_name__c = 'testname'; 
            objtask.OwnerId=u2.id;
            objtask.musqot__sendEmail__c=true;
            objtask.WhatId=objproject.id;
            objtask.ActivityDate =system.toDay();
            objtask.Status='Deferred';
            objtask.Allocated_h__c=2;
            objtask.Outcome_h__c=2;
            objtask.Task_description__c='test record';
            objtask.Task_name__c='Testtask';                     
            insert objtask ;
        System.assertEquals('Testtask', objtask .Task_name__c); 
        
     }
      static testMethod void TaskController1(){
            
           Profile p=[SELECT Id From Profile WHERE Name='System Administrator'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert u2;
            
            Project__c objproject = new Project__c ();
            objproject.Name='test';
           //objproject.Project_type__c='test';
            objproject.Starts_date__c= System.now().date();
            objproject.Ends_date__c= System.now().date();
            System.assertEquals('test', objproject.name);
            insert objproject;
            
            Subproject__c objsp = new Subproject__c ();
            objsp.name = 'testname';
            objsp.Description__c = 'sampdesc';
            objsp.Starts_date__c = date.today();
            objsp.Ends_date__c = date.today()+10;
            //objsp.Project_del__c = objspr.id;
            objsp.Parent_project__c = objproject.id;
            objsp.Status__c = 'Notstarted';
           //objsp.user__c = u2.id;        
            System.assertEquals('testname', objsp .name);
            insert objsp ; 
            
            Task objtask = new Task();      
            objtask.Task_name__c = 'testname'; 
            objtask.OwnerId=u2.id;
            objtask.WhatId=objsp.id;
            objtask.musqot__sendEmail__c=true;
            objtask.ActivityDate =system.toDay();
            objtask.Status='Deferred';
            objtask.Allocated_h__c=2;
            objtask.Outcome_h__c=2;
            objtask.Task_description__c='test record';
            objtask.Task_name__c='Testtask';                     
            insert objtask ;
        System.assertEquals('Testtask', objtask .Task_name__c); 
     }
      static testMethod void TaskController2(){
            
           Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert u2;
            
            Project__c objproject = new Project__c ();
            objproject.Name='test';
           //objproject.Project_type__c='test';
            objproject.Starts_date__c= System.now().date();
            objproject.Ends_date__c= System.now().date();
            System.assertEquals('test', objproject.name);
            insert objproject;
            Subproject__c objspr = new Subproject__c ();
            objspr.name = 'testname';
            objspr.Description__c = 'sampdesc';
            objspr.Starts_date__c = date.today();
            objspr.Ends_date__c = date.today();
            objspr.Status__c = 'Notstarted';    
            System.assertEquals('testname', objspr.name);
            insert objspr; 
            
            Subproject__c objsp = new Subproject__c ();
            objsp.name = 'testname';
            objsp.Description__c = 'sampdesc';
            objsp.Starts_date__c = date.today();
            objsp.Ends_date__c = date.today()+10;
            objsp.Project_del__c = objspr.id;
            objsp.Parent_project__c = objproject.id;
            //objsp.Project_type__c = 'prtyp';
            objsp.Status__c = 'Notstarted';
           //objsp.user__c = u2.id;        
            System.assertEquals('testname', objsp .name);
            insert objsp ; 
                    
            
            Marketing_activity__c objMarketingact=new Marketing_activity__c();
            objMarketingact.Name='test';
            objMarketingact.Description__c='tdescriptionest';
            objMarketingact.Status__c='completed';
            objMarketingact.musqot__Project__c=objsp.id;
            System.assertEquals('test', objMarketingact.name);
            insert objMarketingact;
            
            Task objtask = new Task();      
            objtask.Task_name__c = 'testname'; 
            objtask.OwnerId=u2.id;
            objtask.WhatId=objMarketingact.id;
            objtask.ActivityDate =system.toDay();
            objtask.Status='Deferred';
            objtask.Allocated_h__c=2;
            objtask.Outcome_h__c=2;
            objtask.musqot__sendEmail__c=true;
            objtask.Task_description__c='test record';
            objtask.Task_name__c='Testtask';                     
            insert objtask ;
        System.assertEquals('Testtask', objtask .Task_name__c); 
      
     }
     static testMethod void TaskController3(){
            
           Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
           User u2 =new User( Alias = 'newUser1' ,
           Email ='newuser123@testorg.com',
           EmailEncodingKey = 'UTF-8',
           LastName = 'Testing',
           LanguageLocaleKey='en_US',
           LocaleSidKey='en_US', 
           UserName='newuser1234@testorg.com',
           ProfileId=p.Id,
           TimeZoneSidKey = 'America/Los_Angeles');
           insert u2;
            
            Project__c objproject = new Project__c ();
            objproject.Name='test';
           //objproject.Project_type__c='test';
            objproject.Starts_date__c= System.now().date();
            objproject.Ends_date__c= System.now().date();
            System.assertEquals('test', objproject.name);
            insert objproject;
            Subproject__c objspr = new Subproject__c ();
            objspr.name = 'testname';
            objspr.Description__c = 'sampdesc';
            objspr.Starts_date__c = date.today();
            objspr.Ends_date__c = date.today();
            objspr.Status__c = 'Notstarted';    
            System.assertEquals('testname', objspr.name);
            insert objspr; 
            
            Subproject__c objsp = new Subproject__c ();
            objsp.name = 'testname';
            objsp.Description__c = 'sampdesc';
            objsp.Starts_date__c = date.today();
            objsp.Ends_date__c = date.today()+10;
            objsp.Project_del__c = objspr.id;
            objsp.Parent_project__c = objproject.id;
            //objsp.Project_type__c = 'prtyp';
            objsp.Status__c = 'Notstarted';
           //objsp.user__c = u2.id;        
            System.assertEquals('testname', objsp .name);
            insert objsp ; 
                    
            
            Marketing_activity__c objMarketingact=new Marketing_activity__c();
            objMarketingact.Name='test';
            objMarketingact.Description__c='tdescriptionest';
            objMarketingact.Status__c='completed';
            objMarketingact.musqot__Project__c=objsp.id;
            System.assertEquals('test', objMarketingact.name);
            insert objMarketingact;
            
            Task objtask = new Task();      
            objtask.Task_name__c = 'testname'; 
            objtask.OwnerId=u2.id;
            objtask.WhatId=objMarketingact.id;
            //objtask.ActivityDate =system.toDay();
            objtask.Status='Deferred';
            objtask.Allocated_h__c=2;
            objtask.Outcome_h__c=2;
            objtask.musqot__sendEmail__c=true;
            objtask.Task_description__c='test record';
            objtask.Task_name__c='Testtask';                     
            insert objtask ;
        System.assertEquals('Testtask', objtask .Task_name__c); 
      
     }

 }