src/objects/Members__c.object
<CustomObject>
    <description>Member in a project/sub project</description>
    <fields>
        <fullName>ProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role in Project</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Email__c</fullName>
        <label>Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member set name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmailUpdateByOwnerTest.cls
/*******************************************************
Class Name: EmailUpdateByOwnerTest
Author:G Janarhanreddy     Last modified by:G Janarhanreddy
Date:  25/7/2014           Date:19/03/2015
********©2013 Musqot marketing technology Pvt ltd *******/
@isTest(Seealldata = True)
public class EmailUpdateByOwnerTest
{
    static testMethod void EmailUpdateByOwner()
    {
        Profile p = [select id from profile where name='System Administrator']; 
        User objUser = new User(alias = 'stan', email='standarduser123@test.com', 
                                emailencodingkey='UTF-8', lastname='test', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p.Id, 
                                timezonesidkey='America/Los_Angeles', username='standarduser123@test.com');
        insert objUser ;
        
        User u=[SELECT ID,alias FROM User where id=:objUser.id];
        u.alias ='ram';
        update u;
        
        Members__c objmember = new Members__c ();
        //objmember.Name = 'Ram';
        objmember.ProjUsers__c = objUser.Id;
        objmember.Role__c='Member';
        objmember.User_Email__c ='standarduser123@test.com';
        insert objmember; 
        System.assertEquals('Member', objmember.Role__c);
        
        Members__c   Mems = [Select id,Name, ProjMembers__c, ProjUsers__c,ProjUsers__r.name, musqot__Email_del__c,SubProjMembers__c, Role__c, Type__c, User_Email__c FROM Members__c  where id =:objmember.id];                       
        update Mems ;                         
    }          
}