src/objects/Members__c.object
<CustomObject>
    <description>Member in a project/sub project</description>
    <fields>
        <fullName>Cost_center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost center</label>
        <referenceTo>Costcentre__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role in Project</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member set name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/costcentermembercls.cls
/*********************************************************************
Class Name: costcentermembercls
Author:Chaithanya daggumati        Last modified by: Chaithanya daggumati
Date: 12/11/2015                Date: 12/11/2015 
********©2013 Musqot marketing technology Pvt ltd *********************/
public with sharing class costcentermembercls{
    private ApexPages.StandardController sc;
    public String cosid{get;set;}
    public Members__c member{get;set;}
    public costcentermembercls(ApexPages.StandardController sc) {
        this.sc = sc;
        cosid = ApexPages.currentPage().getParameters().get('cosid');
        if(cosid<>null){
            member = new Members__c (Cost_center__c = cosid); 
        }        
    }    
    /*************************
    Save(): insert new Members  
    **************************/
    Public Pagereference Save(){
        try{
            Pagereference PR;
            if(cosid<>null){
                List<Members__c> mbrList = [select ID,Name,ProjUsers__c,Role__c,ProjUsers__r.Name from Members__c where Cost_center__c =:cosid];               
                Map<Id,Members__c> mbrMap = new Map<Id,Members__c>();
                for(Members__c m : mbrList){
                    mbrMap.put(m.ProjUsers__c,m);    
                }
                 
                if(mbrMap.containsKey(member.ProjUsers__c)){                    
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,Label.mem_member_exist);
                    ApexPages.addMessage(myMsg);    
                }
                else{ 
                    if (Members__c.sObjectType.getDescribe().isCreateable()){  
                    insert member;
                    }
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/Costcenterdetail?id='+EncodingUtil.urlEncode(cosid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('tb4','UTF-8');
                pr=new Pagereference (pageRef);
                }
            }
             return PR; 
        }
        catch(Exception ex){}      
        return null;
    }
    /****************************************
    cancel(): redirect to related parent page   
    *****************************************/
    Public Pagereference cancel(){        
        Pagereference PR;        
        if(cosid<>null){
                String tabId = System.currentPageReference().getParameters().get('tabId');
                string pageRef='/apex/Costcenterdetail?id='+EncodingUtil.urlEncode(cosid,'UTF-8')+'&tab='+EncodingUtil.urlEncode('tb4','UTF-8');
                pr=new Pagereference (pageRef); 
        }        
        return PR;
        }
    }