src/objects/Members__c.object
<CustomObject>
    <description>Member in a project/sub project</description>
    <fields>
        <fullName>ProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role in Project</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubProjMembers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Email__c</fullName>
        <label>Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member set name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExpenseController.cls
/*******************************************************
Class Name: ExpenseController	
Author:G Janardhanreddy     Last modified by:G Janarhanreddy
Date: 26/6/2014              Date:19/03/2015
********©2013 Musqot marketing technology Pvt ltd *******/
public with sharing class ExpenseController {
    private ApexPages.StandardController sc;
    public String projectid{get;set;}
    public String memberid{get;set;}
    public Members__c member{get;set;}
    public ExpenseController(ApexPages.StandardController sc) {
        this.sc = sc;
        projectid = ApexPages.currentPage().getParameters().get('SubProjectid');                     
        memberid= ApexPages.currentPage().getParameters().get('id');
        if(memberId<>''){
            try{
                member = [Select Id, Name, ProjMembers__c, ProjUsers__c, SubProjMembers__c, Role__c, User_Email__c FROM Members__c  where Id=:memberId ];
            }catch(exception e){}   
        }}
    public ExpenseController(){
        templateInfo = new Members__c();
        Members__c member = new Members__c (); 
    }
    Public Pagereference Save(){
        member = new Members__c (); 
        if (Members__c.sObjectType.getDescribe().isUpdateable())
        {
            update member;
        }
        Pagereference PR = new Pagereference('/apex/ProjectDetails?id='+EncodingUtil.urlEncode(projectid,'UTF-8'));
        return PR;
    }
    Public Pagereference cancel(){   
        Pagereference PR = new Pagereference('/apex/SubProject?id='+EncodingUtil.urlEncode(projectid,'UTF-8'));
        return PR;
    }
    public Members__c  templateInfo {get; set;} 
}