src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_type__c</fullName>
        <label>Milestone type</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reach on time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reach delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not reach</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Milestones (Target Project)</relationshipLabel>
        <relationshipName>Milestones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Socialmedia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Socialmedia</label>
        <referenceTo>socialmedia_settings__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_number__c</fullName>
        <label>Target_number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Targetdate__c</fullName>
        <label>Target date</label>
        <type>Date</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OAuthService__c.object
<CustomObject>
    <label>Socialmedia connection</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Socialmedia connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Social_media_data__c.object
<CustomObject>
    <fields>
        <fullName>Compound_Id__c</fullName>
        <externalId>true</externalId>
        <label>Compound Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Connection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OAuth service</label>
        <referenceTo>OAuthService__c</referenceTo>
        <relationshipLabel>Social media data</relationshipLabel>
        <relationshipName>Social_media_data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_likes__c</fullName>
        <label>Number of likes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_member__c</fullName>
        <label>Number of member</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_unik_visitor__c</fullName>
        <label>Number of unik visitor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Socialmedia_Settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Socialmedia Settings</label>
        <referenceTo>socialmedia_settings__c</referenceTo>
        <relationshipLabel>Social media data</relationshipLabel>
        <relationshipName>Social_media_data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Social media data</label>
    <nameField>
        <label>Social media name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social media data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/socialmedia_settings__c.object
<CustomObject>
    <description>The Name will show-up in the Performance Gantt view.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Performance, general</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Performance, project</fullName>
            </value>
            <value>
                <fullName>Performance, marketing activity</fullName>
            </value>
            <value>
                <fullName>Milestone</fullName>
            </value>
            <value>
                <fullName>Performance, costcenter</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Socialmedia Settings</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Socialmedia Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SocialMediaSettingMilestoneSchedulertest.cls
/***************************************************************
Class Name: SocialMediaSettingMilestoneSchedulertest
chaithanya daggumati      Last modified by: chaithanya daggumati
Date :16/10/2015           Date : 16/10/2015                    
********©2013 Musqot marketing technology Pvt ltd **************/

@isTest(seeAllData=true)
    public class SocialMediaSettingMilestoneSchedulertest{
        static testMethod void SocialMediaSettingMilestone(){
                 
        Project__c objproj = new Project__c();
        objproj .name = 'testname';
        objproj .Starts_date__c = System.now().date();
        objproj .Ends_date__c =  System.now().date()+5; 
        objproj .Description__c = 'sampdesc';
        System.assertEquals('testname', objproj .name);
        insert objproj;
        
        Subproject__c objsubproj = new Subproject__c();
        objsubproj .Name = 'test';
        objsubproj .musqot__Parent_project__c=objproj.id;
        objsubproj .Starts_date__c = Date.Today();
        objsubproj .Ends_date__c = Date.Today();
        objsubproj .Description__c = 'testdesc';
        System.assertEquals('test', objsubproj .Name);
        insert objsubproj ;
        
        OAuthService__c  OAuth=new OAuthService__c ();
        OAuth.Name='ffbook';
        OAuth.musqot__Authorization_Type__c='Requestheader';
        OAuth.musqot__Authorization_URL__c='https://www.facebook.com/dialog/oauth';
        OAuth.musqot__Response_Type__c='token';
        OAuth.musqot__Signature_Method__c='PLAINTEXT'; 
        OAuth.musqot__Bar_color__c='#333';   
        System.assertEquals('PLAINTEXT', OAuth.musqot__Signature_Method__c);
        insert OAuth;
        
        Socialmedia_settings__c OBJSocial=new Socialmedia_settings__c();
        OBJSocial.Name='facebook';
        OBJSocial.musqot__Import_rate__c='Hour';
        OBJSocial.musqot__Socialmedia_type__c='Facebook';
        OBJSocial.musqot__Watch_type__c='Likes / click';
        OBJSocial.musqot__Chart__c='Line charts';
        OBJSocial.musqot__Bar_color__c='#333';
        OBJSocial.musqot__Page_Id__c='87567567567';
        OBJSocial.musqot__Auto_import__c= true ;
        OBJSocial.musqot__Socialmedia__c=OAuth.id;
        OBJSocial.musqot__Bar_color__c=OAuth.musqot__Bar_color__c;
        OBJSocial.Type__c ='Milestone';
        System.assertEquals('facebook', OBJSocial.Name);
        insert OBJSocial;
        
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'reachontime';
        objmilestone.musqot__Plan__c=objproj.id;
        objmilestone.Project__c=objsubproj .id;
        objmilestone.Target_Project__c=objsubproj .id;
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_Socialmedia__c=OBJSocial.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        System.assertEquals('reachontime', objmilestone.name);
        insert objmilestone;
        
        Social_media_data__c smd = new Social_media_data__c();        
        smd.Compound_Id__c='auth';
        smd.Date__c = system.today();
        smd.Number_of_likes__c = 4;
        smd.Number_of_member__c=5;
        smd.Number_of_unik_visitor__c=6;
        smd.Connection__c=OAuth.id;
        smd.Socialmedia_Settings__c =OBJSocial.Id; 
        smd.Name = 'test';
        System.assertEquals('auth', smd.Compound_Id__c);              
        insert smd;
        
        SocialMediaSettingMilestoneScheduler socmileschedule = new SocialMediaSettingMilestoneScheduler();
        SchedulableContext sc;
        socmileschedule.execute(sc);
      }
 static testMethod void SocialMediaSettingMilestone1(){
         Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'reachontime';        
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = system.toDay().addDays(-7);
        //objmilestone.Target_Socialmedia__c=OBJSocial.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Not Reach';
        objmilestone.Target_number__c=5;
        System.assertEquals('reachontime', objmilestone.name);
        insert objmilestone; 
        
        SocialMediaSettingMilestoneScheduler socmileschedule = new SocialMediaSettingMilestoneScheduler();
        SchedulableContext sc;
        socmileschedule.execute(sc);                     
        }
 static testMethod void SocialMediaSettingMilestone2(){
        Socialmedia_settings__c OBJSocial=new Socialmedia_settings__c();
        OBJSocial.Name='facebook';       
        OBJSocial.musqot__Watch_type__c='Likes / click';       
        OBJSocial.Type__c ='Milestone';
        System.assertEquals('facebook', OBJSocial.Name);
        insert OBJSocial;
        
        Milestone__c objmilestone = new  Milestone__c();
        objmilestone.Name = 'reachontime';
        objmilestone.Description__c = 'testdesc';
        objmilestone.Targetdate__c = Date.Today();
        objmilestone.Target_Socialmedia__c=OBJSocial.id;
        objmilestone.Milestone_type__c =4;        
        objmilestone.Status__c ='Open';
        objmilestone.Target_number__c=5;
        System.assertEquals('reachontime', objmilestone.name);
        insert objmilestone;
        SocialMediaSettingMilestoneScheduler socmileschedule = new SocialMediaSettingMilestoneScheduler();
        SchedulableContext sc;
        socmileschedule.execute(sc);                     
        }
    }