src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Milestone_type__c</fullName>
        <label>Milestone type</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reach on time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reach delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not reach</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Socialmedia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Socialmedia</label>
        <referenceTo>socialmedia_settings__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_number__c</fullName>
        <label>Target_number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Targetdate__c</fullName>
        <label>Target date</label>
        <type>Date</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OAuthService__c.object
<CustomObject>
    <fields>
        <fullName>Auto_import__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is checked then the import will run every day into the enddate</inlineHelpText>
        <label>Auto import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>Today() + 365</defaultValue>
        <inlineHelpText>After this date will Musqot not collect data from this social media connection.</inlineHelpText>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Socialmedia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Socialmedia</label>
        <referenceTo>socialmedia_settings__c</referenceTo>
        <relationshipName>OAuth_services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Socialmedia connection</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Socialmedia connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Social_media_data__c.object
<CustomObject>
    <fields>
        <fullName>Connection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OAuth service</label>
        <referenceTo>OAuthService__c</referenceTo>
        <relationshipLabel>Social media data</relationshipLabel>
        <relationshipName>Social_media_data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_likes__c</fullName>
        <label>Number of likes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_member__c</fullName>
        <label>Number of member</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_unik_visitor__c</fullName>
        <label>Number of unik visitor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Socialmedia_Settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Socialmedia Settings</label>
        <referenceTo>socialmedia_settings__c</referenceTo>
        <relationshipLabel>Social media data</relationshipLabel>
        <relationshipName>Social_media_data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Social media data</label>
    <nameField>
        <label>Social media name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social media data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/socialmedia_settings__c.object
<CustomObject>
    <description>The Name will show-up in the Performance Gantt view.</description>
    <fields>
        <fullName>Auto_import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_date__c</fullName>
        <defaultValue>Today() + 365</defaultValue>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Socialmedia__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Socialmedia</label>
        <referenceTo>OAuthService__c</referenceTo>
        <relationshipLabel>Socialmedia Settings</relationshipLabel>
        <relationshipName>Socialmedia_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Performance, general</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Performance, project</fullName>
            </value>
            <value>
                <fullName>Performance, marketing activity</fullName>
            </value>
            <value>
                <fullName>Milestone</fullName>
            </value>
            <value>
                <fullName>Performance, costcenter</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Watch_type__c</fullName>
        <label>Watch type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Unique visitors</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Likes / click</fullName>
            </value>
            <value>
                <fullName>Members</fullName>
            </value>
            <value>
                <fullName>Unique visitor &amp; click/likes</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Socialmedia Settings</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Socialmedia Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SocialMediaSettingMilestoneScheduler.cls
/*******************************************************
Class Name: SocialMediaSettingMilestoneScheduler
Author: Narendra K Jha        Last modified by: Narendra K Jha
Date: Oct 15, 2015            Date: Oct 15, 2015
********©2015 Musqot marketing technology Pvt ltd *******/

global class SocialMediaSettingMilestoneScheduler Implements Schedulable {
   global void execute(SchedulableContext sc) {
         // do your logic here
         System.debug('scheduler test');
         List<socialmedia_settings__c> socialMediaList = new List<socialmedia_settings__c>();
         Set<socialmedia_settings__c> socialIds = new Set<socialmedia_settings__c>();
         List<musqot__Milestone__c> milstoneList = new List<musqot__Milestone__c>();
         date startdate ;
         date enddate;
         decimal total;
         decimal iProgress_value ;
         date toDay = system.today();
         List<id> connectionId = new List<id>();
         List<musqot__Milestone__c> updateMilestoneList = new List<musqot__Milestone__c>();
         id conId;
         AggregateResult[]  results; 
     
     
        List<Social_media_data__c> allSMsWithIds = [SELECT connection__c from Social_media_data__c limit 100000];
        for(Social_media_data__c s : allSMsWithIds){
            connectionId.add(s.connection__c);//to get update/insert record connection id from social data;
        }
        //to get social media setting records; 
        socialMediaList=[SELECT id, Socialmedia__c 
                         from socialmedia_settings__c 
                         where Socialmedia__c=:connectionId];
        for(socialmedia_settings__c soc:socialMediaList){
            socialIds.add(soc); //prepare list of social media setting ids;
        } 
        milstoneList=[SELECT Id, Name, Plan__c, Status__c, Milestone_type__c ,Target_Socialmedia__c,Target_Socialmedia__r.Socialmedia__c,Target_number__c,musqot__Targetdate__c ,Plan__r.Starts_date__c,Plan__r.Ends_date__c,Project__c,Project__r.Starts_date__c,Project__r.Ends_date__c
                     		,Target_Socialmedia__r.Watch_type__c 
                      FROM Milestone__c  
                      WHERE  Target_Socialmedia__c IN:socialIds and Milestone_type__c=3 limit 100];     
      
        for(musqot__Milestone__c m:milstoneList){
            if(m.Project__c==null){ 
                 startdate =m.Plan__r.Starts_date__c;
                 enddate=m.plan__r.Ends_date__c;
          
            }else{
                startdate =m.Project__r.Starts_date__c;
                enddate=m.Project__r.Ends_date__c;
           }
              conId=m.Target_Socialmedia__r.Socialmedia__c;
          }
        results=[SELECT sum(Number_of_likes__c) no_likes, sum(Number_of_unik_visitor__c) no_visitor,   Sum(Number_of_member__c)no_mem FROM Social_media_data__c 
                                WHERE  musqot__Connection__c=:conId AND  Date__c >=:startdate AND Date__c <=:enddate];
        for(musqot__Milestone__c m:milstoneList){
          for( AggregateResult ag:results){
               If (m.Target_Socialmedia__r.Watch_type__c=='Unique visitors'){
                    total=(Decimal)ag.get('no_visitor');
               }
               else if(m.Target_Socialmedia__r.Watch_type__c=='Likes / click'){
                    total+=(Decimal)ag.get('no_likes');
               } 
               else if(m.Target_Socialmedia__r.Watch_type__c=='Members'){
                   total+=(Decimal)ag.get('no_mem');  
               }
           }
           If(total >0 && m.Target_number__c > 0){
                iProgress_value = (total /m.Target_number__c)*100; //here calclute the iProgress_value 
                if(m.Targetdate__c>toDay && iProgress_value<100){
                    m.Status__c= 'Open'; 
                }
                else if(m.Targetdate__c>=toDay && iProgress_value>=100){
                    m.Status__c= 'Reach on time';  
                }
                else if(m.Targetdate__c<=toDay && iProgress_value<100){
                    m.Status__c= 'Not Reach';          
                }
                else if(m.Targetdate__c<=toDay && iProgress_value>=100){
                    m.Status__c= 'Reach Delayed'; 
                }          
   
          }
          else if(m.musqot__Targetdate__c<=toDay){
               m.Status__c='Not Reach';
          }
          else{
                m.Status__c= 'Open';
         }
             updateMilestoneList.add(m);
         update updateMilestoneList;//here update the list of milestone
     }
       
       
       // rescheduling job
       try{
           List<OAuthService__c> oAuths = [SELECT Id FROM OAuthService__c where auto_import__c = true and end_date__c > TODAY];
           List<socialmedia_settings__c> sms = [select id, name from socialmedia_settings__c 
                                                where Type__c = :'Milestone' and Socialmedia__c in :oAuths];
           if(sms.size() != 0) {
               Date tomorrowsDate = System.today().addDays(1);
               Integer day = tomorrowsDate.day();
               Integer month = tomorrowsDate.month();
               Integer year = tomorrowsDate.year();
               String SchTimer='0 0 1 '+day+' '+month+' ? '+year;   //  next day 1:00 AM
               System.schedule('SocialMediaSettingMilestoneSchedulerJob', SchTimer, new SocialMediaSettingMilestoneScheduler());
           }
       }catch(Exception e){
           System.debug('Exception : ' + e.getMessage());
       }
    }
}