src/objects/Musqot_member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_type__c</fullName>
        <label>User type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal user</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communities user</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Musqot_members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan member</label>
    <nameField>
        <label>Plan member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/plantype__c.object
<CustomObject>
    <fields>
        <fullName>Barcolor__c</fullName>
        <description>sample number after # hex color</description>
        <label>Barcolor</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fieldset__c</fullName>
        <description>This should be a choice from Plan field set name</description>
        <label>Fieldset</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlantypePageControllerTest.cls
/***********************************************************
Class Name: PlantypePageControllerTest
Author:Nagaraju           Last modified by:G Janardhan reddy
Date :18/7/2014           Date : 20/03/2015                    
********©2013 Musqot marketing technology Pvt ltd *********/

@isTest(seealldata=true)
public class PlantypePageControllerTest{
    static testMethod void insertplanty(){
        Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
     	User u2 =new User( Alias = 'newUser1' ,Email ='newuser123@testorg.com',EmailEncodingKey = 'UTF-8',LastName = 'Testing',
     	LanguageLocaleKey='en_US',LocaleSidKey='en_US', UserName='newuser1234@testorg.com',ProfileId=p.Id,TimeZoneSidKey = 'America/Los_Angeles');
     	insert u2; 
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        plantype__c objPlantype=new plantype__c ();    
        objPlantype.Name='test';    
        objPlantype.Barcolor__c ='test1';  
        objPlantype.Fieldset__c =null;  
        System.assertEquals('test', objPlantype.name);
        insert objPlantype;
        
        Project__c objproj = new Project__c();
        objproj .Name = 'test';
        objproj .Ends_date__c = system.toDay();
        objproj .Starts_date__c= system.toDay();
        objproj .Status__c = 'In Progress';
        objproj.ownerid=plm.userid__c;
        System.assertEquals('test', objproj .Name );         
        insert objproj;
        
        test.startTest();
        PageReference pageRef = Page.MusqotAdminPage;
        Test.setCurrentPage(pageRef); 
        ApexPages.currentPage().getParameters().put('plns','objproj.id');
        String tabId = System.currentPageReference().getParameters().get('tabId');
        ApexPages.StandardController sc = new ApexPages.standardController(objPlantype);
        PlantypePageController plantypepagecont = new PlantypePageController();     
        plantypepagecont .LoadData() ;
        //try{
        plantypepagecont.DeleteAccount();
     
        plantypepagecont .NewPrtype();
        //plantypepagecont.SelectedPlanId='test';
        try{
            plantypepagecont .plantypedit(); 
        }catch(Exception e){   
            
        }  
    }
    static testMethod void insertplanty1(){
        Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
     	User u2 =new User( Alias = 'newUser1' ,Email ='newuser123@testorg.com',EmailEncodingKey = 'UTF-8',LastName = 'Testing',
     	LanguageLocaleKey='en_US',LocaleSidKey='en_US', UserName='newuser1234@testorg.com',ProfileId=p.Id,TimeZoneSidKey = 'America/Los_Angeles');
     	insert u2; 
        Musqot_member__c plm=new Musqot_member__c();
        plm.musqot__userid__c=u2.id;
        plm.musqot__Role__c='Member';        
        plm.User_type__c='Internal user';
        insert plm;
        System.assertEquals('Member', plm.Role__c);
        plantype__c objPlantype=new plantype__c ();    
        objPlantype.Name='test';    
        objPlantype.Barcolor__c ='test1'; 
        objPlantype.Fieldset__c =null; 
        System.assertEquals('test', objPlantype.name);
        insert objPlantype;
        
        Project__c objproj = new Project__c();
        objproj .Name = 'test';
        objproj .Ends_date__c = system.toDay();
        objproj .Starts_date__c= system.toDay();
        objproj .Status__c = 'In Progress';
        objproj.ownerid=plm.userid__c;
        System.assertEquals('test', objproj .Name );         
        insert objproj;
        
        test.startTest();
        PageReference pageRef = Page.MusqotAdminPage;
        Test.setCurrentPage(pageRef); 
        ApexPages.currentPage().getParameters().put('plns', 'objproj.id');
        String tabId = System.currentPageReference().getParameters().get('tabId');
        ApexPages.StandardController sc = new ApexPages.standardController(objproj);
        PlantypePageController plantypepagecont = new PlantypePageController();     
        plantypepagecont .LoadData() ;
        //try{
        plantypepagecont.DeleteAccount();
        //catch(exception e){}
        plantypepagecont .NewPrtype();
        //plantypepagecont.SelectedPlanId='test';
        try{
            plantypepagecont .plantypedit(); 
        }catch(Exception e){           
        }  
    }    
}