src/objects/OAuthService__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token_URL__c</fullName>
        <label>Access Token URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Authorization_Type__c</fullName>
        <label>Authorization Type</label>
        <picklist>
            <picklistValues>
                <fullName>Request Header (Authorization: Bearer)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Request Header (Authorization: OAuth)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URI Query Parameter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Authorization_URL__c</fullName>
        <label>Authorization URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Auto_import__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is checked then the import will run every day into the enddate</inlineHelpText>
        <label>Auto import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bar_color__c</fullName>
        <defaultValue>&quot;#222,#666,#ccc&quot;</defaultValue>
        <inlineHelpText>This is color to be us in Charts to representation of different data in the performance veiw</inlineHelpText>
        <label>Bar colors</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>Today() + 365</defaultValue>
        <inlineHelpText>After this date will Musqot not collect data from this social media connection.</inlineHelpText>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Page_Id__c</fullName>
        <inlineHelpText>This is to watch a page or webpage. Used in Facebook, Google</inlineHelpText>
        <label>Page ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_ID__c</fullName>
        <inlineHelpText>This is used for watch a Post in Facebook</inlineHelpText>
        <label>Post ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redirect_URL__c</fullName>
        <inlineHelpText>this url is used for create url in the ad incl the ID</inlineHelpText>
        <label>Redirect URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Request_Token_URL__c</fullName>
        <label>Request Token URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Response_Type__c</fullName>
        <label>Response Type</label>
        <picklist>
            <picklistValues>
                <fullName>code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>token</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signature_Method__c</fullName>
        <label>Signature Method</label>
        <picklist>
            <picklistValues>
                <fullName>HMAC-SHA1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PLAINTEXT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Socialmedia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Socialmedia</label>
        <referenceTo>socialmedia_settings__c</referenceTo>
        <relationshipName>OAuth_services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Socialmedia connection</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Socialmedia connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Connectioneditsettingcont.cls
public with sharing class Connectioneditsettingcont {
    Public Id oauthid;
    public String fbLoginURL{get;set;}
    public String accessToken {get;set;}
    public String code {get;set;}
    public String connectionId{get;set;}
    public OAuthService__c oauth{get;set;}
    public Connectioneditsettingcont (ApexPages.StandardController controller){
        oauthid=ApexPages.currentPage().getParameters().get('oauthid');
        oauth= new OAuthService__c();  
        try{            
            oauth= [SELECT Id, Name,Access_Token_URL__c,Authorization_Type__c,Authorization_URL__c, Consumer_Key__c,Consumer_Secret__c,Redirect_URL__c,Request_Token_URL__c,Response_Type__c,Scope__c,Signature_Method__c,Page_Id__c,Bar_color__c,Socialmedia__c,Post_ID__c,Access_Token__c,End_Date__c,Auto_import__c FROM OAuthService__c where id =:oauthid];          
                  }catch(exception e){}
    }
    
     /*public Connectioneditsettingcont() {
       
    } */
     /********update OAuthService**************/
      public PageReference updatecon(){
        if (musqot__OAuthService__c.sObjectType.getDescribe().isUpdateable()){   
            update oauth;            
        }
        String tabId = System.currentPageReference().getParameters().get('tabId');
        string pageRef='/apex/MusqotAdminPage?sfdc.tabName='+tabId+'&tab='+EncodingUtil.urlEncode('mpsett','UTF-8');
        Pagereference pg=new Pagereference (pageRef);
        return pg;
    }
    
    /***** redirect to MusqotAdminPage ********/
    public PageReference cancel(){
        String tabId = System.currentPageReference().getParameters().get('tabId');
        string pageRef='/apex/MusqotAdminPage?sfdc.tabName='+tabId+'&tab='+EncodingUtil.urlEncode('mpsett','UTF-8');
        Pagereference pg=new Pagereference (pageRef);
        return pg;
    }
    /***** test oAuth connection ****/    
    public void testConnection(){         
        oauth = [select id ,Name,Access_Token_URL__c, Authorization_Type__c, Authorization_URL__c,Page_Id__c,Post_ID__c,Consumer_Key__c,Socialmedia__c, Bar_color__c,Consumer_Secret__c, Redirect_URL__c, Request_Token_URL__c, Response_Type__c, Scope__c, Signature_Method__c from OAuthService__c where Id =:ApexPages.currentPage().getParameters().get('cntId')];
        HttpRequest req=new HttpRequest();
        req.setMethod('GET');
        String ReqURL = 'https://graph.facebook.com/oauth/authorize?client_id='+EncodingUtil.urlEncode(oauth.Consumer_Key__c,'UTF-8')+'&redirect_uri=https://'+System.URL.getSalesforceBaseUrl().getHost()+'/apex/Facebook_Connection';
        req.setEndpoint(ReqURL);
        
        HttpResponse res = null;
        http h= new Http();
        res = h.send(req);
        fbLoginURL = res.getHeader('Location');        
        Pagereference pg = new Pagereference (fbLoginURL);                             
    }
    
    /***** import social media data ****/
     
    public void importData(){   
        Cookie langCookie = new Cookie('socialId', connectionId, null, 1446, false);
        ApexPages.currentPage().setCookies(new Cookie[]{langCookie}); 
              
        oauth = [select id ,Name,musqot__Access_Token_URL__c, musqot__Authorization_Type__c, musqot__Authorization_URL__c,Page_Id__c,musqot__Consumer_Key__c,musqot__Socialmedia__c, musqot__Bar_color__c,musqot__Consumer_Secret__c, musqot__Redirect_URL__c, musqot__Request_Token_URL__c, musqot__Response_Type__c, musqot__Scope__c, musqot__Signature_Method__c from musqot__OAuthService__c where Id =:ApexPages.currentPage().getParameters().get('cntId')];
        HttpRequest req=new HttpRequest();
        req.setMethod('GET');
        String ReqURL = 'https://graph.facebook.com/oauth/authorize?client_id='+EncodingUtil.urlEncode(oauth.Consumer_Key__c,'UTF-8')+'&redirect_uri=https://'+System.URL.getSalesforceBaseUrl().getHost()+'/apex/Facebook_Connection';
        req.setEndpoint(ReqURL);
        HttpResponse res = null;
        http h= new Http();
        res = h.send(req);        
        fbLoginURL = res.getHeader('Location'); 
        Pagereference pg = new Pagereference (fbLoginURL);                   
    }           
}