src/objects/OAuthService__c.object
<CustomObject>
    <fields>
        <fullName>Bar_color__c</fullName>
        <defaultValue>&quot;#222,#666,#ccc&quot;</defaultValue>
        <inlineHelpText>This is color to be us in Charts to representation of different data in the performance veiw</inlineHelpText>
        <label>Bar colors</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Social_media__c</fullName>
        <label>Social media</label>
        <picklist>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MailChimp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LinkedIn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YouTube</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vimeo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Socialmedia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Socialmedia</label>
        <referenceTo>socialmedia_settings__c</referenceTo>
        <relationshipName>OAuth_services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Socialmedia connection</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Socialmedia connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/socialmedia_settings__c.object
<CustomObject>
    <description>The Name will show-up in the Performance Gantt view.</description>
    <fields>
        <fullName>Bar_color__c</fullName>
        <defaultValue>&quot;#222,#666,#ccc&quot;</defaultValue>
        <label>Bar color</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chart__c</fullName>
        <inlineHelpText>Select type of charts to show in performance view</inlineHelpText>
        <label>Chart</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Area charts</fullName>
            </value>
            <value>
                <fullName>Bar charts</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Line charts</fullName>
            </value>
            <value>
                <fullName>Spline charts</fullName>
            </value>
            <sorted>true</sorted>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Import_rate__c</fullName>
        <label>Import rate</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Day</fullName>
                <default>true</default>
            </value>
            <sorted>true</sorted>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Socialmedia__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Socialmedia</label>
        <referenceTo>OAuthService__c</referenceTo>
        <relationshipLabel>Socialmedia Settings</relationshipLabel>
        <relationshipName>Socialmedia_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Socialmedia_type__c</fullName>
        <label>Socialmedia type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Page</fullName>
            </value>
            <value>
                <fullName>Ad</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Performance, general</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Performance, project</fullName>
            </value>
            <value>
                <fullName>Performance, marketing activity</fullName>
            </value>
            <value>
                <fullName>Milestone</fullName>
            </value>
            <value>
                <fullName>Performance, costcenter</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Watch_type__c</fullName>
        <label>Watch type</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Unique visitors</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Likes / click</fullName>
            </value>
            <value>
                <fullName>Members</fullName>
            </value>
            <value>
                <fullName>Unique visitor &amp; click/likes</fullName>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Socialmedia Settings</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Socialmedia Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Socialmedia_Edit_Ctrl.cls
public with sharing class Socialmedia_Edit_Ctrl{
    public Socialmedia_settings__c ObjSMS{get;set;}
    public  musqot__Activity__c  mus;
    Public Id socialId;
    public OAuthService__c oauthService;
    public string socialMediaName;
    public Socialmedia_Edit_Ctrl(ApexPages.StandardController controller) {        
        socialid = ApexPages.currentPage().getParameters().get('socialId');
        mus=[SELECT id,Use_Forcasting__c,Use_milestones__c FROM musqot__Activity__c limit 1];
       try{            
            ObjSMS = [select id ,Name, Import_rate__c,Type__c,Socialmedia_type__c,Chart__c,Socialmedia__c,Watch_type__c
                       from Socialmedia_settings__c where id =:socialId];   
       }catch(exception e){}
       oauthService = [select id ,Name,Bar_color__c,Social_media__c  from OAuthService__c 
                                            where Id =:ObjSMS.Socialmedia__c];
               socialMediaName=oauthService.Social_media__c; 
    }

    /********update  Socialmedia_settings__c records ********/
    
    public PageReference updSocial(){
        try{
              // OAuthService__c oauthService = [select id ,Name,Bar_color__c,Social_media__c  from OAuthService__c 
                                        //    where Id =:ObjSMS.Socialmedia__c];
               //socialMediaName=oauthService.Social_media__c;
            
            // added by Narendra -- start --
            if(ObjSMS.Type__c == 'Milestone') {
                try{
                    CronJobDetail cj = [select id, Name from CronJobDetail where Name = :'SocialMediaSettingMilestoneSchedulerJob'];
                    if(cj == null) {
                        // if the job is not running
                        Date tomorrowsDate = System.today().addDays(1);
                        Integer day = tomorrowsDate.day();
                        Integer month = tomorrowsDate.month();
                        Integer year = tomorrowsDate.year();
                        String SchTimer='0 0 1 '+day+' '+month+' ? '+year;   //  next day 1:00 AM
                        System.schedule('SocialMediaSettingMilestoneSchedulerJob', SchTimer, new SocialMediaSettingMilestoneScheduler());
                	}
                }catch(Exception e){
                    System.debug('Exception : ' + e.getMessage());
                }
            }
            // added by Narendra -- end --
            
            if (musqot__Socialmedia_settings__c.sObjectType.getDescribe().isUpdateable()){ 
                ObjSMS.Bar_color__c = oauthService.Bar_color__c;
                update ObjSMS;            
            }
        }catch(exception e){}
        String tabId = System.currentPageReference().getParameters().get('tabId');
        string pageRef='/apex/MusqotAdminPage?sfdc.tabName='+tabId+'&tab='+EncodingUtil.urlEncode('mpsett','UTF-8')+'&fromHome=true'+'&tabm='+socialMediaName;
        Pagereference pg=new Pagereference (pageRef);
        return pg;
    }
    /***** redirect to MusqotAdminPage ********/
    public PageReference cancel(){
        String tabId = System.currentPageReference().getParameters().get('tabId');
        string pageRef='/apex/MusqotAdminPage?sfdc.tabName='+tabId+'&tab='+EncodingUtil.urlEncode('mpsett','UTF-8')+'&fromHome=true'+'&tabm='+socialMediaName;
        Pagereference pg=new Pagereference (pageRef);
        return pg;
    }
     public List<SelectOption> getMyOptions() {
        List<SelectOption> options = new List<SelectOption>(); 
        Schema.DescribeFieldResult field = Socialmedia_settings__c.Type__c.getDescribe();
        for (Schema.PicklistEntry f : field.getPicklistValues()){
            if(mus.Use_milestones__c ==false){
                if(f.getLabel()!='Milestone'){
                  options.add(new SelectOption(f.getLabel(), f.getLabel()));
               }
            }else
            options.add(new SelectOption(f.getLabel(), f.getLabel()));
        }   
        return options;     
   } 
}