src/objects/plantype__c.object
<CustomObject>
    <fields>
        <fullName>sort__c</fullName>
        <label>sort</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <inlineHelpText>Enter a hexadecimal color (excluding #)</inlineHelpText>
        <label>Color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <label>Plan type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sort__c</fullName>
        <label>sort</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent project</label>
        <referenceTo>Subproject__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/subprojectClassTest.cls
/*****************************************************************
Class Name: subprojectClassTest
Author: chaithanya daggumati    Last modified by: G Janardhanreddy
Date: 22/7/2014                 Date:  20/03/2015
********©2013 Musqot marketing technology Pvt ltd ****************/
@isTest(seeAllData=true)
    public class subprojectClassTest{    
    static testMethod void subproject(){
    
    Project_type__c objprojtype = new Project_type__c();
    objprojtype.Name = 'testname'; 
    objprojtype.Color__c = 'red'; 
    objprojtype.musqot__Fieldset__c='testFieldset';
    objprojtype.Plantype__c='co branding';
    objprojtype.sort__c=10;
    System.assertEquals('testname', objprojtype .name);
    insert objprojtype ;
    
    Project__c objproj = new Project__c();
    objproj .name = 'testname';
    objproj .Starts_date__c = System.now().date();
    objproj .Ends_date__c =  System.now().date(); 
    objproj .Description__c = 'sampdesc';
    objproj.Status__c='In Progress';
    System.assertEquals('testname', objproj .name);
    insert objproj;
                       
    Subproject__c objsp = new Subproject__c ();
    objsp .name = 'testname';            
    objsp .Description__c = 'sampdesc';
    objsp .Project_del__c = objsp.Id;
    objsp .Parent_project__c= objproj.Id;
    objsp.Starts_date__c =  System.now().date();
    objsp .Ends_date__c =  System.now().date();
    objsp.Status__c='In Progress';
    System.assertEquals('testname', objsp .name);
    objsp.Project_type__c = objprojtype.id;   
    insert objsp;
        
    test.startTest();
    PageReference pageRef = Page.projectpage;
    Test.setCurrentPage(pageRef);      
    ApexPages.currentPage().getParameters().put('planId', objproj.id);
    ApexPages.currentPage().getParameters().put('subPrjId', objsp.id);
    ApexPages.CurrentPage().getParameters().put('prjId',objsp.id);
    //ApexPages.currentPage().getParameters().put('retURL','rb0000000E6daasd=asdassd');
    //ApexPages.currentPage().getParameters().put('mainStr','rb0000000E6daasd=asdassd');
    ApexPages.StandardController sc = new ApexPages.standardController(objsp);            
    subprojectClass subpcls = new subprojectClass (sc); 
   // subprojectClass subpcls1 = new subprojectClass (); 
    List<SelectOption> temp=subpcls.PROTList;   
    subpcls.fieldSetName='testFieldSet';      
    subpcls.save();
    subpcls.cancel(); 
    subpcls.getFields();
    test.stoptest();                    
    }
   static testMethod void subproject1(){
   
    Project__c objproj = new Project__c();
    objproj .name = 'testname';
    objproj .Starts_date__c = System.now().date();
    objproj .Ends_date__c =  System.now().date(); 
    objproj .Description__c = 'sampdesc';
    objproj.Status__c='In Progress';
    System.assertEquals('testname', objproj .name);
    insert objproj ;
    
    Project_type__c objprojtype = new Project_type__c();
    objprojtype .Name = 'testname'; 
    objprojtype .Color__c = 'red';
    objprojtype.Plantype__c='co branding';
    objprojtype.sort__c=10;
    System.assertEquals('testname', objprojtype .name);
    insert objprojtype ;
    
    Subproject__c objsp = new Subproject__c ();
    objsp .name = 'testname';            
    objsp .Description__c = 'sampdesc';
    objsp .Parent_project__c= objproj.Id;
    objsp .Starts_date__c =  System.now().date();
    objsp .Ends_date__c =  System.now().date();
    objsp.Status__c='In Progress';
    System.assertEquals('testname', objsp .name);
    objsp.Project_type__c = objprojtype.id;
    insert objsp ;
        
    test.startTest();
    PageReference pageRef = Page.projectpage;
    Test.setCurrentPage(pageRef);      
    ApexPages.currentPage().getParameters().put('planId', objproj.id);
    ApexPages.currentPage().getParameters().put('subPrjId', objsp.id);

    ApexPages.StandardController sc = new ApexPages.standardController(objsp);            
    subprojectClass subpcls = new subprojectClass (sc); 
    
    List<SelectOption> temp=subpcls.PROTList;         
    subpcls.save();
    subpcls.cancel(); 
    subpcls.getFields();
    test.stoptest();
    }
   static testMethod void subproject2(){  
    Project__c objproj = new Project__c();
    objproj .name = 'testname';
    objproj .Starts_date__c = System.now().date();
    objproj .Ends_date__c =  System.now().date(); 
    objproj .Description__c = 'sampdesc';
    objproj.Status__c='In Progress';
    System.assertEquals('testname', objproj .name);
    insert objproj ;
    
    Subproject__c objsp = new Subproject__c ();
    objsp .name = 'testname';            
    objsp .Description__c = 'sampdesc';
    objsp .Parent_project__c= objproj.Id;
    objsp .Starts_date__c =  System.now().date()+2;
    objsp .Ends_date__c =  System.now().date()+5;
    objsp.Status__c='In Progress';
    System.assertEquals('testname', objsp .name);
    //objsp.Project_type__c = objprojtype.id;
    insert objsp ;
        
    test.startTest();
    PageReference pageRef = Page.projectpage;
    Test.setCurrentPage(pageRef);      
    ApexPages.currentPage().getParameters().put('planId', objproj.id);
    ApexPages.currentPage().getParameters().put('subPrjId', objsp.id);

    ApexPages.StandardController sc = new ApexPages.standardController(objsp);            
    subprojectClass subpcls = new subprojectClass (sc);     
    List<SelectOption> temp=subpcls.PROTList;         
    subpcls.save();
    subpcls.cancel(); 
    subpcls.getFields();
    test.stoptest();
    }
 }