src/objects/plantype__c.object
<CustomObject>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <inlineHelpText>Enter a hexadecimal color (excluding #)</inlineHelpText>
        <label>Color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <label>Plan type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectTypeClass.cls
/******************************************************************
Class Name: ProjectTypeClass 
Author: chaithanya daggumati       Last modified by: Janardhan reddy
Date : 6/7/2014                    Date : 20/03/2015                    
********©2013 Musqot marketing technology Pvt ltd ******************/

public with sharing class ProjectTypeClass {
    Public List<Project_type__c> projectType{get;set;}
    public ProjectTypeClass(ApexPages.StandardController controller) {
        projectType=[SELECT id,Name,Color__c, Plantype__c 
                     from Project_type__c order by Name LIMIT 250];
    }
    /********************************************
	NewPrtype(): redirect to  NewProjectType page
	*********************************************/
    public PageReference NewPrtype()
    {
        PageReference pg=new PageReference ('/apex/NewProjectType');
        pg.setredirect(true); 
        return pg;
    } 
    
    public PageReference NewPrtyp()
    {
        PageReference pg=new PageReference ('https://eu2.salesforce.com?id='+EncodingUtil.urlEncode(projectType[0].id,'UTF-8'));
        pg.setredirect(true); 
        return pg;
    } 
    
}