src/objects/plantype__c.object
<CustomObject>
    <fields>
        <fullName>Fieldset__c</fullName>
        <description>This should be a choice from Plan field set name</description>
        <label>Fieldset</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <inlineHelpText>Enter a hexadecimal color (excluding #)</inlineHelpText>
        <label>Color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fieldset__c</fullName>
        <description>This should be a choice from Project field set name</description>
        <label>Fieldset</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <label>Plan type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Add your project description here (max 4000 chars)</inlineHelpText>
        <label>Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubprojecteditEditontrollerTest.cls
/*************************************************************
Class Name: SubprojecteditEditontrollerTest
Author:Nagaraju G            Last modified by: G Janardhanreddy
Date: 11/9/2014              Date:  20/03/2015
********©2013 Musqot marketing technology Pvt ltd ************/
@isTest(seeAllData=true)
public class SubprojecteditEditontrollerTest{
      static testMethod void SubprojectControlle(){
      Project__c prj = new Project__c ();
      prj.Name='ITC';
     //prj.Plantype__c= pt.Id;
      prj.Ends_date__c = system.toDay().addDays(3);
      prj.Starts_date__c= system.toDay();
      prj.Status__c = 'In Progress';
      System.assertEquals('ITC', prj.name);         
      insert prj;
      
      Project_type__c objprojtype = new Project_type__c();
      objprojtype .Name = 'testname';
      objprojtype .Color__c = 'red';
      objprojtype .Fieldset__c = 'testfieldset';
      insert objprojtype ;
      System.assertEquals('testname', objprojtype .Name);
     
      Subproject__c objsubpro=new Subproject__c();
      objsubpro.Name='testsub';
      objsubpro.Starts_date__c=System.now().date();
      objsubpro.Ends_date__c=System.now().date();
      objsubpro.Project_type__c=objprojtype.id;
      objsubpro.Description__c = 'testdesc';
      insert objsubpro;
      System.assertEquals('testsub', objsubpro.name);
      Project_type__c  proType = [SELECT Id, Fieldset__c FROM Project_type__c  WHERE Id =:objSubpro.Project_type__c];

      ApexPages.CurrentPage().getparameters().put('projectid',objsubpro.id);
      ApexPages.StandardController sc = new ApexPages.standardController(objsubpro);
      test.startTest();
      //SubprojecteditEditontroller objSUBPR1 = new SubprojecteditEditontroller();
      SubprojecteditEditontroller objSUBPR = new SubprojecteditEditontroller(sc);
      SubprojecteditEditontroller onbj=new SubprojecteditEditontroller();
       
      try{
      List<SelectOption> temp = objSUBPR.PROTList;
      }catch(Exception e){}
      List<SelectOption> sofilter = objSUBPR.SocialFilter;
      List<SelectOption> erfilter = objSUBPR.ERPFilter;
      List<SelectOption> crfilter = objSUBPR.CRMFilter;
      List<Schema.FieldSetMember>  temp2=objSUBPR.getFields();
      String[] plan=objSUBPR.ERPItems;
      String[] plan1=objSUBPR.CRMItems; 
      String[] plan2=objSUBPR.SocialItems;
      List<String> stringList = new List<String>{'string1','string2','string3'};
      objSUBPR.ERPItems= stringList;
      objSUBPR.CRMItems= stringList;
      objSUBPR.SocialItems= stringList;
      objSUBPR.save();
      objSUBPR.cancel();
      objSUBPR.gotoEditMode();
      objSUBPR.gotoInfoMode();
      objSUBPR.getCustomSettRec();
      try{
      objSUBPR.getFieldsetList('string subproId');
       }catch(Exception e){}
      Test.stopTest();
     }
}