src/objects/plantype__c.object
<CustomObject>
    <fields>
        <fullName>Barcolor__c</fullName>
        <description>sample number after # hex color</description>
        <label>Barcolor</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plantype</label>
    <nameField>
        <label>Plantype</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan type</label>
        <referenceTo>plantype__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_type__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <inlineHelpText>Enter a hexadecimal color (excluding #)</inlineHelpText>
        <label>Color</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plantype__c</fullName>
        <label>Plan type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project type</label>
    <nameField>
        <label>Project type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Ends_date__c</fullName>
        <defaultValue>Today() + 45</defaultValue>
        <label>End date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project type</label>
        <referenceTo>Project_type__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Subprojects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starts_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <valueSet>
		<valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#3366FF</color>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#FFCC33</color>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#33CC00</color>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <color>#CC0000</color>
            </value>
			</valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectEditControllerTest.cls
/******************************************************
Class Name: ProjectEditControllerTest
Author:Nagaraju             Last modified by:chaithanya 
Date:19/7/2014              Date: 20/03/2015                    
********©2013 Musqot marketing technology Pvt ltd *****/

@isTest(seeAllData=true)
public class ProjectEditControllerTest{
    static testMethod void ProjectEditController(){
        Project_type__c prjType = new Project_type__c();
        prjType.Name = 'Business';
        prjType.Color__c = 'FFFF01';
        System.assertEquals('Business', prjType.name);
        insert prjType; 
        
        Project__c objproject = new Project__c ();
        objproject.Name='test';
        objproject.Starts_date__c= System.now().date();
        objproject.Ends_date__c= System.now().date();
        System.assertEquals('test', objproject.name);
        insert objproject;
        
        plantype__c objporojetype = new plantype__c ();
        objporojetype.name='test';
        objporojetype.Barcolor__c ='cccccc';
        System.assertEquals('test', objporojetype.name);
        insert objporojetype;
        
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = objproject.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;  
        
        ApexPages.currentPage().getParameters().put('id', prjType.id);
        String tabId = System.currentPageReference().getParameters().get('sfdc.tabName');
        ApexPages.StandardController sc = new ApexPages.standardController(prjType);
        test.startTest();
        ProjectEditController prjeditcon1 = new ProjectEditController (); 
        ProjectEditController prjeditcon = new ProjectEditController (sc);
        List<SelectOption> temp = prjeditcon.PlantypeList; 
        try{
            prjeditcon .ProjectEdit();
        }catch(Exception e){
            system.debug('');
        }
        prjeditcon .getPln();
        try{        
            prjeditcon .LoadData();
        }catch(Exception e){
            system.debug('');
        }
       
        prjeditcon .NewPrtype();
        //try{         
            prjeditcon .DeleteProject();
        //}catch(Exception e){}         
    }
    static testMethod void ProjectEditController1(){
        Project_type__c prjType = new Project_type__c();
        prjType.Name = 'Business';
        prjType.Color__c = 'FFFF01';
        System.assertEquals('Business', prjType.name);
        insert prjType; 
        Project__c objproject = new Project__c ();
        objproject.Name='test';
        objproject.Starts_date__c= System.now().date();
        objproject.Ends_date__c= System.now().date();
        System.assertEquals('test', objproject.name);
        insert objproject;
        plantype__c objporojetype = new plantype__c ();
        objporojetype.name='test';
        objporojetype.Barcolor__c ='cccccc';
        System.assertEquals('test', objporojetype.name);
        insert objporojetype;         
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = objproject.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress'; 
        subPrj.Project_type__c = prjType.Id;
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;         
        Project_type__c objprt=[select id,name from Project_type__c where id=:prjType.id limit 1];
        delete objprt;
        test.startTest();
        PageReference pageRef = Page.ProjectType;
        Test.setCurrentPage(pageRef);       
        ApexPages.currentPage().getParameters().put('planid', prjType.id);
        String tabId = System.currentPageReference().getParameters().get('tabId');
        ApexPages.StandardController sc = new ApexPages.standardController(prjType);
        ProjectEditController prjeditcon1 = new ProjectEditController (); 
        ProjectEditController prjeditcon = new ProjectEditController (sc);
        List<SelectOption> temp = prjeditcon.PlantypeList; 
        //prjeditcon.SelectedPlanId='proj';
        prjeditcon.ProjectId='ProjectId';
        try{
            prjeditcon .ProjectEdit();
        }catch(Exception e){
            system.debug('');
        }
        prjeditcon .getPln();
        try{        
            prjeditcon .LoadData();
        }catch(Exception e){
            system.debug('');
        }
        
        prjeditcon .NewPrtype();
        try{         
            prjeditcon .DeleteProject();
        }catch(Exception e){}           
                 
    }
 static testMethod void projecteditdelete(){
        Project__c objproject = new Project__c ();
        objproject.Name='test';
        objproject.Starts_date__c= System.now().date();
        objproject.Ends_date__c= System.now().date();
        System.assertEquals('test', objproject.name);
        insert objproject;
                
        Subproject__c subPrj = new Subproject__c();         
        subPrj.Name='ITC Project';
        subPrj.Parent_project__c = objproject.Id;
        subPrj.Ends_date__c = system.toDay().addDays(3);
        subPrj.Starts_date__c= system.toDay();
        subPrj.Status__c = 'In Progress';         
        System.assertEquals('ITC Project', subPrj.name);     
        insert subPrj;  
        
        PageReference pageRef = Page.MusqotAdminPage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('proj', subPrj.id);       
        ApexPages.StandardController sc = new ApexPages.standardController(subPrj);
        ProjectEditController projeditcot = new ProjectEditController();
        try{   
        projeditcot.DeleteProject();
        }catch(Exception e){}
         }
}