src/objects/Project__c.object
<CustomObject>
    <customHelpPage>Planshelppage</customHelpPage>
    <description>Main Plan container</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subproject__c.object
<CustomObject>
    <customHelpPage>Projects_help_page</customHelpPage>
    <fields>
        <fullName>Parent_project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Subproject_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PopulateClass.cls
/***********************************************************
Class Name: PopulateClass
Author:Nagaraju           Last modified by:G Janardhan reddy
Date :18/7/2014           Date : 20/03/2015                    
********©2013 Musqot marketing technology Pvt ltd **********/
public with sharing class PopulateClass {
    Subproject__c NewSub=New Subproject__c();
    Id Pageid;
    public PopulateClass(ApexPages.StandardController controller) {
        try
        {
            NewSub= (Subproject__c)controller.getRecord();
            Pageid=NewSub.Parent_project__c;
            Project__c sid=[Select id,Name from Project__c where id =:Pageid];
        }
        Catch(Exception e)
        {
        }
    }
    Public PageReference onLoad()
    {
              return null;
    }
}