src/objects/Purchase_order_setting__c.object
<CustomObject>
    <fields>
        <fullName>PO_Autoprefix__c</fullName>
        <inlineHelpText>This prefix will be use when registration &quot;wild&quot; Invoice</inlineHelpText>
        <label>PO prefix auto</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_External__c</fullName>
        <inlineHelpText>Will be use for third party  purchase order integration</inlineHelpText>
        <label>PO prefix ext</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Lastnumber__c</fullName>
        <label>Last used number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PO_Prefix__c</fullName>
        <inlineHelpText>Prefix for purchase order  when you create in Musqot</inlineHelpText>
        <label>PO Prefix</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Startnumber__c</fullName>
        <label>Start number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase order setting</label>
    <nameField>
        <label>Purchase order setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase order settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PurchasingOrderClass.cls
/***********************************************************
Class Name: PurchasingOrderClass  
Author:chaithanya daggumat        Last modified by:Nagaraju G
Date:16/7/2014                    Date:18/03/2015
********©2013 Musqot marketing technology Pvt ltd **********/

public with sharing class PurchasingOrderClass {
    Public Purchase_order_setting__c pos{get;set;}
    public PurchasingOrderClass(ApexPages.StandardController controller) 
    {
        pos=[SELECT id,Name,PO_Startnumber__c,PO_Prefix__c,PO_Autoprefix__c,PO_External__c,PO_Lastnumber__c FROM Purchase_order_setting__c LIMIT 1];
    }
    /**************************************************
	Editpage():redirect to PurchaseOrderSettingEditPage
	****************************************************/  
    Public PageReference Editpage()
    {
        PageReference pg=new PageReference ('/apex/PurchaseOrderSettingEditPage?id='+EncodingUtil.urlEncode(pos.id,'UTF-8'));
        return pg;
    }
     /***********************************************
	 Save():redirect to PurchaseOrderSettingEditPage 
	************************************************/  
    Public PageReference Save()
    {
        PageReference pg=new PageReference ('/apex/PurchaseOrderSettingEditPage?id='+EncodingUtil.urlEncode(pos.id,'UTF-8'));
        return pg;
    }
     /****************************************************
		Cancel(): redirect to PurchaseOrderSettingEditPage 
	 *****************************************************/  
    Public PageReference Cancel()
    {
        PageReference pg=new PageReference ('/apex/PurchaseOrderSettingEditPage?id='+EncodingUtil.urlEncode(pos.id,'UTF-8'));
        return pg;
    }
    Public PageReference CloneRec()
    {
        return Null;
    }
    Public PageReference DeleteRec()
    {
        return Null;
    }
}