src/objects/Purchase_order_setting__c.object
<CustomObject>
    <fields>
        <fullName>PO_Startnumber__c</fullName>
        <label>Start number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase order setting</label>
    <nameField>
        <label>Purchase order setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase order settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PurchasingOrderClassTest.cls
/**********************************************************
Class Name: PurchasingOrderClassTest
Author:chaithanya daggumati     Last modified by: chaithanya 
Date: 21/7/2014                  Date: 18/2/2015 
********©2013 Musqot marketing technology Pvt ltd **********/

@isTest
    public class PurchasingOrderClassTest{
        static testMethod void PurchasingOrder(){
        Purchase_order_setting__c objposo = new Purchase_order_setting__c();
        objposo .name = 'testrec';
        objposo .PO_Startnumber__c = 1;
        System.assertEquals('testrec', objposo .name);
        insert objposo ;
        ApexPages.currentPage().getParameters().put('id', objposo .id);
        ApexPages.StandardController sc = new ApexPages.standardController(objposo );
        test.startTest();
        PurchasingOrderClass pocs = new PurchasingOrderClass(sc);                    
        pocs .Editpage();
        pocs .Save();
        pocs .Cancel();
        pocs  .CloneRec();
        pocs  .DeleteRec();       
        }
        }